### ISSUE TITLE
Error apparently when no add_constraint(...) is called

### ISSUE THREAD

**Issue by sburer** [dirkschumacher/ompr#102]
In the attached example, a valid LP is specified using just lower and upper bounds, but an error is encountered when no add_constraint(...) is called. Calling a redundant add_constraint(...) solves correctly.

OMPR package version ‘0.4.0.9001’

[2016-10-31_minimal_example.txt](https://github.com/dirkschumacher/ompr/files/562461/2016-10-31_minimal_example.txt)

**Comment by dirkschumacher** [comment]
Thanks a lot. I will look into it.

**Comment by dirkschumacher** [comment]
That was a bug interfacing with `ROI`. Should be fixed now in `ompr.roi`.
