### ISSUE TITLE
Incorrect solution

### ISSUE THREAD

**Issue by prubin73** [dirkschumacher/ompr#103]
I'm trying to test ompr on a MIP classification model, but I'm getting what seems to be an incorrect solution. I've attached the example as an R notebook (requires you have a recent version of RStudio -- if not, let me know and I'll try to export it as an R script). The model formulates and solves, but the solution violates the first constraint (and many others, I think). Possibly I'm doing something wrong, but I've tried to double and triple check it.

[ompr_demo.zip](https://github.com/dirkschumacher/ompr/files/574068/ompr_demo.zip)

**Comment by dirkschumacher** [comment]
Thanks a lot! I will look into this as soon as I can.

**Comment by dirkschumacher** [comment]
Thanks again. I found a bug that I think I fixed. I tried the model with GLPK and it did not produce any warnings. The warnings were an indicator that something went wrong.

Would you mind installing the most recent version of the package via `devtools::install_github("dirkschumacher/ompr")` and rerun your model? Is it working now?

**Comment by prubin73** [comment]
It's working now. Thanks for the quick fix! I did find one other problem (fairly minor). I'll look through your open issues and, if I don't find it, file a new issue in a few minutes.
