### ISSUE TITLE
Error "The expression contains a variable that is not part of the model."

### ISSUE THREAD

**Issue by sburer** [dirkschumacher/ompr#104]
Attached model yields error "The expression contains a variable that is not part of the model." Although the model uses indexing in a way that doesn't seem to be necessary, I believe the model has been specified correctly. (In addition, this example is a minimal example that I noticed from a bigger example in which indexing was necessary.)

ompr version  ‘0.5.0’
ompr.roi version ‘0.4.1.9000’

[2016-11-08_minimal_example.txt](https://github.com/dirkschumacher/ompr/files/579116/2016-11-08_minimal_example.txt)

**Comment by dirkschumacher** [comment]
It looks like there is a typo in `sum_epxr` => `sum_expr`

```R
model <- MIPModel()
model <- add_variable(model, x[1])
model <- add_constraint(model, sum_epxr(x[i], i = 1) >= 0)
```

**Comment by sburer** [comment]
So sorry for my silly mistake. Thanks!

**Comment by dirkschumacher** [comment]
@sburer Happened to me as well. I think I should implement a better warning message in this case.
