### ISSUE TITLE
Cannot use "c" as a variable name?

### ISSUE THREAD

**Issue by prubin73** [dirkschumacher/ompr#105]
`MIPModel() %>% add_variable(c, type = "continuous")`

produces error message

> Error in add_variable_.optimization_model(model = model, variable = lazyeval::lazy(variable),  : 
>   The variable definition does not seem to be right. Take a look at the example models on the website on how to formulate variables

**Comment by dirkschumacher** [comment]
Thanks. Will look into it. I guess it conflicts with the standard `c` definition.

**Comment by prubin73** [comment]
That was my first thought, and it might be right. On the other hand, "t" is also defined as a function (transpose) in the base package, and there is no problem naming a variable "t".

**Comment by dirkschumacher** [comment]
Ok, I found the bug. Turns out `lazyeval::lazy(c)` does not lead to `c`but to `.Primitive("c")`. Maybe a bug in lazyeval, maybe a feature. But I wasn't expecting that.

I wrote an issue (in case it is a bug):
https://github.com/hadley/lazyeval/issues/91
