### ISSUE TITLE
Error when indices used in sum_expr(...) condition already have values in workspace

### ISSUE THREAD

**Issue by sburer** [dirkschumacher/ompr#106]
The code

```
rm(list = ls())

library(dplyr)
library(ROI)
library(ROI.plugin.glpk)
library(ompr)
library(ompr.roi)

print(packageVersion("ompr"))
print(packageVersion("ompr.roi"))

# Commenting out the following two lines seems to fix the error

i <- 2
j <- 2

model <- MIPModel()

# Setup four variables x[i, j]

model <- add_variable(model, x[i, j], i = 1:2, j = 1:2)

# Set objective x[1, 2] + x[2, 1]

model <- tryCatch(
    set_objective(model,
        sum_expr(x[i, j], i = 1:2, j = 1:2, i != j),
        "min"),
    error = function(x) { x }
    )

print(model$message)
```

produces the output

```
[1] ‘0.5.0.9000’
[1] ‘0.4.1.9000’
[1] "The number of different indexes for sum_expr is 0."
```

It appears to me that the error is caused by the lines assigning values to `i` and `j` conflicting with the condition `i1 != i2` used in `sum_expr(...)`.

**Comment by dirkschumacher** [comment]
This one is a bit tricky. What happens is that `sum_expr(x[i, j], i = 1:2, j = 1:2, i != j)` gets bound first and variables `i` and `j`are being set to 2. Then the new expression `sum_expr(x[i, j], i = 1:2, j = 1:2, 2 != 2)` gets evaluated which results in a sum of length zero as `2!=2` is always false.

I guess the solution would be to first collection the bound indexes and then evaluate any filter expressions without binding any indexed variables.

**Comment by dirkschumacher** [comment]
Should be fixed now I think.
