### ISSUE TITLE
Possible to have model without objective, i.e., just search for feasibility?

### ISSUE THREAD

**Issue by sburer** [dirkschumacher/ompr#107]
Sometimes it is nice to be able to *not* specify an objective and just search for a feasible solution. Is this possible with OMPR? The following code gives the error below:
```
rm(list = ls())

library(dplyr)
library(ROI)
library(ROI.plugin.glpk)
library(ompr)
library(ompr.roi)

print(packageVersion("ompr"))
print(packageVersion("ompr.roi"))

# Setup model with single variable 0 <= x <= 1 but no objective

model <- MIPModel()
model <- add_variable(model, x, lb = 0, ub = 1)

result <- tryCatch(
    solve_model(model, with_ROI(solver = "glpk", verbose = TRUE)),
    error = function(x) { x }
)

print(result$message)
```

```
[1] ‘0.5.0.9000’
[1] ‘0.4.1.9000’
[1] "attempt to set 'colnames' on an object with less than two dimensions"
```

**Comment by dirkschumacher** [comment]
You can say `set_objective(0)`. But I guess that could be the default. What do you think?

**Comment by sburer** [comment]
Oh, that's certainly easy enough, but I guess having that as the default might be nice.

**Comment by dirkschumacher** [comment]
Fixed now in the most recent version of `ompr.roi`: https://github.com/dirkschumacher/ompr.roi/commit/6314318eccbc8eee6f2bddb19b734eab90a18636

Thanks again for the report!
