### ISSUE TITLE
Formulas at https://dirkschumacher.github.io/ompr/articles/problem-warehouse-location.html

### ISSUE THREAD

**Issue by hoehleatsu** [dirkschumacher/ompr#111]
In the section "The mathematical model" you use equations contains, e.g., the variable transportcost_{i,j}. I'd prefer to put transportcost into \texttt or \operatorname as it otherwise looks like it's a product of variables, i.e. t*r*a*n*s*p*o*r*t*c*o*s*t. Also, shouldn't your "min" say what variables are to be minimized? I guess it's the x_{i,j} and the y_j?

... In this article we will generate it randomly. -> Well, I'd say it's artificial data?

Plot of locations (warehouse & customers) -> why not use different plot symbols as well as a ggplot legend for this? I mean these are two fundamentally different things.

...with an objective value of 3.322210^{4}.  -> Why not use sprintf("%.2f", res) here? It's some ten-thousands...no need for scientific notation here IMHO

Last picture: This really looks cool! However, it would again be good to have an explanation in the legend. For example (if I got it right): light red means warehouses not needed?

Altogether: Nice work! Any easy way to illustrate this with some more real data? Also, is the Euclidean metric always the best metric?

**Comment by dirkschumacher** [comment]
Thanks. Valid points :) I will incorporate your suggestions when I have time.

**Comment by dirkschumacher** [comment]
Made some changes to the article. Thanks for the suggestions.

Re. Euclidean distances. For the artificial grid on the plane I think it is a good metric. The model itself does not make any assumptions on the costs. In practice the cost would probably be based on road distances. I was too lazy to combine it with real map data :)

Re. real data. I don't know. Maybe there are some use cases where the data is open. Also more constraints would be interesting.
