### ISSUE TITLE
Gurobi support

### ISSUE THREAD

**Issue by kkmann** [dirkschumacher/ompr#113]
Hey, 

okay, first of all: JuMP for R - my dreams are comming true ;) Thanks for getting this started!

Is there any hope of getting Gurobi support in the not so distant future?

**Comment by chrisflath** [comment]
If we can get the A Matrix, the b vector, inequality signs as well as the variable types one could dirdctly leverage Gurobi's R Interface.

**Comment by dirkschumacher** [comment]
The easiest way to get this started would be to write a plugin for ROI. Then one could use the `ompr.roi` package. Side effect would be that people using ROI directly could also use Gurobi. 

I recently added some [helper functions](https://dirkschumacher.github.io/ompr/reference/index.html#section-solver-developer-functions) to extract the Matrix, b vector, bounds etc. So what @chrisflath suggested would also be possible. 
See `ompr.roi` [code](https://github.com/dirkschumacher/ompr.roi/blob/master/R/with-roi.R) as an example.

**Comment by ggsdc** [comment]
Maybe this can help:

https://github.com/kuol/ROI.plugin.gurobi

I have a problem installing it with the following error message:

```
> system("R CMD INSTALL ROI.plugin.gurobi_0.0-1.tar.gz")
* installing to library 'C:/Users/Guillermo/Documents/R/win-library/3.3'
* installing *source* package 'ROI.plugin.gurobi' ...
** R
** preparing package for lazy loading
** help
No man pages found in package  'ROI.plugin.gurobi' 
*** installing help indices
** building package indices
** testing if installed package can be loaded
Error : .onLoad failed in loadNamespace() for 'ROI.plugin.gurobi', details:
  call: get(name, envir = asNamespace(pkg), inherits = FALSE)
  error: object 'get_solver_name' not found
Error: loading failed
Execution halted
ERROR: loading failed
* removing 'C:/Users/Guillermo/Documents/R/win-library/3.3/ROI.plugin.gurobi'
Warning message:
running command 'R CMD INSTALL ROI.plugin.gurobi_0.0-1.tar.gz' had status 1
```

Maybe you have better luck.

**Comment by chrisflath** [comment]
Ok this worked nicely for me - thanks dirk for pointing me towards the helper functions. I was able to very easily solve the WLP example. Will verify general compatibility later on.

I really like ```ompr``` a lot already!

```
require(gurobi)

modelConstraints = extract_constraints(model)
variables = variable_types(model)
variables = as.character(variables)

variables[grepl("binary",variables)]="B"
variables[grepl("continuous",variables)]="C"
variables[grepl("integer",variables)]="I"

modelConstraints$direction[grepl("==",modelConstraints$direction)]="="

gurobiModel = list()
gurobiModel$A = modelConstraints$matrix
gurobiModel$obj = objective_function(model)$vector
gurobiModel$sense = modelConstraints$direction
gurobiModel$rhs = modelConstraints$rhs
gurobiModel$vtype = variables
gurobiModel$modelsense = "min"

solved = gurobi(gurobiModel)

varNames = variable_keys(model)

names(solved$x) = varNames
result = new_solution(model, solved$objval, "optimal", solved$x)
```

**Comment by dirkschumacher** [comment]
There is now a ROI plugin being developed by the maintainers of ROI:
https://r-forge.r-project.org/scm/viewvc.php/pkg/ROI.plugin.gurobi/?root=roi
