### ISSUE TITLE
underscores in variable names

### ISSUE THREAD

**Issue by tecb1234** [dirkschumacher/ompr#115]
Hi Dirk, firstly this is an awesome package. It really is a step change in working with optimisation models in R.  Thanks very much!

I think I've found a bug related to variables that have an underscore in the variable name.  To explain, this example gives us the constraint matrix we would expect.

```
library(ompr)
library(magrittr)

model <- MIPModel() %>%
  add_variable(x[i], i = 1:3) %>%
  set_objective(sum_expr(x[i], i = 1:3)) %>%
  add_constraint(x[1] == 1)

extract_constraints(model)$matrix
#>      [,1] [,2] [,3]
#> [1,]    1    0    0
```

But if the variable name is changed to `x_a` then we get a constraint matrix with all zero entries:

```
library(ompr)
library(magrittr)

model <- MIPModel() %>%
  add_variable(x_a[i], i = 1:3) %>%
  set_objective(sum_expr(x_a[i], i = 1:3)) %>%
  add_constraint(x_a[1] == 1)

extract_constraints(model)$matrix
#>      [,1] [,2] [,3]
#> [1,]    0    0    0
```

Apologies if I'm missing something!

**Comment by dirkschumacher** [comment]
Thanks. Will look into it. It does look like a bug.
