### ISSUE TITLE
ROI package

### ISSUE THREAD

**Issue by Tecumse44372** [dirkschumacher/ompr#116]
Calling library(ROI) Generates this error:

> library(ROI)
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called ‘slam’
Error: package or namespace load failed for ‘ROI’
> library(ROI.plugin.glpk)
Error in library(ROI.plugin.glpk) : 
  there is no package called ‘ROI.plugin.glpk’

**Comment by dirkschumacher** [comment]
It seems like you need to install the `slam` package first.

**Comment by Tecumse44372** [comment]
Thanks! I did and it works fine now. 

Er
