### ISSUE TITLE
missing the constraint relation

### ISSUE THREAD

**Issue by rickyars** [dirkschumacher/ompr#117]
Not sure if this is a bug, but I can't figure out what I'm doing wrong here:

```
library(ompr)
library(tidyverse)

I <- 10 # trips
K <- 5  # types of aircraft
C <- 3  # regions

set.seed(12345)

# compute the fixed cost of aircraft k
f.cost <- sample(1:10, K, TRUE)

# compute the variable cost of aircraft k
v.cost <- data.frame(
  crossing(i = 1:I, k = 1:K) %>%
  mutate(cost = sample(1:10, n(), TRUE)) %>%
  spread(k, cost) %>%
  select(-i)
)

# create some demand: indicator if trip is in region (can only be in one region for now)
demand <- c(1, rep(0, C - 1))
demand <- data.frame(
  crossing(i = 1:I, c = 1:C) %>%
    group_by(i) %>%
    mutate(pax = sample(demand)) %>%
    spread(c, pax) %>%
    ungroup() %>%
    select(-i)
)

model <- MIPModel() %>%
  
  # [integer] number of aircraft of type k needed in region c
  add_variable(fleet[k, c], k = 1:K, c = 1:C, type = "integer", lb = 0, ub = Inf) %>%
  
  # [integer] number of trips on trip i when flown by aircraft of type k in region c
  add_variable(mm[i, k, c], i = 1:I, k = 1:K, c = 1:C, type = "integer", lb = 0, ub = Inf) %>%
  
  # [binary] indicates if trip i is flown by aircraft of type k in region c
  add_variable(sm[i, k, c], i = 1:I, k = 1:K, c = 1:C, type = "binary") %>%
  
  # minimize cost
  set_objective(
    sum_expr(mm[i, k, c] * v.cost[i, k], i = 1:I, k = 1:K, c = 1:C) + 
      sum_expr(fleet[k, c] * f.cost[k], k = 1:K, c = 1:C), 
    "min") %>%
  
  # satisfy all trip demand 
  add_constraint(sum_expr(sm[i, k, c], k = 1:K) >= demand[i, c], i = 1:I, c = 1:C) 
```
Which produces the following error:
```
Error in add_constraint_.optimization_model(model, lazyeval::as.lazy(substitute(constraint_expr),  : 
  Does not recognize constraint expr. Missing the constraint relation
```

**Comment by rickyars** [comment]
I figured it out! You can't have an index variable called "c"!

Perhaps this is related to issue #105?

**Comment by dirkschumacher** [comment]
Interesting. Thanks! I will look into this. Might be related

**Comment by dirkschumacher** [comment]
So, apparently the argument dispatch gets a bit confused if an indexed variable has the name `c`. In this case the content of `c` and `constraint_expr` gets exchanged. 

That seems to be a general problem in R and not particularly related to `ompr`. I'll try to find out if this is a bug or feature. 
```R
f <- function(some_var, ...) list(some_var, ...)
f("first", i = "second")
> [[1]]
> [1] "first"
> $i
> [1] "second"

f("first", s = "second")
> [[1]]
> [1] "second"
> [[2]]
> [1] "first"
```

**Comment by dirkschumacher** [comment]
Ok. The problem is R's partial function argument matching. It tries to match `c` with the `constraint_expr` argument.

**Comment by tecb1234** [comment]
I've just come across a similar (the same?) issue affecting using the letter `m` as an index.
```
library(ompr)
library(magrittr)
model <- MIPModel() %>%
  add_variable(x[m], m = 1:3)
#> Error in UseMethod("add_variable_"): no applicable method for 'add_variable_' applied to an object of class "c('integer', 'numeric')"
```

But bizarrely, the letter `c` seems fine... 

```
library(ompr)
library(magrittr)
model <- MIPModel() %>%
  add_variable(x[c], c = 1:3)
```

**Comment by dirkschumacher** [comment]
@tecb1234 it is the same problem that R does partial argument matching. Your letter `m` is matched to the argument `model` of `add_variable`. Thus the error that it could not find a proper method to apply to `1:3`.

I wonder what the best solution would be. A heuristic that tries to detect these cases? E.g. if any indexed variable is equal to m, check if that was matched to a wrong argument...

**Comment by dirkschumacher** [comment]
Also other packages such as `dplyr` don't handle this issue:
`dplyr::mutate(mtcars, .d = 1)`

I guess one sensible approach is to rename arguments and add a leading `.` to them like in dplyr. Thus users only choosing `.m` as an index name will run into problems.

**Comment by rickyars** [comment]
Dirk, I think that makes sense.

**Comment by dirkschumacher** [comment]
Renaming the parameters hurts, but since it is not on CRAN yet, now is still time :)

**Comment by eileen-1** [comment]
### 
I also encountered the similar error and couldn't figure out why. Could you please kindly help me?

"Error: Does not recognize constraint expr. Missing the constraint relation"

I was trying to write a staff/job schedule. My code is as follows.
```
## define variables

# define total number of staffs to be scheduled work on
num_staff = 10
# define total number of job need to allocate staff to
num_job = 10
# define total number of week to schedule on
num_week = 15

# define budget days for each job j - Budget [j]
Budget <- c(10, 15, 20, 25, 18, 20, 23, 21, 19, 21)

## schedule model

library(dplyr)
library(magrittr)
library(ROI)
library(ROI.plugin.glpk)
library(ompr)
library(ompr.roi)

model <- MIPModel()%>%
  
  # 1 iff staff i is scheduled to work on job j on week k (assume staff on job j throughout the week, not partial week)
  add_variable (Staff[i, j, k], i = 1:num_staff, j = 1: num_job, k = 1:num_week, type = "binary" ) %>%
  
  # 1 iff job j is scheduled on week k
  add_variable (Job[j, k], j = 1:num_job, k = 1:num_week, type = "binary") %>%
  
  # integer iff extra resources are required for job j, extra resource cannot be negative
  add_variable (Resource[j], j = 1:num_job, type ="integer", lb = 0) %>%
  
  # staff i only do one job in week k
  add_constraint (sum_expr(Staff[i, j, k], j = 1:num_job) == 1, i = 1:num_staff, k = 1:num_week) %>%
  
  # total staff work on an audit j should no more than audti budget days
  add_constraint(sum_expr(Staff[i, j, k], i = i:num_staff, k = 1:num_week) <  Budget[j], j = 1:num_job) %>%
  
  # when staff cannot fully fulfil the budget days, extra resources are required
  add_constraint (sum_expr(Staff[i,j,k], i=1:num_staff, k=1:num_week) + Resource[j] == Budget[j], j=1:num_job) %>%
  
  # Extra resource cannot exceed total budget days
  add_constraint (Resource[j] < Budget[j], j = 1:num_job) %>%

  # Extra resource cannot be negative
  add_constraint (Resource[j] >= 0, j = 1:num_job) %>%
  
  # at least one staff will be scheduled on one job (i.e. one job can't solely rely on Resource)
  add_constraint (sum_expr(Staff[i,j,k],i=1:num_staff) >= Job[j,k], j= 1:num_job, k= 1:num_week) %>%
  
  #Staff cannot exceed ones'availability
  add_constraint (sum_expr(Staff[i,j,k],j = 1:num_job, k = 1:num_week) <= 15, i = 1:num_staff) %>%
  
  # maximize utilisation of staff (linear integer optimisation)
  set_objective(sum_expr(Staff[i,j,k], i = 1:num_staff, j = 1:num_job, k = 1:num_week), "max") %>%

  # set up solver method #
    solve_model(with_ROI(solver = "glpk"))
  
  #print out solution
  #
  #get_solution(Staff[i,j,k])
  filter(value > 0) %>%
  arrange(i)
```
Thank you!

**Comment by dirkschumacher** [comment]
@eileen-1 I guess the problem is that you use a strict inequality. But I have not run the model myself.
´add_constraint (Resource[j] < Budget[j], j = 1:num_job) %>%´

**Comment by eileen-1** [comment]
It works!! By relaxing a couple of strict inequality constraints, the error message disappeared. 
Also changed this line, I had a typo in the code above:
`add_constraint(sum_expr(Staff[i, j, k], i = 1:num_staff, k = 1:num_week) <=  Budget[j], j = 1:num_job) %>%`

A big ### THANKYOU for your help!

**Comment by Preeth073** [comment]
Hi All, 
I require a help from you.
I am getting an error when trying to solve this basic TSP: 

`library(ompr.roi)
library(ompr)
library(ROI.plugin.glpk)
library(dplyr)

dist_matrix<-matrix(data=c(1000,30,50,90,40,1000,20,80,30,30,1000,60,20,15,10,1000),4,4,byrow = TRUE)
n<-4
model_ts<-MIPModel()%>%
  add_variable(x[i,j],i=1:n,j=1:n,type="binary")%>%
  add_variable(u[i],i=1:n,lb=1,ub=n)%>%
  set_objective(sum_expr(dist_matrix[i,j]*x[i,j],i=1:n,j=1:n),sense="min")%>%
  add_constraint(sum_expr(x[i,j]==1,i=1:n),j=1:n)%>%
  add_constraint(sum_expr(x[i,j]==1,j=1:n),i=1:n)%>%
  add_constraint(x[i,i]==0,i=1:n)%>%
  add_constraint((u[i]-u[j]+n*x[i,j])<=(n-1),i=1:n,j=2:n,i!=j)%>%
  solve_model(with_ROI("glpk",verbose=TRUE))

get_solution(model_ts,x[i,j])`

The error is:
`Error: Does not recognize constraint expr. Missing the constraint relation`

Based on this thread, I tried renaming but couldn't get rid of it. 
@dirkschumacher or any others please help me out as I would be using `ompr` package for my current master's project.
Many Thanks:)

PS: This formulation is a simplified one of https://dirkschumacher.github.io/ompr/articles/problem-tsp.html

**Comment by sbmack** [comment]
```
  add_constraint(sum_expr(x[i,j]==1,i=1:n),j=1:n)%>%
  add_constraint(sum_expr(x[i,j]==1,j=1:n),i=1:n)%>%
  add_constraint(x[i,i]==0,i=1:n)%>%
```
I don't see the operators `<=, == , >=` in those constraints.

**Comment by Preeth073** [comment]
Thanks for pointing out.
