### ISSUE TITLE
how to specify stopping criteria

### ISSUE THREAD

**Issue by rickyars** [dirkschumacher/ompr#118]
Is there a way to set stopping criteria for models? E.g., it would be nice to stop either by time or by gap. 

Also, I apologize for using the issue tracker as a help forum. If there is a more appropriate location. Please let me know. Perhaps stackoverflow?

**Comment by dirkschumacher** [comment]
That would be done on the solver level and not in the model. If you use `ompr.roi` there might be some solver options in the specific ROI solvers.

**Comment by rickyars** [comment]
I'm a bit confused, will `ompr.roi` just pass through arguments to the solver. 

I found this blog to be a very good overview of optimization in R:
http://strimas.com/prioritization/ilp-field-guide/

In it they talk about setting stopping criteria in the different packages. E.g., the `glpkAPI` packages can set the gap like this:

```
# gap to optimality
  glpkAPI::setMIPParmGLPK(MIP_GAP , gap)
```
I think this is an important feature.

**Comment by rickyars** [comment]
Dirk,

I'll test this out later and update, but I wanted to think out loud a bit first. I think it should be possible through the ROI package. E.g., Rsymphony will take a gap parameter or time limit, so I presume this will just get passed down. However, Rglpk does not have any such parameters, so it won't be possible. I'll test later today and let you know.

**Comment by rickyars** [comment]
Yup. I tested today:

```
result <- solve_model(model, with_ROI(solver = "symphony", verbosity = 1, gap_limit = 0.1))
```

**Comment by dirkschumacher** [comment]
Nice. Yes, I guess it depends on the ROI bindings to the specific solvers. Kurt Hornik et al. are the maintainers. I am sure they would be happy about contributions :)
