### ISSUE TITLE
Link to Contributor Code of Conduct not working

### ISSUE THREAD

**Issue by hoehleatsu** [dirkschumacher/ompr#126]
Link on https://dirkschumacher.github.io/ompr.docs/ to https://dirkschumacher.github.io/ompr.docs/CONDUCT.md appears not to work atm.

**Comment by dirkschumacher** [comment]
Should be fixed once github pages cache invalidates.
https://github.com/dirkschumacher/ompr.docs/commit/14d1209b114b8e6c66b19f226fb054086999d792
