### ISSUE TITLE
ompr fails to return a result when model stops prematurely

### ISSUE THREAD

**Issue by rickyars** [dirkschumacher/ompr#131]
Using symphony there are several ways to stop the model early. E.g., you can set `first_feasible` to `TRUE` or use `time_limit` to prematurely stop the optimization. However, ompr fails to return a result when you do this. 

Let's modify the bin packing example from the ompr GitHub homepage:
```
library(dplyr)
library(ROI)
library(ROI.plugin.symphony)
library(ompr)
library(ompr.roi)
max_bins <- 10
bin_size <- 3
n <- 10
weights <- runif(n, max = bin_size)
MIPModel() %>%
  add_variable(y[i], i = 1:max_bins, type = "binary") %>%
  add_variable(x[i, j], i = 1:max_bins, j = 1:n, type = "binary") %>%
  set_objective(sum_expr(y[i], i = 1:max_bins), "min") %>%
  add_constraint(sum_expr(weights[j] * x[i, j], j = 1:n) <= y[i] * bin_size, i = 1:max_bins) %>%
  add_constraint(sum_expr(x[i, j], i = 1:max_bins) == 1, j = 1:n) %>%
  solve_model(with_ROI(solver = "symphony", verbosity = 1, first_feasible = TRUE)) %>% 
  get_solution(x[i, j]) %>%
  filter(value > 0) %>%
  arrange(i)
```
The only difference is the addition of `first_feasible = TRUE` in the call to `solve_model`. The result is:
```
[1] variable i        j        value   
<0 rows> (or 0-length row.names)
```

**Comment by rickyars** [comment]
Hmm, this might be a problem with the ROI package.

**Comment by rickyars** [comment]
Yeah, the problem is with ROI:
```
library(ROI)
mat <- matrix(c(3, 4, 2,
                2, 1, 2,
                1, 3, 2), nrow=3, byrow=TRUE)
lp <- OP(objective = c(2, 4, 3),
         constraints = L_constraint(L = mat,
                                    dir = c("<=", "<=", "<="),
                                    rhs = c(60, 40, 80)),
         maximum = TRUE)
```
Normal:
```
sol <- ROI_solve(lp, solver = "symphony")
sol
```
Result:
```
Optimal solution found.
The objective value is: 7.666667e+01
```
First feasible:
```
sol <- ROI_solve(lp, solver = "symphony", first_feasible = TRUE)
sol
```
Result:
```
No solution found.
The solver message was: TM_FINISHED
The objective value is: NA
```
I sent an email to Stefan Theussl about it. Hopefully he responds.

**Comment by dirkschumacher** [comment]
Thanks for looking into this

**Comment by dirkschumacher** [comment]
@rickyars any news on this? It seems like with `glpk` the same happens. If the search process terminates due to a time limit, no solution is returned by ROI.

**Comment by rickyars** [comment]
I've been trying to get in touch with the ROI authors to get a response. For SYMPHONY it's something they need to fix. They are misinterpreting the return codes, mostly likely because old vs. new version of the solver. They other problem is they will only return results if model finds an optimal solution. I suspect this is the issue you're having with `glpk`. 

I also roped in someone from COIN-OR who works on SYMPHONY to reach out and he says he hasn't been able to reach them either. Perhaps it would help if you also send an email? 

The problem is here:
https://r-forge.r-project.org/scm/viewvc.php/pkg/ROI.plugin.symphony/R/plugin.R?view=markup&revision=307&root=roi

In `the add_status_codes` (besides having the wrong codes) only optimal solutions set the `roi_code` to zero (see TM_OPTIMAL_SOLUTION_FOUND). Unless that value is zero, ROI returns only NA when asked for the solution. See `make_OP_solution` here:
https://r-forge.r-project.org/scm/viewvc.php/pkg/ROI/R/solution.R?view=markup&root=roi

**Comment by rickyars** [comment]
Just to confirm. You are seeing the same issue. They return the default `roi_code` when a feasible solution is found. The default code won't return a solution:
https://r-forge.r-project.org/scm/viewvc.php/pkg/ROI.plugin.glpk/R/plugin.R?view=markup&root=roi

I wonder why they made this decision. If it were me, I would just pass through the solution no matter what and let the user figure out what they wanted to do with it. Instead they just return NA whenever something other than an optimal solution is found.

**Comment by dirkschumacher** [comment]
Ah great, thanks! I will contact them.

**Comment by rickyars** [comment]
I was thinking about forking the ROI repo and putting it on GitHub.

**Comment by dirkschumacher** [comment]
@rickyars Maybe interesting to you. CBC can now be used with ompr:
https://github.com/dirkschumacher/rcbc
https://github.com/dirkschumacher/ROI.plugin.cbc

Still work in progress though

**Comment by rickyars** [comment]
This looks great! I'll give it a shot and let you know how it works, but probably not until after our big analysis is do. Thanks for all your efforts on this stuff and please let me know how I might be able to contribute. I'm a halfway decent R programmer.

**Comment by rickyars** [comment]
I got a not from the ROI folks:

> Hi Ricardo,
> thanks for reporting. We need those status codes for status message canonicalization. I will update the respective plugin accordingly. We will upload new versions of ROI and plugins over the next few days. 
> 
> However, you should be able to extract the Rsymphony solution from the ROI solution object anyway using:
> solution( x, type = "msg")
> where x is the ROI solution object.
> 
> I am very sorry for the late response. 
> 
> Best,
> Stefan

**Comment by rickyars** [comment]
Hi Dirk,

I was trying to use the ROI::solution method but I don't think ompr returns an ROI solution object. Is this true? Or am I doing something wrong?

**Comment by rickyars** [comment]
I think I figured it out. On line 124 of `with-roi.R` in the `ompr.roi` package you call `ROI::solution` on the "result". For me to try their suggestion, I need with_ROI to return the output from `ROI::ROI_solve` so I can call `ROI::solution` on my own.

**Comment by dirkschumacher** [comment]
I think we need to add this to ompr.roi. This is the interface to ROI.

**Comment by rickyars** [comment]
One last comment. It looks like the ROI folks have fixed the issue. It will now return a solution regardless of the solver status message. The change was made on May 11, 2017 to solution.R (revision 339).. 

https://r-forge.r-project.org/scm/viewvc.php/pkg/ROI/R/solution.R?root=roi&view=log

I think we should be able to get our solutions out once this gets pushed out to CRAN.

**Comment by dirkschumacher** [comment]
For now you can also clone ompr.roi and change the code for yourself

**Comment by dirkschumacher** [comment]
@rickyars Also, you can always change the gap ratio, so that a solution is marked as optimal even with a large gap to the LP value. That would be a quick fix. But I will look into this once the new version of ROI is on CRAN.

Also, I updated the coin-or brew repository to have the latest solver versions and enabled parallel support for CBC: https://github.com/coin-or-tools/homebrew-coinor/issues/45

**Comment by rickyars** [comment]
@dirkschumacher 

Doesn't look like the `ROI` folks have fixed their code yet. We're now returning the correct status message but I can't return the solution using `solution()`. Instead I can get it direction from the object; e.g., `x$solution`. Is there any way I can get the solution return from `ROI` from `ompr`?

E.g., in `with-roi.R` you asked for the code directly but not the solution:
```
status <- if (result$status$code == 0) "optimal" else "infeasible"
solution <- ROI::solution(result)
```
Can we also return the solution the same way: `result$solution`? From my tests, this should work. Either that or just give me the `result` object.

**Comment by rickyars** [comment]
I guess it's not that easy. We also need to modify `get_solution()` too.

**Comment by dirkschumacher** [comment]
Can you post an issue with what you would like to see/have?

**Comment by rickyars** [comment]
See issue #156
