### ISSUE TITLE
model api should return sparse matrices/arrays

### ISSUE THREAD

**Issue by dirkschumacher** [dirkschumacher/ompr#147]
Ideally all model api function should return sparse matrices/arrays. 
Number 1 priority is `extract_constraints`, otherwise larger models will be impossible to solve.

**Comment by dirkschumacher** [comment]
Some observations (note to myself):

* `objective_function` returns an element called `solution` that contains the sparse vector. Why is this called `solution`and who is responsible for choosing such a bad name?
* It seems that rbinding all constraints to a sparse matrix can be made a faster

**Comment by rickyars** [comment]
another thing i've noticed is that these solution objects can get very big. i'm running thousands of small optimizations and the result can be in the GB. i've ended up discarding the solution object and just keeping the info i want. this has greatly reduced my memory requirement.

**Comment by dirkschumacher** [comment]
Note to self: I feel like, I should just push this update out. Not ideally implemented, but it's something ;)

**Comment by dirkschumacher** [comment]
The reason I believe those solution objects become so big is that they have a copy of the model with them.
