### ISSUE TITLE
Error in ast[[i]] : subscript out of bounds 

### ISSUE THREAD

**Issue by JeffreyASmith** [dirkschumacher/ompr#148]
When I attempt to solve:

library(dplyr)
library(ROI)
library(ROI.plugin.glpk)
library(ompr)
library(ompr.roi)

n <- 70
k <- 17
d <-
  gtools::permute(
    c(
      rep(1:k, floor(n / k)),
      sample.int(
        n = k,
        size = n - floor(n / k) * k,
        replace = FALSE
      )
    ))
    M <- matrix(d, nrow = n)
    sM <-
      scale(M, center = colMeans(M), scale = apply(M, 2, sd, na.rm = TRUE))

    result <- MIPModel() %>%
      add_variable(Theta[r, l], type = "binary", r = 1:n, l = 1:k) %>%
      add_constraint(sum_expr(Theta[r, l], l = 1:k) == 1, r = 1:n) %>%
      add_variable(X[r], type = "continuous", r = 1:n) %>%
      add_constraint(sum_expr(l * Theta[r, l], l = 1:k) == X[r], r = 1:n) %>%
      add_variable(Xsum, type = "continuous") %>%
      add_constraint(sum_expr(X[r], r = 1:n) == Xsum) %>%
      add_variable(Xd[r], type = "continuous", r = 1:n) %>%
      add_constraint(sum_expr(X[r] - (1 / n) * Xsum) == Xd[r], r = 1:n) %>%
      add_variable(V, type = "continuous") %>%
      add_constraint(sum_expr(sM[r, c] * Xd[r], r = 1:n) >= V, c = 1:ncol(sM)) %>%
      add_constraint(sum_expr(-sM[r, c] * Xd[r], r = 1:n) >= V, c = 1:ncol(sM)) %>%
      set_objective(V, sense = "min") %>%
      solve_model(with_ROI(solver = "glpk", verbose = TRUE))

using ompr with the glpk or symphony solvers, i receive the error:
Error in ast[[i]] : subscript out of bounds

Trace produces:

22. on_element(push, inplace_update_ast, get_ast_value, element) 
21. ast_walker(base_ast, on_element) 
20. try_eval_exp_rec(ast, calling_env) 
19. bind_variables(model, expression, envir) 
18. normalize_expression(model, lhs_ast, envir) 
17. add_constraint_internal(calling_env) 
16. FUN(newX[, i], ...) 
15. apply(var_combinations, 1, function(row) {
    calling_env <- as.environment(as.list(row))
    parent.env(calling_env) <- parent_env
    constraint <- add_constraint_internal(calling_env) ... 
14. add_constraint_.optimization_model(.model, lazyeval::as.lazy(substitute(.constraint_expr), 
    parent.frame()), .dots = lazyeval::lazy_dots(...), .show_progress_bar = .show_progress_bar) 
13. add_constraint_(.model, lazyeval::as.lazy(substitute(.constraint_expr), 
    parent.frame()), .dots = lazyeval::lazy_dots(...), .show_progress_bar = .show_progress_bar) 
12. add_constraint(., sum_expr(X[r] - (1/n) * Xsum) == Xd[r], r = 1:n) 
11. function_list[[i]](value) 
10. freduce(value, `_function_list`) 
9. `_fseq`(`_lhs`) 
8. eval(expr, envir, enclos) 
7. eval(quote(`_fseq`(`_lhs`)), env, env) 
6. withVisible(eval(quote(`_fseq`(`_lhs`)), env, env)) 
5. MIPModel() %>% add_variable(Theta[r, l], type = "binary", r = 1:n, 
    l = 1:k) %>% add_constraint(sum_expr(Theta[r, l], l = 1:k) == 
    1, r = 1:n) %>% add_variable(X[r], type = "continuous", r = 1:n) %>% 
    add_constraint(sum_expr(l * Theta[r, l], l = 1:k) == X[r],  ... at sample.R#25
4. eval(substitute(expr), envir, enclos) 
3. evalq({
    library(dplyr)
    library(ROI)
    library(ROI.plugin.glpk) ... at sample.R#1
2. env$fun() 
1. debugSource("D:/DOE/sample.R") 

For the life of me I cannot see the error I am making to produce this.

**Comment by dirkschumacher** [comment]
Thanks!

This is the problem
```
add_constraint(sum_expr(X[r] - (1 / n) * Xsum) == Xd[r], r = 1:n) %>%
```

There is a `sum_expr` without any quantifiers. I believe this is equivalent to
```
add_constraint(X[r] - (1 / n) * Xsum == Xd[r], r = 1:n) %>%
```
I added an issue to improve the error message in a future release (#151)

**Comment by JeffreyASmith** [comment]
Dick.

 

Thank you.  That solved my problem. 

 

I very much appreciate your help.

 

Jeffrey
