### ISSUE TITLE
get_solution should always return a solution

### ISSUE THREAD

**Issue by rickyars** [dirkschumacher/ompr#156]
Currently get_solution will not return a solution if the status code is not "optimal". 
```
if (solution$status != "optimal") {
        result_df <- result_df[FALSE, ]
}
```
In my opinion, a solution should always be returned regardless of the solver status code. Since I can ask for the solver status code, I can disregard the solution in my code if necessary. The reason this makes a difference is that sometimes I want the solution even though it's not optimal. E.g., I could either terminate the solver early, before it converges by using a time limit. Or I can ask the solver for the first feasible solution. In both cases these are not "optimal" and nothing is returned. Let the user decide what to do with the output of the solver.

I should note that there is currently an issue in `ROI` where the solver only returns optimal solutions using the `solution()` method. However, you can get the solver output by accessing the solution directly. E.g., `x$solution`. This is a change that would need to be made in `ompr.roi`.

**Comment by dirkschumacher** [comment]
Yes this change should be reflected in the next version of `ompr.roi`. I will try to draft something when I have time.
