### ISSUE TITLE
All equal constraint

### ISSUE THREAD

**Issue by instantkaffee** [dirkschumacher/ompr#158]
Is there a way to add the constraint, that the variable vector elements are all equal?

**Comment by dirkschumacher** [comment]
Can you give me an example? Do you mean `add_constraint(x == 1)`?

**Comment by instantkaffee** [comment]
Thx, I already solved it using the pattern:
  `add_constraint(x[i] == x[j], i= 1:(problem_size-1), j= 2:problem_size)`
