### ISSUE TITLE
Symphony not returning feasible solution

### ISSUE THREAD

**Issue by ralphasher** [dirkschumacher/ompr#163]
I'm using OMPR to call Symphony and have a weird circumstance. I put the Symphony solver arguments to be verbose, so I know that the problem has feasible solutions and solves to optimality because the R console shows it. Yet when I use ompr::get_solution, the solution object says that the problem is infeasible. Any idea why this may be happening?

**Comment by dirkschumacher** [comment]
Do you have a reproducible example?

**Comment by ralphasher** [comment]
Will do.  Need to clean it up and anonymize data.

Ralph

________________________________

**Comment by dirkschumacher** [comment]
Cool. That helps. I might know what the problem is. Did symphony say it is optimal or was it just a feasible solution? Because in previous ROI versions, only the optimal solution was returned.

**Comment by ralphasher** [comment]
I tested solving the same model, with and without additional arguments passed to Symphony.  Without arguments, it solves and the solution object has a optimal status.  With arguments, I see it solves on the console verbosity and the solution object status is infeasible!

This is a problem because I want to be able to add gap limit and time limit arguments, however it makes the solution object infeasible, when in fact I see the solvers progress and I know that Symphony solves to within my defined gap limit!

**Comment by dirkschumacher** [comment]
The recent changes address that issue. As for right now, the solver status will be "success" for ROI based interfaces or "error". ROI also returns the "error" status code when a user time limit is reached. However there is now a function called `additional_solver_output(solution)` that returns solver specific status and messages that can be used to determine what actually happened.
