### ISSUE TITLE
MINLP still using ompr?

### ISSUE THREAD

**Issue by MelissaLe44** [dirkschumacher/ompr#164]
Hello,
I would like to use ompr, but my objective function is non-linear, having a component like a/a+b. 
First question: is there a "trick" to transform this component into a linear one, so that I can use one of the solvers in ompr (e.g glpk). (I already used a trick for the absolute value, creating two constraints)
If not, would you recommend me any R solver (package/function) to solve my MINLP problem?

Thanks a lot for your answers.
FYI, please find attached my MINLP problem.
[revengineeringMIP.docx](https://github.com/dirkschumacher/ompr/files/1337232/revengineeringMIP.docx)

Regards,
Mélissa

**Comment by dirkschumacher** [comment]
I think we discussed this on twitter. 

For the rest:
ompr does not support non linear programming. See the package ROI or the solvers listed at neos-server (https://neos-guide.org/content/mixed-integer-nonlinear-programming)

**Comment by MelissaLe44** [comment]
you are right thanks a lot, my next step is then to use the package rneos on my MINLP problem.
Thanks for your support.
Best
Mélissa

**Comment by Yogitha785** [comment]
Hello Melissa,
I am trying to solve a similar problem where my objective function is non-linear and i have some binary constraints. It would be very helpful if you can let me know any package that worked for you.

Thank you
Yogitha
