### ISSUE TITLE
how to get the gap

### ISSUE THREAD

**Issue by rickyars** [dirkschumacher/ompr#173]
sorry that this isn't really an issue, but i'm wondering how i can get some info back from the solver. i've been poking around ompr.roi and roi and haven't quite seemed to find the answer. basically i want to know the optimality gap. well, i don't, but my boss does. when i run symphony in verbose mode i get
````
Gap Percentage:              6.667
````
not sure how to capture that, but maybe it's already being saved and i don't know about it.

**Comment by dirkschumacher** [comment]
I don't know if you can get the GAP from `Rsymphony` through `ROI` - I doubt it. What you could do is capture the STDOUT output, write it to a log file and the parse it later. `Rscript solve.R > log.txt` Just an idea.

**Comment by rickyars** [comment]
Thanks for the suggestion. Unfortunately I use a foreach loop to run 200k optimizations in parallel.
