### ISSUE TITLE
contain is not part of model, or object not found

### ISSUE THREAD

**Issue by alekasandarnedanov** [dirkschumacher/ompr#174]
Hi Dirk,

I'm not so good in mixed linear programming but your OMPR package is really amazing and 
helps me a lot in understanding of this area! I'm a very close to finish my doctoral thesis but 
before that I need to construct a four very similar MILP model to check flexibility (Cook and Zhu, 2007)
and to verify importance of my input and output variables for DEA model (Toloo et al., 2014).
I'm playing with their data because I want to replicate results and learn something about these methods.

... but I have a problem with importing both of them in R and don't have any new idea how to fix it.

One version of Cook model (see text document in attachment) gives me the report:
"_Error in check_for_unknown_vars_impl(model, the_ast): The expression contains a variable that is not part of the model._"
and when I try to add index [j] for all variables in objection function report then says:
"_Error: The objective is probably non-linear. Currently, only linear functions are supported._"

I'm confused a little bit because it's a linear programming issue. 

Similar issues I have with Toolo model (also in attachment) where two proposed models cannot find binar variable
Report is: "_Error in set_bounds_.optimization_model(.model, lazyeval::as.lazy(substitute(.variable), : object 'bx' not found_:

I'm looking at them and try everything but I cannot find a syntax mistake(s). Do you have any suggestions on how to solve this? I have also attached you an image of two Cook model with restrictions on `variables.

Thanks a lot,
Aleksandar

[MILP models.txt](https://github.com/dirkschumacher/ompr/files/1643060/MILP.models.txt)
![cook zhu individual and aggregate approach](https://user-images.githubusercontent.com/35565314/35101812-27ed6994-fc61-11e7-83f3-0d9b2d5d444d.jpg)

**Comment by dirkschumacher** [comment]
E.g. `u.var[r] * y.var[r]` is a non-linear term. Are you sure both are model variables?
