### ISSUE TITLE
Running time

### ISSUE THREAD

**Issue by lalitathakali** [dirkschumacher/ompr#175]
Hi,

I am trying to solve a simple linear integer program using ompr. I have a total of 1497 intersection locations and I'm trying to optimize safety benefit by implementing treatment at specific sites with a limited budget. I have been trying to solve this problem and it is taking a very long time, more than a day. Do you think this is a normal time duration? Is there a way to reduce the running time. I would appreciate your feedback. Thanks.

```R
  n<- 1497 # no of intersections
  m<- 3 # no of treatment type
  b<- 5000000 # budget 
      
  model <- MIPModel() %>%
        # 1 iff (if and only if) i gets assigned to countermeasure j
        # Create x[i,j] variables for all combinations of i and j "where" i = 1:n and j = 1:m.
        add_variable(x[i, j], i= 1:n, j= 1:m, type = "binary") %>%
        
        # maximize the total safety benefit
        set_objective(sum_expr(p(i,j) * x[i,j], i= 1:n, j= 1:m), "max") %>%
        
        add_constraint(sum_expr(cost_var(j) * x[i,j], i= 1:n, j= 1:m)<= b) %>%
        # At most one countermeasure can be used for a given site
        add_constraint(sum_expr(x[i,j], j = 1:m)<= 1, i= 1:n) %>% 
        # only selective countermeasures can be implemented to given sites 
        add_constraint(x[i,j] <= y(i,j), i= 1:n, j= 1:m) 
```

**Comment by dirkschumacher** [comment]
There is a new backend `MILPModel` that is way faster than the old implementation. When I find some time I will push it to CRAN, but I have to make some changes first.

You can try it with the current `master` of this repository. Here are some docs: https://github.com/dirkschumacher/ompr/blob/master/vignettes/modelling-milp.Rmd
