### ISSUE TITLE
Concentration Constraint Setup Question

### ISSUE THREAD

**Issue by khsu15** [dirkschumacher/ompr#176]
Hi,
I'm fairly new to to linear programming, so apologies if this question has been asked before.  I'm trying maximize the total sum of account balances, but at the same time, I want to setup a constraint that limits the concentration of a type of account.  I can get the constraint to limit the type based on the original total pool (commented out below), but I cannot get it to be limited based on the final, maximized pool amount.  Is this possible within the ompr framework?

```R
MIPModel() %>%
  add_variable(x[i],i=1:n,type='binary') %>%
  add_variable(y[j],j=1:n,type='binary') %>%
  set_objective(sum_expr(pool$account_balances[i] * x[i],i=1:n),'max') %>%
  ##Wt Avg Score
  add_constraint(sum_expr(pool$score[i] * x[i] * pool$account_balances[i] - x[i] * max_score * pool$account_balances[i],i=1:n) <=0) %>%
  ##Concentrations of a certain type - limit to 8% of total pool
  #add_constraint(sum_expr(pool$account_balances[i] * x[i] , i=1:n,pool$type[i]=="A" ) <= 0.08 * sum(pool$account_balances))  ##works, but isn't dynamic with the resulting pool
  add_constraint(sum_expr(pool$account_balances[i] * x[i] - 0.08* y[j] * pool$account_balances[j], i=1:n, j=1:n,pool$type[i]=="A" ) <=0 )
```

**Comment by dirkschumacher** [comment]
Did you solve it?

**Comment by khsu15** [comment]
Yes, the solution was to create another column containing the balance if it is of type 'A' and use that in the constraint

**Comment by dirkschumacher** [comment]
👍
