### ISSUE TITLE
Error in check_for_unknown_vars_impl(model, the_ast) :   The expression contains a variable that is not part of the model.

### ISSUE THREAD

**Issue by abhaylidbe** [dirkschumacher/ompr#180]
Hi, Before posing my question, let me first thank you for great efforts. I have been on lookout for such a package for a long time; the one that integrates mathematical modeling with R and at the same time allows to script the model closer to its mathematical form. I'm new to this package and hence the question.

The attached file has two data frames with the required data, followed by few other steps to enable using the data in the MIP model. The model yields error "The expression contains a variable that is not part of the model."  

[hfsdcarp.txt](https://github.com/dirkschumacher/ompr/files/1839448/hfsdcarp.txt)

**Comment by dirkschumacher** [comment]
Happy to help here 👍 , but it would be nice if you could try to narrow down the problem and create a minimal reproducible example. This makes it easier for me to debug. More info here: http://reprex.tidyverse.org/articles/reprex-dos-and-donts.html

**Comment by ShuchitaShukla** [comment]
@abhaylidbe 
Hi , the error in my code is similar to yours. can you please help if you have already worked on it.
library(Rglpk)
library(magrittr)
library(dplyr)
library(ROI)
library(ROI.plugin.glpk)
library(ompr)
library(ompr.roi)


data<-read.csv('input.csv',header=TRUE,sep=",")
Inv_Stock<-read.csv('INV_DATA.csv',header = TRUE,sep = ",")
#Inv_Stock<- sapply(Inv_Stock,as.matrix)
qty_req<- data[,5]
qty_req<- sapply(qty_req,as.double)

Revenueperunit<-data[,4]
Revenueperunit<-sapply(Revenueperunit,as.double)

Raw_mat<-data[,-c(1,2,3,4,5)]
set.seed(0)
n<-172

model <- MIPModel() %>%
  add_variable(Qtysold[i],i=1:n,type = "integer" ,lb=0 ) %>%
  add_variable(Total_mat[i,j],i=1:n,j=1:68, type = "continuous", lb = 0) %>%
  set_objective(sum_expr(Qtysold[i]*Revenueperunit[i],i=1:n), "max")%>%
  add_constraint(Qtysold[i] <= qty_req[i], i = 1:n)%>%
  add_constraint(Qtysold[i]*Raw_mat[i,j]==Total_mat[i,j],i=1:n,j=1:68)%>%
  add_constraint(colSums(Total_mat[i,j],i=1:n)<=Inv_Stock[j],j=1:68)
  result <- solve_model(model, with_ROI(solver = "glpk"))  

im facing difficulty in adding the last constraint.
Thanks in advance.

**Comment by devu123** [comment]
@ShuchitaShukla
You won't be able to use colSums in ompr, try sum_expr instead.
