### ISSUE TITLE
access solver information

### ISSUE THREAD

**Issue by dirkdegel** [dirkschumacher/ompr#187]
Hi Dirk,
I was wondering if it is possible with the ompr interface to access solver information, e.g. the current best (feasible) solution and objective value and after how many iteration/time this solution was found and so on. Thanks a lot in advance! This a really great package and incredible useful! Thanks a lot!

**Comment by rickyars** [comment]
Maybe there's a better way, but what I do is convert the my `ompr` model to an `roi` model and then solve:
```
    roi.model <- as_ROI_model(model)
    roi.result <- ROI::ROI_solve(roi.model, "symphony", verbosity = -2, time_limit = time.limit)
 ```
Then you can get the status, objective and solution:
```
    status <- roi.result$status$msg$message
    obj.value <- roi.result$objval
    roi.result$solution
```

**Comment by dirkschumacher** [comment]
@rickyars outlined one practical option - thanks👍. I recently added an interface for duals, but there is no general way to capture arbitrary solver output. Probably a good idea though. What information is interesting?

**Comment by dirkdegel** [comment]
Thanks a lot @rickyars for the hints. I need to have a closer look at the ROI package. @dirkschumacher The information which is most interesting for me is to observe the solution process in the solver, in particular to get a list of all feasible (suboptimal) solutions, the objective value, the optimality gap, and solver time to this solutions. In general, I think it would be great to access every information that a particular solver is able to provide (which depends of course on the solver). I'm particularly interested in CBC and Gurobi. I know that Gurobi recently provided an R interface, but I can't find much information about it and as far as I know there is no algebraic modelling capability like in OMPR.

**Comment by rickyars** [comment]
@dirkdegel This has actually been a source of frustration for me as well. You can run the solvers with varying levels of verbosity. But I don't think it's possible to capture that information. I've tried `cat` and other methods for redirecting the output, but it doesn't seem to work. I wonder if it's because the solvers are external to R. Regardless, this isn't an ideal solution since I tend to run many solvers in a parallel foreach loop because I need to do 200k of them. 200k logs takes a long time to post-process (mostly reading in that many files) and then Windows has problems deleting them all.

I wish there were a way to get some of that information. Perhaps we need to make requests to the API authors to give us things like the gap and time to solve. I would love more diagnostic information.

**Comment by dirkschumacher** [comment]
Or we think about taking a look at the solver packages in R and see, if we can rewrite/patch them. I am not even sure this functionaly is offered in all the lower level bindings to the solvers.

@rickyars what solvers to you use?

**Comment by rickyars** [comment]
I use Symphony but I would like to switch to CBC. My company does have CPLEX but it's tied to GAMS. So I don't think I can use it with R. That said, I would lover to get more info out of the solvers.

**Comment by dirkschumacher** [comment]
I wonder how such an interface could look like: simply a named list with arbitrary, solver dependet information?

**Comment by rickyars** [comment]
Isn't that sorta how we get some of the information out now?

**Comment by dirkschumacher** [comment]
Well, yes, if you convert it to a ROI model. But there is no interface with `ompr`.

**Comment by rickyars** [comment]
In my case, converting to ROI model is adding another 30 seconds of runtime. I'm doing 200k optimizations. So that's a lot of extra time!  Maybe it's time I look at the ROI code again.

**Comment by dirkschumacher** [comment]
Too bad you can't test the `MILPModel`

**Comment by rickyars** [comment]
Okay - I'll give it a shot. Gonna use docker and just build my own environment.

**Comment by sbmack** [comment]
> I recently added an interface for duals, but there is no general way to capture arbitrary solver output. Probably a good idea though. What information is interesting?

FYI, Gurobi has a save last n solutions option.  So for example if you are solving a MIP problem, you can tell Gurobi to maintain the last 5 feasible solutions.  Then the end-user can evaluate all 5.  And if they want, they can apply some subjective criteria not explicitly embedded in the formulation to select the "best" solution from the 5.

**Comment by dirkschumacher** [comment]
You can now use `additional_solver_output` to access whatever `ROI` returns as additional, solver specific information. What will be made available is determined by the ROI plugins and the solver interface package.
