### ISSUE TITLE
Error in acc[[key]] : no such index at level 1

### ISSUE THREAD

**Issue by abhaykumar14** [dirkschumacher/ompr#189]
Hi, I am trying to run the model. However it shows the error "Error in acc[[key]] : no such index at level 1".
64 Bit Laptop, R 3.4.1
Its the model posted at below link

(https://dirkschumacher.github.io/ompr/articles/problem-warehouse-location.html#feedback)

Regards
Abhay

**Comment by dirkschumacher** [comment]
Strange, works for me. Where exactly does this error happen?

**Comment by abhaykumar14** [comment]
Its happens at following place
result <- solve_model(model, with_ROI(solver = "glpk", verbose = TRUE))

**Comment by dirkschumacher** [comment]
If you attach code, please paste it directly in here using three backticks. See here: https://help.github.com/articles/creating-and-highlighting-code-blocks/
