### ISSUE TITLE
fail gracefully

### ISSUE THREAD

**Issue by rickyars** [dirkschumacher/ompr#195]
I'm running a very large number of small optimizations in a loop. I have a problem where the solver will sometimes crash. I accept that this will happen. However, this also causes R to crash. I would like to wrap the call to `solve_model` in a `tryCatch` and continue even when it fails. Currently that doesn't seem to work. Is there another way to stop R from crashing when the solver throws and error? 

Here's the error I get from the CBC solver:
```
R: CoinIndexedVector.cpp:326: void CoinIndexedVector::checkClear(): Assertion `!elements_[i]' failed.
```

**Comment by dirkschumacher** [comment]
Hey @rickyars thanks. I will look into this once I have more time. 

Just so you know that I do not ignore your contributions :): I am currently not able to devote time to OS work due to reasons I do not want to disclose publicly. Hopefully I will be back in the coming weeks.

**Comment by dirkschumacher** [comment]
You can use `purrr`'s `safely` or `base`'s `try`. If you session gets killed by a segfault or something, you could use `callr` to solve the model in a different process.
