### ISSUE TITLE
Error related to MIPModel

### ISSUE THREAD

**Issue by m-c-1-2** [dirkschumacher/ompr#197]
Hi, I am new to using the ompr package and need some help. 
I am getting the following error message.
"Error in check_for_unknown_vars_impl(model, the_ast) : 
  The expression contains a variable that is not part of the model."

Below is my code.
```R
C = CapMat     # C is a 34x34 data table
model <- MIPModel() %>% 
  add_variable(X[i,k], i = 1:34 , k = 1:2 , type = "binary") %>% 
  add_variable(Y[i,j], i = 1:34 , j = 1:34 , type = "binary") %>% 
  set_objective(sum_expr(Y[i,j] * C[i,j], i = 1:34, j = 1:34), sense = "max") %>% 
  add_constraint(sum_expr(X[i,k] - X[j,k], i = 1:34,j=1:34, k = 1:2) <= sum_expr(1 - Y[i,j], i = 1:34, j = 1:34)) %>%
  add_constraint(sum_expr(X[i,k] + X[j,k], i = 1:34,j=1:34 k = 1:2) <= sum_expr(1 + Y[i,j], i = 1:34, j = 1:34)) %>%
  add_constraint(sum_expr(X[i,k], k = 1:2) == 1) %>%
  get_solution(X[i,k])
```

**Comment by dirkschumacher** [comment]
Happy to help. Can you please try to further reduce the code and create a minimal reproducible example? Try reducing the number of variables and constraints.

**Comment by rickyars** [comment]
@m-c-1-2 `C` can't be a `data.table`. Convert it to a `matrix` or `data.frame` and it should work. That said, I'm getting a similar error for the 3rd constraint that I can't figure out - and I need to work other stuff now.

You also have a missing comma in the 2nd constraint.

**Comment by rickyars** [comment]
@m-c-1-2 I've updated my previous comment. Your code should work now with these changes.

**Comment by dirkschumacher** [comment]
Thanks @rickyars 👍👍👍
