### ISSUE TITLE
Error in get_solution() in case there is only one variable

### ISSUE THREAD

**Issue by saurav2608** [dirkschumacher/ompr#198]
library(tidyverse)
#> -- Attaching packages ---------- tidyverse 1.2.1 --
#> v ggplot2 2.2.1     v purrr   0.2.4
#> v tibble  1.4.2     v dplyr   0.7.4
#> v tidyr   0.8.0     v stringr 1.3.0
#> v readr   1.1.1     v forcats 0.3.0
#> -- Conflicts ------------- tidyverse_conflicts() --
#> x dplyr::filter() masks stats::filter()
#> x dplyr::lag()    masks stats::lag()
library(ompr)
library(ompr.roi)
library(ROI.plugin.glpk)
n <- 1; W <- 2
v <- runif(n);w <- runif(n)
model <- MIPModel() %>% 
  add_variable(x[i], i = 1:n, type = "binary") %>% 
  set_objective(sum_expr(v[i] * x[i], i = 1:n)) %>% 
  add_constraint(sum_expr(w[i] * x[i], i = 1:n) <= W)
result <- solve_model(model, with_ROI(solver = "glpk", verbose = FALSE))
solution <- get_solution(result, x[i])
#> Warning in seq_len(ncol(var_index)): first element used of 'length.out'
#> argument
#> Error in seq_len(ncol(var_index)): argument must be coercible to non-negative integer

**Comment by dirkschumacher** [comment]
Ah interesting. Thanks a lot!

**Comment by dirkschumacher** [comment]
Seems to be a bug in https://github.com/dirkschumacher/ompr.roi/issues/19

**Comment by dirkschumacher** [comment]
Thanks a lot. `drop = TRUE` striked again.

**Comment by saurav2608** [comment]
Oh you are quick. I was preparing a PR. I started using your package recently. It is very good.

**Comment by dirkschumacher** [comment]
Thanks for reporting the bug. I am slowly restarting my OS work again after a temoral leave, so I thought this is a good start ;)
