### ISSUE TITLE
cannot set objective functions

### ISSUE THREAD

**Issue by Veranda2018** [dirkschumacher/ompr#206]
Hi there,

For some reason I cannot set an objective function for my model. Here is the code:

```R
# Simple case first
W = matrix(c(0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0), nrow = 6);
m = c(1,1,1,1,1,1)
T = length(m);
rho = 0.5

##################################################
# Calculating some constants 
a = rho/(1-rho) * sum(m)
B = a*W + m %*% t(m)
diag(B) <- 0

Model <- MILPModel() %>%
  add_variable(v[1:T], type = "binary") %>%
  add_variable(u[i,j], i = 1:T, j = i:T, lb = 0) %>%
  set_objective(2 *sum_expr(B[i, j] * u[i,j], i = 1 : T-1, j = i + 1 : T) -
                  sum_expr(B[i,j] * v[j], i = 1 : T-1, j = i + 1 : T), "min") %>%
  add_constraint(u[i,j] <= v[i], i = 1 : T-1, j = i + 1 : T) %>%
  add_constraint(u[i,j] <= v[j], i = 1 : T-1, j = i + 1 : T) 
######################################################
```

But it gives me the following error at set_objective line:

Error in eval(x$expr, x$env, emptyenv()) : object 'i' not found

Can you please help? I don't understand why "i" is not found when I actually define it to be from 1 to T-1.

Thanks,
Vika

**Comment by dirkschumacher** [comment]
The error comes from this part `sum_expr(1, i = 1 : T-1, j = i + 1 : T)`. You cannot reuse the `i` index in other index generators. The semantic currently is that `sum_expr` generates all combinations of indexes and then builds the variables accordingly.  Apart from that, `i + 1:T` would generate index values that are out of bounds.

There are two options: 
1) Either you use a filter expression to further reduce the sum
`sum_expr(..., i = 1:n, j = 1:n, j > i)`
2) You build the vector of indexes yourself and do this (only with MILPModel)
```R
MILPModel() %>% 
  add_variable(x[i, i], i = 1:10) %>% 
  set_objective(x[c(1, 2, 3, 4), c(2, 3, 4, 5)]) %>% # this generates x[1, 2], x[2, 3], x[3, 4], x[4, 5]
  ompr::objective_function()
```

If you use the `MILPModel` backend, `B[i,j]` currently won't work, as i and j will be long vectors. You need to define a function for it. See the TSP article for a example: https://dirkschumacher.github.io/ompr/articles/milp-problem-tsp.html

**Comment by Veranda2018** [comment]
It worked perfectly!
Thank you so much for your help.

V

**Comment by dirkschumacher** [comment]
Glad I could help!
