### ISSUE TITLE
Warehouse Location Problem on a 1000Customer*80Branch set

### ISSUE THREAD

**Issue by RajeevBajj** [dirkschumacher/ompr#209]
Hi, 
I am trying to following problem:
We have total of 1000 customer and total 80 branches that currently supply goods to these customer. We want close 10 branches. For closing these 10 branches we want to identify which ones to close. 
We have got demand for each customer, distance + speed to travel from branch to customer + cost incurred to serve a customer from all the 80 branches. We need to do map a customer to a particular branch. 
Constraints:
1. A customer cannot be served by more than 1 branch. A
2. Distance traveled should not be greater than 24 hour

We know the distance and cost to travel to each customer from each of these branches. First a customer needs to be assigned a branch and then identify the branch to be closed minimizing the total distance traveled and eventually the cost. We are using ware house location algorithm for it of MIP.

The challenge that we are facing is our code is working perfectly fine if we have less than 300 customers. As soon as we increase number of customer beyond 300 to the code. We are getting stack over flow error. We tried running the same code on a dedicated R - server with 32 gig Ram. Still running into the same problem. Please suggest some solution. 

Below is the code used:
time_start<- Sys.time()
sch_data=read.csv("Scenario_Optimzer_data.csv",header = T)
sch_data=subset(sch_data,sch_data$Customer.Cluster<=300)
sch_data$id=seq(1,nrow(sch_data))
sch_data$time=sch_data$DistanceMiles/sch_data$Avg.Speed
sch_data1=as.data.frame(sch_data[,c(1,2,3,8,9,10)])

setnames(sch_data1,old=c('Branch.ID','Customer.Cluster','number.of.Fairs',
                         'Avg.Wage','Avg.Speed','DistanceMiles'),
         new=c('Branch','Customer','Fairs','Wage','Speed','DistanceMiles'))

sch_data2=as.data.frame(sch_data1[,c(1,2,3)])
sch_data3=as.data.frame(sch_data1[,c(1,2,4)])
sch_data4=as.data.frame(sch_data1[,c(1,2,5)])
sch_data5=as.data.frame(sch_data1[,c(1,2,6)])

sch_data_d=as.data.frame(cast(sch_data2,Customer~Branch))
sch_data_w=as.data.frame(cast(sch_data3,Customer~Branch))
sch_data_s=as.data.frame(cast(sch_data4,Customer~Branch))
sch_data_di=as.data.frame(cast(sch_data5,Customer~Branch))

customer_locations <- as.data.frame(unique(sch_data1$Customer))
colnames(customer_locations)[1]="customer"
num_cus=nrow(customer_locations)
branch_location=as.data.frame(unique(sch_data1$Branch))
colnames(branch_location)[1]="Branch"
num_branch=nrow(branch_location)

rm(sch_data1)
rm(sch_data2)
rm(sch_data3)
rm(sch_data4)
rm(sch_data5)

transportcost <- function(i, j) {
  demand <- sch_data_d[i,j+1]
  distance <- sch_data_di[i,j+1]
  speed <- sch_data_s[i,j+1]
  wage <- sch_data_w[i,j+1]
  (demand*distance*wage)/speed
}
transportcost(1,1)

travel <- function(i, j) {
  distance <- sch_data_di[i,j+1]
  speed <- sch_data_s[i,j+1]
  distance/speed
}
travel(1,1)

library(ROI.plugin.glpk)
library(ompr)
library(magrittr)
model <- MIPModel() %>%
  add_variable(x[i, j], i = 1:num_cus, j = 1:num_branch, type = "binary") %>%
  
  add_variable(y[j], j = 1:num_branch, type = "binary") %>%

  set_objective(sum_expr(transportcost(i, j) * x[i, j], i = 1:num_cus, j = 1:num_branch) + 
                  sum_expr(y[j], j = 1:num_branch), "min") %>%
  
  add_constraint(sum_expr(x[i, j], j = 1:num_branch) == 1, i = 1:num_cus) %>% 
  
  add_constraint(x[i,j] <= y[j], i = 1:num_cus, j = 1:num_branch) %>%
  
  add_constraint(sum_expr(x[i,j]*travel(i,j),i = 1:num_cus)<=24 , j = 1:num_branch) %>%
  
  add_constraint(sum_expr(y[j], j = 1:num_branch) <= 50)
  
model

result <- solve_model(model, with_ROI(solver = "glpk", verbose = TRUE))

matching <- result %>% 
  get_solution(x[i,j]) %>%
  filter(value > 0) %>%  
  select(i, j)

setnames(matching,old=c('i','j'),new=c('Cust_row','Branch_row'))
sch_data1=as.data.frame(sch_data[,c(1,2,3,8,9,10)])

setnames(sch_data1,old=c('Branch.ID','Customer.Cluster','number.of.Fairs',
                         'Avg.Wage','Avg.Speed','DistanceMiles'),
         new=c('Branch','customer','Fairs','Wage','Speed','DistanceMiles'))

customer_locations$Cust_row <- seq.int(nrow(customer_locations))
branch_location$Branch_row <- seq.int(nrow(branch_location))

sch_result <- left_join(matching,customer_locations,by='Cust_row')
sch_result1 <- left_join(sch_result,branch_location,by='Branch_row')
sch_result2 <- left_join(sch_result1,sch_data1, by=c('customer','Branch'))

sch_result2$cost <- (sch_result2$Fairs*sch_result2$Wage*sch_result2$DistanceMiles)/sch_result2$Speed
sch_result2$time <- sch_result2$DistanceMiles/sch_result2$Speed

branch_mapped <- as.data.frame(unique(sch_result2$Branch))
colnames(branch_mapped)[1] <- "Branch_map"
branch_mapped$allocated <- "T"

sch_result3 <- left_join(branch_location,branch_mapped,by=c("Branch"="Branch_map"))
sch_result4 <- sch_result3[is.na(sch_result3$allocated),]

sum(sch_result2$cost)/1000000
sum(as.numeric(sch_data$Total.Outbound.Cost))/1000000

length(unique(matching$Branch_row))

time_end<- Sys.time()

difftime(time_end, time_start,units = c("secs"))

**Comment by dirkschumacher** [comment]
There are some options:

- You could use the new `MILPModel` backend. It is a bit experimental, but it can be very fast.
- You can extract the matrix/coefficients out of the model, store it to disk and pass it directly to your solver in a different session (if total RAM consumption is the problem)
- If GLPK is the problem, try using a different solver or try to reduce the problem. Sometimes, you can preprocess the model and maybe rule out certain combinations of clients/warehouse. This reduces the size of the problem. Also try the `presove=TRUE` option for `GLPK`
