### ISSUE TITLE
Add terms to the objective in separate calls

### ISSUE THREAD

**Issue by innuo** [dirkschumacher/ompr#213]
It would be nice to have the ability to construct the objective in several steps. This might enable modular design of the optimization code.

For example, I would like to do something like the following. The add_to_objective() function on line 5 will add the coefficient 2 to the existing coefficient of y (which would be zero after the set_objective call).

 
```
result <- MIPModel() %>%
  add_variable(x, type = "integer") %>%
  add_variable(y, type = "continuous", lb = 0) %>%
  set_objective(x, "max") %>%
  add_to_objective(2 * y) %>%
  add_constraint(x + y <= 11.25) %>%
  solve_model(with_ROI(solver = "glpk")) 
```

If this is hard to implement, is there another way to accomplish this using the existing capabilities?

**Comment by hugolarzabal** [comment]
Hello,

I guess that you need that function in order to declare a very long and/or complicated objective function.

One way to do it would be to add intermediary variables like that:

```
add_variable( obj1, type = "continuous") %>%
add_variable( obj2, type = "continuous") %>%
add_constraint( obj1 = x) %>%
add_constraint(obj2 = 2*y) %>%
set_objective(obj1 + obj2, "max")
```
In this example, it doesn't make much sense but it can be usefull if obj1 and obj2 are complicated expressions.

Also, you can use the %<>% pipe to declare the model part by part.
`result %<>%` is equivalent to `result <- result %>%
`

**Comment by dirkschumacher** [comment]
I like the idea of adding multiple objective functions, but at the moment the suggestion of @hugolarzabal is probably the best option. 
You can also use `rlang` to construct the formula programatically before passing it to `set_objective`. Although is might a bit more involved.

**Comment by gaiazaff** [comment]
I am trying to do something similar, but @hugolarzabal's suggestion doesn't work for me.

```
MIPModel() %>%
  add_variable(x, type = "integer") %>%
  add_variable(y, type = "continuous", lb = 0) %>%
  add_variable( obj1, type = "continuous") %>%
  add_variable( obj2, type = "continuous") %>%
  add_constraint(x + y <= 11.25) %>%
  add_constraint( obj1 = x) %>%
  add_constraint(obj2 = 2*y) %>%
  set_objective(obj1 + obj2, "max")
```

Gives the error:
Error in add_constraint_.optimization_model(.model, lazyeval::as.lazy(substitute(.constraint_expr),  : 
  argument "constraint_ast" is missing, with no default

Am I missing something?

**Comment by sbmack** [comment]
Well an obvious syntax error is:

```
  add_constraint( obj1 = x) %>%
  add_constraint(obj2 = 2*y) %>%
```
Since the equality is a comparison, not an assignment.  Replace `=` with `==`  in those lines first and see what happens.

```
  add_constraint( obj1 == x) %>%
  add_constraint(obj2 == 2*y) %>%
```

**Comment by gaiazaff** [comment]
I see, that was indeed an obvious thing to try. Thanks!
