### ISSUE TITLE
Wrong coefficients associated with MILP constraint

### ISSUE THREAD

**Issue by moaarab** [dirkschumacher/ompr#214]
Hi,

When implementing a constraint using the MILP backend the coefficients do not seem to be correct. 
I will try to illustrate the problem:
When the code below is run 
```R
library(ompr)
library(dplyr)

n_truck <- 4
n_warehouse <- 2
equalto <- 15:18


coefficients = matrix(
c(0,1,
  1,0,
  1,1,
  0,0),
nrow=4,
ncol=2
)

fun_coefficients  <- function(x,y) {
  mapply(function(x, y) {
    coefficients[x, y]
  }, x,y) 
}


model = MILPModel() %>% 
  add_variable(assign[x, y], x = 1:n_truck, y = 1:n_warehouse, type = "binary") %>% 

  add_constraint(sum_expr((assign[x, y]*fun_coefficients(x,y)), y = 1:n_warehouse) == equalto[x], x = 1:n_truck) 

model$constraints
```
You can see that the coefficient associated with every row/col combination is not correct. As they should be 0,1,1,1,1,0,0,0 as can be derived from the coefficient matrix. Rather what is outputted is the first element of the row in the coefficientmatrix duplicated.

![uneven](https://user-images.githubusercontent.com/41294010/43469317-2cdba0ba-94e6-11e8-9c6c-011050f58aaf.PNG)

Applying the colwise function results in the error:

> Error in `[[<-.data.frame`(`*tmp*`, "coef", value = c(0, 1, 1, 0, 0, 1,  : 
>   replacement has 16 rows, data has 8

The only fix, which involves a combination of a for loop and colwise function, that works is the following code:
```R
for (x in 1:n_truck) {
  model = add_constraint(model, sum_expr((assign[x, y]*colwise(fun_coefficients(x,y))), y = 1:n_warehouse) == equalto[x]) 
}
```
instead of 

```R
add_constraint(sum_expr((assign[x, y]*fun_coefficients(x,y)), y = 1:n_warehouse) == equalto[x], 
  x = 1:n_truck)


```

The problem is that due to the many loops when n_truck is big the model_solve() does not work work and throws a memory related error after using up all available RAM memory.

Anyone able to help?

Thank you in advance.

**Comment by dirkschumacher** [comment]
Thanks. Will try to take a look on the weekend. 
PS: I extracted the code from your attached txt file and put it into your question

**Comment by moaarab** [comment]
Thank you, I appreciate the effort. Let me know if you need any more input/information.

**Comment by dirkschumacher** [comment]
I must admit, this functionalty is not covered by existing tests and is thus not easily possible 🙈. Will be working on extending colwise to support this.

My current idea is to have something like this:

```R
x[1:4, colwise(1:2)] * colwise(1:4, 1:4)
```

**Comment by moaarab** [comment]
Thanks for looking into it! It would be very nice to have this functionality in the MILP backend. Do you think that vectorizing everything instead of using the for loop will make solve the RAM depletion problem?

**Comment by moaarab** [comment]
Wonderful! Thanks for the adaption. Will try it out asap.
