### ISSUE TITLE
Error in check_for_unknown_vars_impl(model, the_ast) : The expression contains a variable that is not part of the model. 

### ISSUE THREAD

**Issue by ShuchitaShukla** [dirkschumacher/ompr#215]
Hi @dirkschumacher ,

My problem is related to manufacturing industry. We have an Inventory of stock . for eg.

A | B | C | D | … | 68columns
-- | -- | -- | -- | -- | --
0 | 213 | 50 | 415 |   | 123

We have a raw materials table which states for one unit of order item , how much raw materails is required.

eg.

Ordr no | A | B | C | D
-- | -- | -- | -- | --
1 | 2 | 1 | 3 | 4
2 | 0 | 3 | 1 | 2
3 | 1 | 2 | 4 | 0
4 | 1 | 0 | 2 | 1

There is a vector quantity req for each order number.
we want to max the revenue by determining how much qty can we sell given the constraint that  it cannot be more than qty required and total quantity sold multiplied by raw materials will give total raw materials req, which should not exceed the inv stock column wise. 

Please find the below code. Adding the last constraint , im getting an error.

ibrary(Rglpk)
library(magrittr)
library(dplyr)
library(ROI)
library(ROI.plugin.glpk)
library(ompr)
library(ompr.roi)

data<-read.csv('input.csv',header=TRUE,sep=",")
Inv_Stock<-read.csv('INV_DATA.csv',header = TRUE,sep = ",")
qty_req<- data[,5]
qty_req<- sapply(qty_req,as.double)

Revenueperunit<-data[,4]
Revenueperunit<-sapply(Revenueperunit,as.double)

Raw_mat<-data[,-c(1,2,3,4,5)]
set.seed(0)
n<-172

model <- MIPModel() %>%
  add_variable(Qtysold[i],i=1:n,type = "integer" ,lb=0 ) %>%
  add_variable(Total_mat[i,j],i=1:n,j=1:68, type = "continuous", lb = 0) %>%
  set_objective(sum_expr(Qtysold[i]*Revenueperunit[i],i=1:n), "max")%>%
  add_constraint(Qtysold[i] <= qty_req[i], i = 1:n)%>%
  add_constraint(Qtysold[i]*Raw_mat[i,j]==Total_mat[i,j],i=1:n,j=1:68)%>%
  add_constraint(colSums(Total_mat[i,j],i=1:n)<=Inv_Stock[j],j=1:68)
result <- solve_model(model, with_ROI(solver = "glpk"))

**Comment by moaarab** [comment]
It is probably is due to the fact that you are using the colSums function combined with index summation over i=1:n.  According to me you can only do that when using a sum_expr().

**Comment by ShuchitaShukla** [comment]
@moaarab Thanks. I tried it with sum_expr(), but its still giving the same error.

**Comment by dirkschumacher** [comment]
@ShuchitaShukla try building a minimal model. A good strategy is to reduce the number of variables as much as possible. Then remove constraints to find the constraint causing the problem. A good example for the issue tracker here is an example anyone can run and that does not require any additional datasets.

**Comment by ShuchitaShukla** [comment]
@dirkschumacher ,
Thanks for your response. I checked one by one, on adding the below constraint, i am getting error.
add_constraint(colSums (Total_mat[i,j],i=1:n)<=Inv_Stock[j],j=1:68)
Error in check_for_unknown_vars_impl(model, the_ast) :                                    
  The expression contains a variable that is not part of the model.
I am not able to understand the issue, I also tried replacing colSums with sum_expr.

Appreciate your help in this.

**Comment by dirkschumacher** [comment]
you are using `colSums`, which is a base R function not supported in `ompr`.  You can only use `sum_expr` to create a sum of variables.

**Comment by ShuchitaShukla** [comment]
@dirkschumacher ,

I tried with sum_expr but i am getting the below error:

Error in check_for_unknown_vars_impl(model, the_ast) :
The expression contains a variable that is not part of the model.

**Comment by dirkschumacher** [comment]
Please provide a minimal example that I can run and I will try to help you.

**Comment by dirkschumacher** [comment]
yes

**Comment by ShuchitaShukla** [comment]
many thanks, i have sent

**Comment by ShuchitaShukla** [comment]
@dirkschumacher ,

please confirm if you received my email.

Thank you.
