### ISSUE TITLE
MIP code not running for long dataset

### ISSUE THREAD

**Issue by ShuchitaShukla** [dirkschumacher/ompr#217]
Hi @dirkschumacher 
This code does not run for long dataset.If i increase n to 400 , it does not run.

n<-200
model <- MIPModel() %>%
  add_variable(x[i,j], i = 1:n, j = 1:(m + 1), type = "integer") %>%
  set_objective(sum_expr(input[i,3] * x[i,1], i = 1:n), 'max') %>%
  add_constraint(x[i,1] <= input[i,4], i = 1:n) %>%
  add_constraint(x[i,(j+1)] == x[i,1] * present[i,j], i = 1:n, j = 1:m)%>%
  add_constraint(x[i,j] >= 0, i = 1:n, j = 1:m)%>%
  add_constraint(sum_expr(x[i,j], i = 1:n) <= sum_inv[1,j], j = 2:(m+1))

result <- solve_model(model, with_ROI(solver = "glpk", verbose = TRUE))

**Comment by dirkschumacher** [comment]
What do you mean by it "does not run"?

**Comment by ShuchitaShukla** [comment]
@dirkschumacher ,

Im getting the following error on runnning it for n=500

Error: cannot allocate vector of size 292 Kb

**Comment by dirkschumacher** [comment]
Maybe the model growth to big for the `MIPModel` backend. What is your value of `m`?

**Comment by ShuchitaShukla** [comment]
The value of m is 68. i will provide you the example soon.

**Comment by ShuchitaShukla** [comment]
Also please explain what do u mean by MIP Model backend.

**Comment by hugolarzabal** [comment]
> Error: cannot allocate vector of size 292 Kb
This kind of error when R does use all the RAM of the computer and doesn't have any space left to continue calculations.

The github version of OMPR makes available the MILPModel function which use vectors syntax and is a lot faster and allow bigger models.
The MIPModel is very slow and use a lot of memory whith big models.
