### ISSUE TITLE
not common error in MILP

### ISSUE THREAD

**Issue by errodd** [dirkschumacher/ompr#218]
Hi, I had working with your library in a math model for MIP. When I run this code with MIP:

omprMIPWithL1 <- function(A, K, lambda, epsilon = 0, maxi, mini){
    N <- ncol(A)

    #setting the model with the correspondient restrictions and variables
    result <- MIPModel() %>%
        add_variable(x[i], i = 1:N, type = "continuous", lb = 0) %>%
        add_variable(y[i], i = 1:N, type = "continuous", lb = 0) %>%
        add_variable(w[i], i = 1:N, type = "binary") %>%
        set_objective(sum_expr(y[i], i = 1:N), sense = "min") %>%
        add_constraint(sum_expr(A[i, j] * x[j], j = 1:N) - y[i] <=  K[i], i = 1:N) %>%
        add_constraint(sum_expr(A[i, j] * x[j], j = 1:N) + y[i] >=  K[i], i = 1:N) %>%
        add_constraint(x[i] - lambda * w[i] <= epsilon, i = 1:N) %>%
        add_constraint(x[i] + lambda * w[i] <= maxi + lambda, i = 1:N) %>%
        add_constraint(x[i] - lambda * w[i] >= mini - lambda, i = 1:N) %>%
        solve_model(with_ROI(solver = "glpk")) 
    get_solution(result, x[i])$value
}

The problem is that MIPModel run slow (1 minute when the matrix A is 120x120). I tried with MILP using the same code above but changing MIPModel to MILPmodel, te code is: 

omprMILPWithL1 <- function(A, K, lambda, epsilon, maxi, mini){
    N <- ncol(A)

    #setting the model with the correspondient restrictions and variables
    result <- MILPModel() %>%
        add_variable(x[i], i = 1:N, type = "continuous", lb = 0) %>%
        add_variable(y[i], i = 1:N, type = "continuous", lb = 0) %>%
        add_variable(w[i], i = 1:N, type = "binary") %>%
        set_objective(sum_expr(y[i], i = 1:N), sense = "min") %>%
        add_constraint(sum_expr(A[i, j] * x[j], j = 1:N) - y[i] <=  K[i], i = 1:N) %>%
        add_constraint(sum_expr(A[i, j] * x[j], j = 1:N) + y[i] >=  K[i], i = 1:N) %>%
        add_constraint(x[i] - lambda * w[i] <= epsilon, i = 1:N) %>%
        add_constraint(x[i] + lambda * w[i] <= maxi + lambda, i = 1:N) %>%
        add_constraint(x[i] - lambda * w[i] >= mini - lambda, i = 1:N) %>%
        solve_model(with_ROI(solver = "glpk")) 
    get_solution(result, x[i])
}

When I run this code, the error is: "Error in A[i, j] * x[j]: non-numeric argument to binary operator" in the line of add_constraint(sum_expr(A[i, j] * x[j], j = 1:N) - y[i] <=  K[i], i = 1:N) function (also the line below that use the same matrix A present the same error). I would like that you help me with this error. Please.

note: the matrix A contains numeric values. Greetings

**Comment by dirkschumacher** [comment]
You need to wrap `A[i, j]` into a function as `i` and `j` are vectors.
see #214  and https://dirkschumacher.github.io/ompr/dev/articles/milp-modelling.html#coefficients-and-colwise

You have to use the github version until the new version is on CRAN.

**Comment by errodd** [comment]
Thank you! I will to try it :)
