### ISSUE TITLE
Error in .Primitive(".Call") Incorrect number of arguments (5)

### ISSUE THREAD

**Issue by edgBR** [dirkschumacher/ompr#219]
Dear colleagues, 

I was trying to translate my JuMP code to ompR in order to solve a simplified version of the commitment problem:
![image](https://user-images.githubusercontent.com/14976422/44845070-da9cc800-ac4c-11e8-9450-911aa401d36a.png)

Lets consider that I am only taking into account the first constraint and a modification of the upper and lower limits of the output power implementing the following code:

```
a<-c(12000,13000,14000,11000,12500,10500)
b<-c-131, -145, -114, -120, -104,  -99)
X0<-c(1,1,0,1,0,1)

result <- MIPModel() %>%
  
#Inicialising variables
  
  add_variable(p[j,t], j = 1:(ncol(Demand)-1), t=1:nrow(Demand), type = "continuous", lb >= 0) %>%
  add_variable(u[j,t], j = 1:(ncol(Demand)-1), t=1:nrow(Demand), type = "binary") %>%
  add_variable(s[j,t], j = 1:(ncol(Demand)-1), t=1:nrow(Demand), type = "continuous", lb >=0) %>%

#Setting Objective
  set_objective(sum_expr(b[j]*p[j,t])+a[j]+s[j,t], j = 1:(ncol(Demand)-1), t=1:nrow(Demand)), "min") %>%
  
#Setting constrains
  
  #Power Balance
  
  add_constraint(sum(p[j,t]) == Demand$Total[t], j = 1:(ncol(Demand)-1), t=1:nrow(Demand)) %>%
  
  #Capacity Limits
  
  add_constraint(p[j,t] <= Pmax[j,t] * u[j,t], j = 1:(ncol(Demand)-1), t=1:nrow(Demand)) %>%
  add_constraint(p[j,t] >= Pmin[j,t] * u[j,t], j = 1:(ncol(Demand)-1), t=1:nrow(Demand)) %>%
  
  #Starup cost
  add_constraint(s[j,t] >= d[j] * (u[j,t] - X0[j]), j = 1:(ncol(Demand)-1), t=1:nrow(Demand)) %>%
  add_constraint(s[j,t] >= d[j] * (u[j,t] - u[j,t-1]), j = 1:(ncol(Demand)-1), t=1:nrow(Demand))

result <- solve_model(model, with_ROI(solver = "glpk", verbose = TRUE))
```

But I am getting the following error:

Error in .Primitive(".Call")(list(name = "rlang_tilde_eval", address = <pointer: 0x0000000009b80780>,  : 
  Incorrect number of arguments (5), expecting 4 for 'rlang_tilde_eval'

Do you know why this issue is happening?

BR,
Edgar

**Comment by edgBR** [comment]
Any similar issues for some of the users of ompr?

**Comment by dirkschumacher** [comment]
Would be great if you can create a minimal example what goes wrong. Until then I will close issue, but I am happy to reopen it once you provide further input. Thanks!
