### ISSUE TITLE
Unexpected operator ... found

### ISSUE THREAD

**Issue by dsparks** [dirkschumacher/ompr#220]
Please forgive me if this is not the appropriate venue for this question, but I have been encountering the error `Error: Unexpected operator 'lookup_function' found.` when I run the following (simplified example) code:

```r
rm(list = ls())
library(ompr)
library(ompr.roi)
library(ROI.plugin.glpk)
library(dplyr)
library(tidyr)

# Generate data ================================================================
set.seed(1)
n_workers <- 5
n_shifts <- 21
unit_size <- 3
# Each set of three workers has a different observed productivity level
combination_values <- expand.grid(x = 1:n_workers,
                                  y = 1:n_workers,
                                  z = 1:n_workers) %>%
  filter(x < y, y < z) %>%
  mutate(value = rnorm(n(), 10, 3))

# Lookup function ==============================================================
# Given a set of three workers, return their productivity level
lookup_function <- function(x, y, z){
  combination_vector <- c(x, y, z)
  
  which_combination <- combination_values %>%
    dplyr::select(-value) %>%
    sweep(., 2, combination_vector, "==") %>%
    rowSums() %>%
    magrittr::equals(3) %>%
    which()
  
  combination_value <- -10000
  
  if(length(which_combination) > 0){
    combination_value <- combination_values$value[which_combination]
  }
  
  return(combination_value)
}

lookup_function(2, 3, 4)

# Specify model ================================================================
# A very basic, largely unconstrained model, which _should_ return the
# most productive three-worker set for all of the 21 shifts.
mip_model <- MIPModel() %>% 
  add_variable(x[i, j], type = "integer",
               i = 1:n_shifts, j = 1:unit_size,
               lb = 1, ub = n_workers) %>%
  set_objective(sum_expr(lookup_function(x[i, 1], x[i, 2], x[i, 3]),
                         i = 1:n_shifts)) %>%
  add_constraint((x[i, 1] + 0.1) <= x[i, 2], i = 1:n_shifts) %>%
  add_constraint((x[i, 2] + 0.1) <= x[i, 3], i = 1:n_shifts)
mip_model

# Solve ------------------------------------------------------------------------
result <- mip_model %>%
  solve_model(with_ROI(solver = "glpk", verbose = TRUE))
result %>%
  get_solution(x[i, j]) %>%
  dplyr::select(-variable) %>%
  spread(j, value)
```

I don't really see how my `lookup_function()` here is substantially different from the `weight()` function defined in the [Assigning students to courses](https://dirkschumacher.github.io/ompr/articles/problem-course-assignment.html) vignette. What is causing this error? How can I use my `lookup_function()`, or something with similar functionality?

Thank you for your time and help.

**Comment by hugolarzabal** [comment]
`lookup_function(x[i, 1], x[i, 2], x[i, 3])` : This is not allowed in linear programing.
You cannot have your variables used inside a function.

In the assigning students vignette, weight is used to multiply a variable but it is not applied to a variable:
`set_objective(sum_expr(weight(i, j) * x[i, j], i = 1:n, j = 1:m))`

**Comment by dsparks** [comment]
Thank you so much for your response. I have developed a workaround, but am now facing a new problem, which I illustrate below with a simplified example:

I have a series of (21) shifts, and a constraint on the number of shifts that each of two units can work total. I use `add_variable` to produce an ordered list indicating which of two units works in each of the 21 shifts.

``` r
set.seed(2)
n_shifts <- 21
max_shifts <- 11

test_model <- MIPModel() %>%
  add_variable(x[i],
               type = "binary",
               i = 1:n_shifts) %>%
  add_constraint(sum_expr(x[i],
                          i = 1:n_shifts) == max_shifts)

test_result <- solve_model(test_model, with_ROI(solver = "glpk", verbose = TRUE))

test_result %>% 
  get_solution(x[i])
```

But I want to *minimize* the number of switches between one unit and another. In this simplified toy example, the answer is trivial: `0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1`, but in my actual, more complicated problem, it is not trivial.

Here is my best attempt at adding such an objective:

``` r
test_model_2 <- MIPModel() %>%
  add_variable(x[i],
               type = "binary",
               i = 1:n_shifts) %>%
  set_objective(sum_expr(x[i] - x[i+1],  # This subtraction does not help
                         # because the sum of consecutive differences is the
                         # same regardless of order.
                         i = 1:(n_shifts-1)),
                sense = "min") %>%
  add_constraint(sum_expr(x[i],
                          i = 1:n_shifts) == max_shifts)

test_result_2 <- solve_model(test_model_2, with_ROI(solver = "glpk", verbose = TRUE))
test_result_2

test_result_2 %>% 
  get_solution(x[i])
```

But, obviously, `x[i] - x[i+1]` does not produce a stable solution. I believe that something like `x[i] == x[i+1]`, or `x[i] * x[i+1]`, or `abs(x[i] - x[i+1])` would work, but those are not permitted.

Do you have any suggestions as to how I could implement this objective, or, more generally, check whether consecutive values of a variable are the same?
