### ISSUE TITLE
MIPModel and MILPModel yielding different results

### ISSUE THREAD

**Issue by SiSchu** [dirkschumacher/ompr#222]
Hi Dirk,

this came up in my master thesis when I tried to replace `MIPModel()` with `MILPModel()` to get a much needed performance boost.
Suppose a student has some (fake money) budget and each course has a (fake money) price. We want to maximize her utility given her stated values for the courses. However, there are two constraints: The budget constraint, and a course seat constraint: She may take at most two seats (so effectively 2 out of 3 courses here).
Anyway, `MILPModel()` yields an incorrect result (decides to buy courses 1&2 instead of 2&3). `MIPModel()` solves this just fine, albeit a lot slower (this matters as I will have to solve thousands of these kinds of problems with a larger problem size).

Here is the code:

```R
library(tidyverse)
library(ompr)
library(ompr.roi)

schedule_constraint <- 2
budget_constraint <- 100
prices <- c(0,0,100)
values <- c(4,5,6)
seat_weight <- c(1,1,1)

MIP <- MIPModel() %>%
  add_variable(x[j], j = 1:3, type = "binary")%>%
  set_objective(sum_expr(values[j] * x[j], j = 1:3), sense = "max") %>%
  add_constraint(sum_expr(prices[j] * x[j], j = 1:3) <= budget_constraint) %>%
  add_constraint(sum_expr(x[j] * seat_weight[j], j = 1:3)<= schedule_constraint)
MIP
solve_model(MIP, with_ROI(solver = "cplex", verbose = FALSE)) %>% 
  get_solution(x[j])


MILP <- MILPModel() %>%
  add_variable(x[j], j = 1:3, type = "binary")%>%
  set_objective(sum_expr(values[j] * x[j], j = 1:3), sense = "max") %>%
  add_constraint(sum_expr(prices[j] * x[j], j = 1:3) <= budget_constraint) %>%
  add_constraint(sum_expr(x[j] * seat_weight[j], j = 1:3)<= schedule_constraint)
MILP
solve_model(MILP, with_ROI(solver = "cplex", verbose = FALSE)) %>% 
  get_solution(x[j])

```

I am on ompr and ompr.roi 0.80 (from CRAN).
Feel free to point out any error I made ;)
Thanks!

**Comment by dirkschumacher** [comment]
If you really want speed, you can also build a matrix that has two rows. The knapsack problems are usually quite straightforward in terms of matrix formulation. Here is the ROI code:

```R
constraints <- ROI::L_constraint(rbind(prices, seat_weight),
                                 c("<=", "<="), 
                                 c(budget_constraint, schedule_constraint))
op <- ROI::OP(values, constraints = constraints, types = rep.int("B", length(values)), maximum = TRUE)
sol <- ROI::ROI_solve(op, "glpk")
ROI::solution(sol)
```

This saves you the abstractions cost of `ompr`.
