### ISSUE TITLE
Feature Request: Write out formulation in standard form

### ISSUE THREAD

**Issue by sbmack** [dirkschumacher/ompr#223]
The ROI package has the function write.op to write out the formulation for visual inspection.  For example:
```
  wd <- getwd()
  file_out <- paste(wd, "model.txt", sep = "/")
  write.op(model, file_out, "lp_lpsolve")
```
So the model gets exported for the modeler to examine.

Creating an ompr function to export the formulation directly or a write_model(with_ROI(...)) function similar to solve_model(with_ROI(...)) would be very valuable.

BTW, this is a nice piece of work.

**Comment by hugolarzabal** [comment]
In ompr.roi there is a function called `as_ROI_model` which transform an ompr model into roi model.

I think that `write.op(as_ROI_model(model), file_out, "lp_lpsolve")` should work.

**Comment by sbmack** [comment]
That works.  I missed the as_ROI_model function in the documentation.
Great feature.  Thanks!
