### ISSUE TITLE
Objective function to minimize switching

### ISSUE THREAD

**Issue by dsparks** [dirkschumacher/ompr#224]
I have tried and failed to develop an objective function that minimizes the number of switches between values in an ordered list of either integer or binary variables. See below for a simplified example:

I have a series of (21) shifts, and a constraint on the number of shifts that each of two units can work total. I use `add_variable` to produce an ordered list indicating which of two units works in each of the 21 shifts.

``` r
set.seed(2)
n_shifts <- 21
max_shifts <- 11

test_model <- MIPModel() %>%
  add_variable(x[i],
               type = "binary",
               i = 1:n_shifts) %>%
  add_constraint(sum_expr(x[i],
                          i = 1:n_shifts) == max_shifts)

test_result <- solve_model(test_model, with_ROI(solver = "glpk", verbose = TRUE))

test_result %>% 
  get_solution(x[i])
```

But I want to *minimize* the number of switches between one unit and another. In this simplified toy example, the answer is trivial: `0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1`, but in my actual, more complicated problem, it is not trivial.

Here is my best attempt at adding such an objective:

``` r
test_model_2 <- MIPModel() %>%
  add_variable(x[i],
               type = "binary",
               i = 1:n_shifts) %>%
  set_objective(sum_expr(x[i] - x[i+1],  # This subtraction does not help
                         # because the sum of consecutive differences is the
                         # same regardless of order.
                         i = 1:(n_shifts-1)),
                sense = "min") %>%
  add_constraint(sum_expr(x[i],
                          i = 1:n_shifts) == max_shifts)

test_result_2 <- solve_model(test_model_2, with_ROI(solver = "glpk", verbose = TRUE))
test_result_2

test_result_2 %>% 
  get_solution(x[i])
```

But, obviously, `x[i] - x[i+1]` does not produce a stable solution. I believe that something like `x[i] == x[i+1]`, or `x[i] * x[i+1]`, or `abs(x[i] - x[i+1])` would work, but those are not permitted.

Do you have any suggestions as to how I could implement this objective, or, more generally, check whether consecutive values of a variable are the same?

**Comment by hugolarzabal** [comment]
I think you can solve this by adding an auxiliar variable e[i] such as:
x[i+1] - x[i] <= e[i]
x[i+1] - x[i] >= -e[i]
e[i] >= 0
and minimize e[i] in the objective function.

Those constraints will force e[i] to be equal to abs(x[i+1] - x[i])
