### ISSUE TITLE
set_bounds Error: Index var.status[i] not bound by quantifier

### ISSUE THREAD

**Issue by sbmack** [dirkschumacher/ompr#225]
I am building a model with category (factor) constraints.  I first extract the variable indexes of the target category and then pass them to a constraint.  For example:

```
var.inter <- which(inter == "I")
cnt.inter <- length(var.inter)
```
var.inter is the vector of variable index values with the factor inter = "I", cnt.inter is the length of the vector.  Those values are then passed to a constraint:
```
      add_constraint(model, sum_expr(admit[var.inter[i]],
                              i = 1:cnt.inter) >= 2)
```
So for example if var.inter = {2, 5, 11} then cnt.inter = 3 and the var.inter values are assigned to the variable admit.  That works perfectly in creating the constraint.  However when I apply the same method to a bound:
```
var.status <- which(status == "Admit")
cnt.status <- length(var.status)

      set_bounds(admit[var.status[i]], lb = 1, i = 1:cnt.status)
```
That fails with the message:

Error: Index var.status[i] not bound by quantifier.

In my test case var.status = {1, 55} and cnt.status = 2, so the data structures appear to be same as with the constraint that works properly.

Any ideas?

BTW, ompr really is a nice package.  Thanks for your efforts.

SteveM

**Update: This method I created to formulate category (R factors) constraints fails completely using the MILPMODEL back end.**

**Comment by dirkschumacher** [comment]
Does that really work if you pass in logicals as indexes? Not sure, haven't run the code. Would you mind posting a self contained, minimal example of whay you try to achieve?

**Comment by sbmack** [comment]
Thanks must for the reply.  Here's a test data.frame read in as test.df:
```
ID,Val,Fac1,Fac2,Status
ID01,49,U,BBB,Open
ID02,50,U,BBB,Open
ID03,37,U,AAA,Open
ID04,34,U,CCC,Must
ID05,20,U,BBB,Open
ID06,34,U,CCC,Open
ID07,30,I,BBB,Open
ID08,27,U,AAA,Must
ID09,32,U,CCC,Must
ID10,33,U,BBB,Open
ID11,36,I,BBB,Open
ID12,37,U,BBB,Open
ID13,43,I,BBB,Open
ID14,38,U,CCC,Open
ID15,48,I,BBB,Must
ID16,30,U,CCC,Open
ID17,36,U,CCC,Open
ID18,20,U,AAA,Open
ID19,43,I,AAA,Open
```
The binary variable is the ID column. Fac1, Fac2 are Factors with sums being constrained in the model.  Fac1 is a binary Factor so only one value is constrained.  Fac2 has 3 levels, all three are constrained.  Status is the bounds Factor.  A "Must" level should set the lower bound to 1.

Here is the code using the MIP backend:

```
n.vars <- nrow(test.df)
val <- test.df$Val
fac1 <- test.df$Fac1
fac2 <- test.df$Fac2
status <- test.df$Status

var.fac1 <- which(fac1 == "I")
cnt.fac1 <- length(var.fac1)

lev.fac2 <- levels(fac2)
cons.fac2 <- map(lev.fac2, function(x) which(fac2 == x))
cnt.fac2 <- map_int(1:3, function(x) length(cons.fac2[[x]]))

var.status <- which(status == "Must")
cnt.status <- length(var.status)

model <- MIPModel() %>%
      add_variable(ID[i], i = 1:n.vars, type = "binary") %>%

      set_objective(sum_expr(val[i] * ID[i], i = 1:n.vars), "max") %>%
      
      add_constraint(sum_expr(ID[var.fac1[i]],
                              i = 1:cnt.fac1) <= 3) %>%
      
      add_constraint(sum_expr(ID[cons.fac2[[i]][j]],
                              j = 1:cnt.fac2[i]) >= 2, i = 1:3) %>%

      set_bounds(ID[var.status[i]], lb = 1, i = cnt.status)

wd <- getwd()
file_out <- paste(wd, "tester.txt", sep = "/")
write.op(as_ROI_model(model), file_out, "lp_lpsolve")

```
The fac1 constraint is a single vector.  The fac2 case is a a list of vectors.  Each vector contains the ID sub-index values associated with the specific level.   tester.txt output file is the model in standard form.

The formulation fails at the set_bounds statement.  It does work if the bounds statement and last pipe are commented out as demonstrated in the tester.txt file.

I will post the MILP refactor problem separately.  I converted the fac2 indexed list of vectors in the fac2 constraint into a function.  But it fails.
Using purrr map functions to formulate factor constraints seems to be efficient.
Assistance is much appreciated
SteveM

**Comment by sbmack** [comment]
fixed error in original pasted code
