### ISSUE TITLE
Formulating Category Constraints with MILPMODEL

### ISSUE THREAD

**Issue by sbmack** [dirkschumacher/ompr#226]
I formulated an efficient way to generate category constraints using MIPMODEL but the method fails using MILPMODEL.  Problem description:

- I have a table of data.  Each row is a variable.  The columns are both numeric and category values.
- I need to create constraints for the number of values in the solution by specific category value
- For example, one category is "diversity"
- - There are 4 factor levels for diversity: 'grape', 'lime', 'orange', 'peach'
- I want to set a constraint at a maximum number of each level in the solution
- The first step is to get the unique level values as a character vector:
```
`lev <- levels(divcat)
> lev [1] "grape"  "lime"   "orange" "peach"
```
- divcat is the diversity category vector in the table
- The next step is to create a list of 4 vectors

`cons.div <- map(lev, function(x) which(divcat == x))`

- Each vector contains the row numbers in which each level value occurs
- So for example if the table has 50 rows, the con.div list could could look like

```
[[1]]
[1]  4 16 42 47 73 97

[[2]]
 [1]  1  5  9 10 13 19 20 21 22 30 33 38 41 53 54 55 62 76 88

[[3]]
 [1]  2  3  7  8 11 12 14 17 18 23 24 25 26 27 28 29 32 34 35 36 37 39 40 43 45 46 48 49 50 51 56 57 58 60 61 63
[37] 64 65 66 67 68 69 71 72 74 75 78 79 80 81 82 83 84 85 86 87 90 92 93 94 95 96 98

[[4]]
 [1]   6  15  31  44  52  59  70  77  89  91  99 100
```

- Which are the row occurrences of each factor value for the diversity column
- I then get the number of occurrences (count) for each factor value in the list:

```
cnt.div <- map_int(1:4, function(x) length(cons.div[[x]]))

[1]  4 13 29  4
```

- Using cons.div and cnt.div, I create 4 constraints for the categories, 1 for each level:

```
      add_constraint(sum_expr(admit[cons.div[[i]][j]],
                              j = 1:cnt.div[i]) <= 20, i = 1:4) %>%
```

- 'admit' is the variable name
- The constraints limit the occurrence of 'grape', 'lime', 'orange', 'peach' each to 20 or less in the solution
- That constraint definition works for MIPMODEL but fails with MILPMODEL with the error message:

```
Error in cons.div[[i]] : recursive indexing failed at level 2
In addition: Warning message:
In 1:cnt.div[i] : numerical expression has 4 elements: only the first used
```
I cannot think of a work-around from the MILPMODEL documentation.  I think this is good way to include category constraints in a model.   Any advice on how to refactor into MILPMODEL would be appreciated.

SteveM

**Comment by hugolarzabal** [comment]
MILP understand `cons.div[[i]]` as `cons.div[[1:4]]` which doesn't make sense in R which explain the error:
`Error in cons.div[[i]] : recursive indexing failed at level 2`

`j = 1:cnt.div[i]` is not understandable by the MILP model, it reads it as `j = 1:cnt.div[1:4]` and understand `j = 1:cnt.div[1]`
This is the warning:
> In 1:cnt.div[i] : numerical expression has 4 elements: only the first used

You need to use functions which return vectors.
For exemple:
`cnt.div <- function(i) {map_int(i, function(x) length(cons.div[[x]])) }`
`j=1:cnt.div(i)`
