### ISSUE TITLE
Can be used to solve NMF problems?

### ISSUE THREAD

**Issue by privefl** [dirkschumacher/ompr#227]
Thanks again for your presentation in Rennes.

I was wondering if I could use your package to solve a NMF problem like this one:
![nmf](https://user-images.githubusercontent.com/11161036/45553255-aa038380-b833-11e8-9bf0-64c8665a60a2.png)

**Comment by dirkschumacher** [comment]
I doubt it, only if you can make it the objective function linear. Take a look at the ROI package or the cvxr package (https://cvxr.rbind.io/)
