### ISSUE TITLE
Possible error in the package vignette/documentation

### ISSUE THREAD

**Issue by dirkdegel** [dirkschumacher/ompr#228]
Hi @dirkschumacher, I think there is a small error in the vignette?documentation in the section "vectorized-semantics-revisited":
[https://dirkschumacher.github.io/ompr/articles/milp-modelling.html#vectorized-semantics-revisited](https://dirkschumacher.github.io/ompr/articles/milp-modelling.html#vectorized-semantics-revisited)
 This code is given:
```{r}
MILPModel() %>% 
  add_variable(x[i, j], i = 1:n, j = 1:n) %>% 
  add_constraint(sum_expr(x[i, j], i = 1:n) == 1, j = 1:n) %>% 
  add_constraint(x[1:n, colwise(1:n)] == 1) # this this equivalent
```
I guess the right code would be:

```{r}
MILPModel() %>% 
  add_variable(x[i, j], i = 1:n, j = 1:n) %>% 
  add_constraint(sum_expr(x[i, j], i = 1:n) == 1, j = 1:n) %>% 
  add_constraint(x[colwise(1:n), 1:n] == 1) # this this equivalent
```
i.e.,
`1:n, colwise(1:n)` needs to be swapped to `colwise(1:n), 1:n`.

**Comment by dirkschumacher** [comment]
Thanks a lot @dirkdegel . Fixed in the development docs: https://dirkschumacher.github.io/ompr/dev/articles/milp-modelling.html#vectorized-semantics-revisited
