### ISSUE TITLE
Minimum consecutive constraint

### ISSUE THREAD

**Issue by dsparks** [dirkschumacher/ompr#231]
Hello again. Here is a simplified version of my model, in which I am scheduling a set of workers to staff a certain number of hours:

``` r
set.seed(1)
n_hours <- 24
n_workers <- 5
min_total_hours <- 2
max_total_hours <- 7

test_result <- MIPModel() %>%
  add_variable(x[i, j],
               i = 1:n_workers,
               j = 1:n_hours) %>%
  add_constraint(sum_expr(x[i, j],
                          j = 1:n_hours) <= max_total_hours,
                 i = 1:n_workers) %>%
  add_constraint(sum_expr(x[i, j],
                          j = 1:n_hours) >= min_total_hours,
                 i = 1:n_workers) %>%
  add_constraint(sum_expr(x[i, j],
                          i = 1:n_workers) == 1,
                 j = 1:n_hours) %>%
  solve_model(with_ROI(solver = "glpk",
                       verbose = TRUE))

test_result %>% 
  get_solution(x[i, j]) %>%
  dplyr::select(-variable) %>%
  spread(j, value) %>%
  dplyr::select(-1) %>%
  as.matrix()
```
``` r
     1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
[1,] 1 1 0 0 0 0 0 0 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[2,] 0 0 1 1 0 0 0 0 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[3,] 0 0 0 0 1 1 1 0 0  0  0  0  0  0  0  0  0  0  0  0  0  1  1  1
[4,] 0 0 0 0 0 0 0 1 1  0  0  0  0  0  0  0  1  1  1  1  1  0  0  0
[5,] 0 0 0 0 0 0 0 0 0  1  1  1  1  1  1  1  0  0  0  0  0  0  0  0
```

However, I would like to add an additional constraint, `min_consecutive_hours <- 3`, which ensures that, any time one of the workers is scheduled, she works no fewer than three hours in a row.

How can I implement this consecutivity constraint in ompr?

**Comment by hugolarzabal** [comment]
I think that this problem can be solved with a constraint like that (you need to adjust the names of the variables and indexes):
` min_consecutive_hours * (x[i+1] - x[i]) <= sum_expr(x[i+k], k = 1:min_consecutive_hours)  for 1=<i<max_i-min_consecutive_hours`

When a worker start a shift, (x[i+1] - x[i])  will be equal to 1 and force the sum of the next x to be superior or equal to the minimum number of consecutive hours.
