### ISSUE TITLE
Variable ordering error

### ISSUE THREAD

**Issue by sbmack** [dirkschumacher/ompr#233]
I removed the bulk of this message.  Because I found the source of the error.  opmr orders the variable sets in the objective function based on the alphabetical order of the variable names.  So for example in this case:

```
model <- MILPModel() %>%
      add_variable(
            aa[1:5], type = "continuous", lb=0) %>%
      
      add_variable(
            zz[1:5], type = "continuous", lb=0) %>%
      
      set_objective(
            sum_expr(999 * aa[i], i=1:5) +
            sum_expr(333 * zz[i], i=1:5))
```
Variables aa with coefficients 999 are indexed first in the objective function. But when the variable names are reversed:

```
model <- MILPModel() %>%
      add_variable(
            zz[1:5], type = "continuous", lb=0) %>%
      
      add_variable(
            aa[1:5], type = "continuous", lb=0) %>%
      
      set_objective(
            sum_expr(999 * zz[i], i=1:5) +
            sum_expr(333 * aa[i], i=1:5))
```
The aa variables now with coefficients 333 are indexed first.  So the obvious workaround if index order is important is to create variable set names alphabetized to yield the correct order.  E.g., aVarName, bVarName, cVarName...

Thanks much for the consideration.  -SteveM

**Comment by dirkschumacher** [comment]
Thanks for locating the problem. May I ask what your use-case is? Why is column ordering important to you?

**Comment by sbmack** [comment]
> 
> 
> Thanks for locating the problem. May I ask what your use-case is? Why is column ordering important to you?

Because I'm using a clever list of lists method i created to populate constraints.  For example, here is a df of a transportation model (plants -> warehouses):

```
  pl  wh1  wh2  wh3  wh4
1 p1 4000 2500 1200 2200
2 p2 2000 2600 1800 2600
3 p3 3000 3400 2600 3100
4 p4 2500 3000 4100 3700
5 p5 4500 4000 3000 3200
```
I use a gather function to generate a sparse vector representation:

`trans.vars <- gather(trans.costs, wh, cost, -pl, na.rm = TRUE, factor_key = TRUE) `

Which yields this:

```
   pl  wh cost
1  p1 wh1 4000
2  p2 wh1 2000
3  p3 wh1 3000
4  p4 wh1 2500
5  p5 wh1 4500
6  p1 wh2 2500
7  p2 wh2 2600
8  p3 wh2 3400
9  p4 wh2 3000
10 p5 wh2 4000
11 p1 wh3 1200
12 p2 wh3 1800
13 p3 wh3 2600
14 p4 wh3 4100
15 p5 wh3 3000
16 p1 wh4 2200
17 p2 wh4 2600
18 p3 wh4 3100
19 p4 wh4 3700
20 p5 wh4 3200
```
With that structure variable 1 of the model is row 1, variable 2 is row 2...  That's why ordering the variables in the model definition is important.  I then apply this function to generate the list of lists from the normalized variable vector:

```
ListIdx <- function(df) {
      fac.cols <- df[, sapply(df, is.factor)]
      lapply(fac.cols, function(x) split(seq_along(x), x))
}

pl.wh.idx <- ListIdx(trans.vars)
```
The pl.wh.idx list object is this:

```
$`pl`
$`pl`$`p1`
[1]  1  6 11 16

$`pl`$p2
[1]  2  7 12 17

$`pl`$p3
[1]  3  8 13 18

$`pl`$p4
[1]  4  9 14 19

$`pl`$p5
[1]  5 10 15 20


$wh
$wh$`wh1`
[1] 1 2 3 4 5

$wh$wh2
[1]  6  7  8  9 10

$wh$wh3
[1] 11 12 13 14 15

$wh$wh4
[1] 16 17 18 19 20
```
Those list vectors are passed directly to the constraints.  Demand cycles the wh list, Capacity the pl list.  So the individual elements of each vector must correspond to the row numbers of the normalized data frame.  This is a trivial example because the original data matrix was dense.  However for missing values the list vectors would be ragged because the missing values are left out.  This would be very efficient for managing very sparse data vectors.

So you can see that many variable index lists with different factors could be created using the same compact method (transform via gather -> create the list of lists).  With this strategy subsetting of the the base variable indexes could be done external to ompr using tidyverse and set functions.  However I not fully thought out the utility of the method.

Was denken Sie dazu?  SteveM

**Comment by sbmack** [comment]
I see now that this is a non-issue.

I was using the write-op function of ROI to examine the formulation output.  It writes out the variables in a contiguous stream with no linkage to the original variable names.

However I see now using the variable_keys function of ompr that ompr does maintain variable sets as separate named vectors.  And the the solution vectors of each variable set can be accessed independently using the ompr get_solution function.

So since each row of original normalized df of each problem parameter corresponds to a solution vector with the length = nrow of the df I can cbind each solution vector to its parent normalized df and post process from there.

So nice job Dirk in supplying the functionality.  Thanks much.  SteveM
