### ISSUE TITLE
Constraints from List of Indexes

### ISSUE THREAD

**Issue by sbmack** [dirkschumacher/ompr#234]
I have a small multi-period production planning problem.  I want to generate constraints from a list of index vectors.  In this problem there are 5 raw materials (oils)  indexed by 6 periods (months).  Here is the normalized data frame:
```
    oil    month cost
1  VEG1  January  110
2  VEG1 February  130
3  VEG1    March  110
4  VEG1    April  120
5  VEG1      May  100
6  VEG1     June   90
7  VEG2  January  120
8  VEG2 February  130
9  VEG2    March  140
10 VEG2    April  110
11 VEG2      May  120
12 VEG2     June  100
13 OIL1  January  130
14 OIL1 February  110
15 OIL1    March  130
16 OIL1    April  120
17 OIL1      May  150
18 OIL1     June  140
19 OIL2  January  110
20 OIL2 February   90
21 OIL2    March  100
22 OIL2    April  120
23 OIL2      May  110
24 OIL2     June   80
25 OIL3  January  115
26 OIL3 February  115
27 OIL3    March   95
28 OIL3    April  125
29 OIL3      May  105
30 OIL3     June  135
```
Here is the month list:

```
$`January`
[1]  1  7 13 19 25

$February
[1]  2  8 14 20 26

$March
[1]  3  9 15 21 27

$April
[1]  4 10 16 22 28

$May
[1]  5 11 17 23 29

$June
[1]  6 12 18 24 30
```
So the January list vector indicates that VEG1 is the 1st row of the df, VEG2 is the 7th row OIL1 is the 13th row and so on.  This is the ompr model:
```
price <- 150
store.cost <- 5
i.store <- 500

model <- MILPModel() %>%
      add_variable(
            buy[1:n.vars], type = "continuous", lb=0) %>%
      add_variable(
            use[1:n.vars], type = "continuous", lb=0) %>%
      add_variable(
            store[1:n.vars], type = "continuous", lb=0) %>%
      add_variable(
            make[1:n.months], type = "continuous", lb=0) %>%

      set_objective(
            sum_expr(price * make[i], i=1:n.months) -
            sum_expr(colwise(df$cost[i]) * buy[i], i=1:n.vars) -
            sum_expr(store.cost[i] * store[i], i=1:n.vars), 'max') %>%
      ## Initial month material balance with stored raw material inventory of i.store
      add_constraint(
            i.store + buy[i] == use[i] + store[i], i=month[[1]]) %>%
      ## Material balance months 2 - 4
      add_constraint(
            store[i-1] + buy[i] == use[i] + store[i], i=month[[j]], j=2:4)
```
The first constraint set is the material balance for the first month for each raw material.

`            i.store + buy[i] == use[i] + store[i], i=month[[1]])`

That works properly.  It writes out 5 constraints, one for each oil for the first month (January).  However the 2nd constraint set:

`            store[i-1] + buy[i] == use[i] + store[i], i=month[[j]], j=2:4)`

Which is supposed to write out the material balances for months 2 through 4 fails with this error message:

`Error in eval(x$expr, x$env, emptyenv()) : object 'j' not found`

My question is how to define the second constraint set to cycle through the specified list of index vectors?

Any advice appreciated.  Thanks.   SteveM

**Comment by hugolarzabal** [comment]
`store[i-1] + buy[i] == use[i] + store[i], i=month[[j]], j=2:4)`
month[[j]] should be month[j] or directly month[2:4]

Also, I am not sure that having everything in raw with single indexes is the best option (I think that it does works but it is quite unintuitive to understand).

You should consider using variable with two indexes like:
buy[p,t] p 0 1:n_product  m = 1:n_months

**Comment by hugolarzabal** [comment]
You ara right, month[i] fails because it is a list.
`add_constraint( store[i-1] + buy[i] == use[i] + store[i], i=unlist(month[2:4]))` should work

When you talk about sparse matrix, I understand that you mean that not every combination of p and t would exist, right?

If so, you can filter when creating the variables:
`add_constraint(buy[p,t], p = 1:n_product m = 1:n_months, filter = my_filter(p,m))`

Then you won't need to worry about it in the constraint since every non existant variable will be ignored.
You will also get a warning telling you the real number of index combinations used:
> You used the variable 'buy' with 20 indexes but only 15 indexes will be used

**Comment by sbmack** [comment]
Thanks again for the reply.  unlist does work.  I thought about it but assumed that the month[2:4] would be processed as at the console.  I.e., the 3 list vectors concatenated into a single result vector.

But it appears that ompr processes each unlist index element one at a time.  i.e., unlist(month[2]), unlist(month[3]), unlist(month[4]) which generates all of the constraint sets.

I see what you are saying about generating sparse variable vectors.  But then the data passed to them also has to be maintained in sparse format indexed by the factors.  That's what the list of lists method does.

The downside of my approach is what you have mentioned.  It's not as intuitive.  The shortfall is that as of now with ompr/ROI you can't write out the variables by their factor indexes as when using a model manager like MPL.  So validating the input matrix by visual inspection is somewhat more difficult.

Regards, SteveM
