### ISSUE TITLE
Translating complex constraint to MILPmodel()

### ISSUE THREAD

**Issue by dsparks** [dirkschumacher/ompr#236]
Below is a simplified version of a model with a complex, worker-varying minimum-consecutive constraint, which works as a `MIPmodel()`.

``` r
n_hours <- 24 * 3
n_workers <- 5
workers_per_shift <- 2
max_total_hours <- 40
min_consecutive_hours <- sample(c(6, 8), n_workers, replace = TRUE)
worker_productivity <- sort(runif(n_workers))

test_model <- MIPModel() %>%
  add_variable(timesheet[i, j],
               type = "binary",
               i = 1:n_workers,
               j = 1:n_hours) %>%
  set_objective(sum_expr(timesheet[i, j] * worker_productivity[i],
                         i = 1:n_workers,
                         j = 1:n_hours),
                sense = "max") %>%
  add_constraint(sum_expr(timesheet[i, j],
                          i = 1:n_workers) == workers_per_shift,
                 j = 1:n_hours) %>%
  add_constraint(sum_expr(timesheet[i, j],
                          j = 1:n_hours) <= max_total_hours,
                 i = 1:n_workers) %>%
  # Min consecutive constraint
  add_constraint(
    (min_consecutive_hours[i] *
       (timesheet[i, j] - timesheet[i, j - 1])) <=
      sum_expr(timesheet[i, j + l],
               l = 0:(min_consecutive_hours[i] - 1)),
    i = 1:n_workers,
    j = 2:(n_hours - max(min_consecutive_hours - 1))) %>%
  # Getting into the corners for min-consecutive constraint
  add_constraint(
    (min_consecutive_hours[i] *
       timesheet[i, 1]) <=
      sum_expr(timesheet[i, 1 + l],
               l = 0:(min_consecutive_hours[i] - 1)),
    i = 1:n_workers) %>%
  add_constraint(
    (min_consecutive_hours[i] * timesheet[i, j]) <=
      sum_expr(timesheet[i, j - l],
               l = 0:(min_consecutive_hours[i] - 1)),
    i = 1:n_workers,
    j = (n_hours - max(min_consecutive_hours - 1)):n_hours)

test_result <- solve_model(test_model,
                          with_ROI(solver = "glpk",
                                   verbose = TRUE,
                                   control = list(
                                     tm_limit = 2*60*1000)))  # milliseconds
test_result

test_result %>%
  get_solution(timesheet[i, j]) %>%
  dplyr::select(-variable) %>%
  filter(value > 0) %>%
  ggplot(.) +
  aes(x = j, y = i) +
  geom_tile(colour = "white")
```

However, I want to convert this to a `MILPmodel()` for speed. I have attempted to do so by defining a helper function
``` r
min_consecutive_lookup <- function(i){
  colwise(as.integer(min_consecutive_hours[i]))
}
```
and replacing every instance of `min_consecutive_hours[i]` with `min_consecutive_lookup(i)`. However, I get errors like:
```
Warning messages:
1: In 0:(min_consecutive_lookup(i) - 1) :
  numerical expression has 320 elements: only the first used
2: In j + l :
  longer object length is not a multiple of shorter object length
3: In 0:(min_consecutive_lookup(i) - 1) :
  numerical expression has 5 elements: only the first used
4: In 0:(min_consecutive_lookup(i) - 1) :
  numerical expression has 40 elements: only the first used
5: In j - l :
  longer object length is not a multiple of shorter object length
```
Essentially, even after reading all of the documentation and examples I can find, I am having a hard time discerning how best to translate this model to `MILP` format -- can you offer any suggestions for how best to reformulate?

Thanks.

**Comment by hugolarzabal** [comment]
You need to think about your indexes as vectors.

min_consecutive_lookup(i) will be evaluated as min_consecutive_lookup(1:n_workers) which is the vector:
`[1] 6 8 6 8 8`

So when you write `l = 0:(min_consecutive_lookup(i) - 1)`, ompr and R understand `l = 0:(c(6,8,6,8,8)-1)` and only use the first value (6) and conclude that `l = 0:5`

**Comment by etesio** [comment]
Hi @hugolarzabal I am running into a similar issue (or so it seems to me). I am trying to represent a constraint with a sum whose extrema runs over an index `tau`

$\sum_{\tau=t-df_gen(i,"min_up_time")+1}^t x(\tau) \leq y(t)$ 

with the index `t` runs as `t=N:96` and `df_gen` is a data.frame containing the `min_up_time` parameter (integer) for each `i=1:N`. I am attempting to do this as

`add_variable(x[t], t=1:TT, type="binary") %>%`
`add_variable(y[t], t=1:TT, type="binary") %>%`
`add_constraint(sum_expr(x[tau], tau=(t-df_gen[i,"min_up_time"]+1):t) <= y[t], i = 1:N, t = df_gen[i,"min_up_time"]:TT) %>%`

When creating the `MILPModel()` I get

`Warning messages:`
`1: In (t - df_gen[i, "min_up_time"] + 1):t : numerical expression has 475 elements: only the first used`
`2: In (t - df_gen[i, "min_up_time"] + 1):t : numerical expression has 475 elements: only the first used`

which I understand it depends from the fact that being `t` a vector, R is unsure about how to deal with it and always takes the first value (i.e. `df_gen[i,"min_up_time"]`) in my example.

What is the correct `MILPModel()` way of having `t` "looping" over the index set, i.e. what is the correct way to create `N*(T-df_gen[i,"min_up_time"])`  constraints (one for each relevant value of `i` and `t`)? In my example I have `N=5`, `T=96`, `df_gen[1, "min_up_time"]=1` which leads to the warning showing `475` elements.

**Comment by etesio** [comment]
As a minimal example, I can reproduce the issue looking at the difference between the two constraints below 

```
TT <- 10
model2 <- MILPModel() %>%
  add_variable(x[t], t=1:TT, type="binary") %>%
  add_variable(y[t], t=1:TT, type="binary") %>%
  # add_constraint(sum_expr(x[tau], tau=(t-1):t) <= y[t], t=2:TT)  # this does not work?
  add_constraint(x[t-1] + x[t] <= y[t], t=2:TT) # this should be OK
model2
```

**Comment by hugolarzabal** [comment]
You need to create a list of the different values that tau may have depending on t.
```
list_tau <- list()

for (t in 2:TT) {
  list_tau[[t]]<- (t-1):t
}
```
Then the constraint is pretty easy to write:
`add_constraint(sum_expr(x[tau], tau=list_tau[t]) <= y[t], t=2:TT)`

**Comment by etesio** [comment]
Right OK! that makes perfet sense, thanks a lot

**Comment by tjseydel** [comment]
Hello there, 
I have a similar problem. I want to model the following simple constraint: 

![image](https://user-images.githubusercontent.com/30954995/62120413-d7c5af80-b2c1-11e9-9c8b-5954ee9912c8.png)

where _t_ is a timeslot, _lr_ is the length of request _r_, _Xrt_ is a binary decision variable which equals 1 when request _r_  is scheduled on timeslot _t,_ and _Send_ is an auxiliary variable. The constraint ensures that _Send_ is at least as big as the last planned request. 

I am able to model the constraint in a MIP model as follows: 
 ```r
timeslots <- seq(1,17,1)
requests <- seq(1,21,1)
durations <- sample(1:2, 21, replace = TRUE)

model <- MIPModel() %>%
add_variable(x[r,t], r= requests, t= timeslots,
               type = "binary") %>%
add_variable(S_End, type= "integer", lb=0, ub = 17) %>%
add_constraint(sum_expr(x[r,t]*(t+durations[r]-1), t = timeslots) <= S_End, r = requests) 
```
Though, when using the constraint in a MILP i get the error "in t+ durations[r] : longer object lenght is not a mulitple of shorter object length".

The error is given due to the fact that the number of timeslots and the number of requests is not a multiple of each other. Though, it used to work in a MIP model. I can't figure out how I should model this constraint as a MILP constraint.  Does anyone have an idea?
