### ISSUE TITLE
Error: Writing Out Formulation w/o Piping

### ISSUE THREAD

**Issue by sbmack** [dirkschumacher/ompr#240]
Here's a simple model variable declaration with the objective function using piping:

```
model <- MILPModel() %>%

      add_variable(proj[i], i=1:100, type = "binary", lb=0) %>%
      
      set_objective(sum_expr(proj[i], i=1:100), "max") 
```
It properly generates the variable set and the objective function.  However removing the piping and adding the model parameter to the add_variable and set_objective statements:

```
model <- MILPModel()
      
add_variable(model, proj[i], i=1:100, type = "binary", lb=0)
      
set_objective(model, sum_expr(proj[i], i=1:100), "max")  
```

Throws an error:

```
Error in proj[i] : object of type 'closure' is not subsettable
```
It appears to be a syntax error in the set_objective statement, but I can't see where.  Any help?

Thanks, SteveM

**Comment by dirkschumacher** [comment]
Piping chains the calls, so it is equivalent to the following
```R
model <- MILPModel()
model <- add_variable(model, proj[i], i=1:100, type = "binary", lb=0)
set_objective(model, sum_expr(proj[i], i=1:100), "max")

#or 
set_objective(add_variable(MILPModel(), proj[i], i=1:100, type = "binary", lb=0), sum_expr(proj[i], i=1:100), "max")
```

**Comment by sbmack** [comment]
Thanks.  I see: mine versus yours:

```
add_variable(model, proj[i], i=1:100, type = "binary", lb=0) 
model <- add_variable(model, proj[i], i=1:100, type = "binary", lb=0)
```
I thought that using the model name parameter ("model") in the add variable function was sufficient.   Did not realize the add_variable(model...) still had to be assigned to the actual model variable.

**Comment by dirkschumacher** [comment]
The model objects are immutable. Each call to a function creates a new, independent model. They do not modify by reference.
