### ISSUE TITLE
Constraint Syntax: Cost Vector * Variable Vector

### ISSUE THREAD

**Issue by sbmack** [dirkschumacher/ompr#241]
Deleted my original comment because I see that it is an extension of the closed issue #232.  The solution is this code example:

```
library(ompr)
library(magrittr)

vect_list <- list(c(3,8,18,19),c(1,2,5,7,10,11,12,13,15,20),c(4,6,9,14,16,17))

model <- MILPModel()
model %<>% add_variable(x[j], j =1:20)
model %<>% add_constraint(sum_expr(x[j], j = vect_list[i]) <= 3, i = 1:3)
```

That works.  The problem is multiplying the variable in the constraint by a vector of coefficients, c[j]:
`
model %<>% add_constraint(sum_expr(colwise(c[j]) * x[j], j = vect_list[i]) <= 3, i = 1:3)`

Where the vector c has a length of 20.  So the same sub-indexes delivered to x[j] should be delivered to c[j].  However running that code returns the error:

`Error in cost[j] : invalid subscript type 'list'`

I understand that `vect_list[i] `is a list so is rejected by `c[j]`.  But if `vect_list[i]` is replaced with `vect_list[[i]]` to pass the underlying vector, it fails but with a different error code:

`Error in vect_list[[i]] : recursive indexing failed at level 2`

So how to multiply the variables in a constraint by a vector of coefficients?
Thanks for the assistance.  SteveM

**Comment by sbmack** [comment]
Update on the above.  It turn outs that the constraint syntax:

```
  add_constraint(
        sum_expr(colwise(cost[i]) * proj[i], i=cat.idx[j]) <= 10000, j=1:n.cat)
```
Actually does properly generate the constraints.  So the error is actually in the error processing.  I.e., Type 1 error.

**Comment by hugolarzabal** [comment]
You need to replace c by a function.

In your case a simple function like
`fun_c <- function(j) { c[unlist(j)] }`
should work

**Comment by sbmack** [comment]
Thanks, for the reply.   I tried that.  I created a "cost" vector instead of "c" for clarity.  Calling the function,
`f_cost(vect_list[2])` from the console returns the proper cost vector by sub-index.
```
vect_list <- list(c(3,8,18,19),c(1,2,5,7,10,11,12,13,15,20),c(4,6,9,14,16,17))
cost <- c(454, 447, 811, 274, 309, 821, 203, 640, 279, 992, 893, 138, 857, 291, 936,
               632, 829, 140, 313, 298)

f_cost <- function(x) {
      y <- unlist(x)
      z <- cost[y]
      return(z)
}

model <- MILPModel()
model %<>% add_variable(x[j], j =1:20)
model %<>% add_constraint(sum_expr(f_cost(j) * x[j], j = vect_list[i]) <= 3, i = 1:3)
```
However, running the model code produces these constraints:

```
+811 C3 +811 C8 +811 C18 +811 C19 <= 3;
+640 C1 +640 C2 +640 C5 +640 C7 +640 C10 +640 C11 +640 C12 +640 C13 +640 C15 +640 C20 <= 3;
+140 C4 +140 C6 +140 C9 +140 C14 +140 C16 +140 C17 <= 3;
```
You can see that only the first element of each vector is used.  Which suggests applying the colwise function to the f_cost return value:

```
model <- MILPModel()
model %<>% add_variable(x[j], j =1:20)
model %<>% add_constraint(sum_expr(colwise(f_cost(j)) * x[j], j = vect_list[i]) <= 3, i = 1:3)
```
However, that code fails with the message:

```
Error in `[[<-.data.frame`(`*tmp*`, "coef", value = c(811, 640, 140, 313,  : 
  replacement has 60 rows, data has 20
In addition: Warning message:
In coef * val :
  longer object length is not a multiple of shorter object length
```
I just discovered something else.  If I change the i index to a simple scalar the colwise function works.  E.g. `i=3`:

```
model <- MILPModel()
model %<>% add_variable(x[j], j =1:20)
model %<>% add_constraint(sum_expr(colwise(f_cost(j)) * x[j], j = vect_list[i]) <= 3, i = 3)
```
Executing that yields:

`+274 C4 +821 C6 +279 C9 +291 C14 +632 C16 +829 C17 <= 3;`

So the problem is with the i index generating multiple constraints.  This is such a common constraint I'm sure somebody has figured it out.  But not knowing how myself is really holding me back.  Again, appreciate the assistance.

**Comment by sbmack** [comment]
Of course I can loop through the i index with a for construct

```
model <- MILPModel()
model %<>% add_variable(x[j], j =1:20)
for (k in 1:3) {
model %<>% add_constraint(sum_expr(colwise(f_cost(j)) * x[j], j = vect_list[i]) <= 3, i=k)
}
```

But I'd rather not if I don't have too...

**Comment by hugolarzabal** [comment]
I think that putting the colwise in the function may work:
```
f_cost <- function(x) {
      y <- unlist(x)
      z <- cost[y]
      return(colwise(z))
}
```

Another alternative is to provide the entire vector in the right order:
```
vect_cost <- cost[unlist(vect_list[1:3])]
model %<>% add_constraint(sum_expr(  colwise(vect_cost) * x[j], j = vect_list[i]) <= 3, i = 1:3)
```

**Comment by sbmack** [comment]
Thanks again for thinking about this.  I tried those and every possible way of using colwise.  They all fail with the same error message:

```
Error in `[[<-.data.frame`(`*tmp*`, "coef", value = c(811, 640, 140, 313,  : 
  replacement has 60 rows, data has 20...
```
Since the simple syntax works for the scalar case, the error must be in looping through the RHS vector, not with colwise.

I'm going to post a request for the var vectors and coefficient vectors to accept the same data types for indexes.  In other words if var[i] processes a list vector then so should coeff[i].

**Comment by hugolarzabal** [comment]
This error is due to the fact that sum_expr works in an unintuitive way with constants with indexes.
It creates 3 * 20 values instead of 20 values.

The two solutions I proposed do works for me without any error. Do you have the latest github version of ompr ?

**Comment by sbmack** [comment]
hugo, thanks again for the reply and the assistance.  I am running ompr ver. 0.8.0  If you could post the exact code that works for you, I will copy and paste.
Regards, SteveM

**Comment by hugolarzabal** [comment]
```
library(ompr)
library(magrittr)

vect_list <- list(c(3,8,18,19),c(1,2,5,7,10,11,12,13,15,20),c(4,6,9,14,16,17))
cost <- c(454, 447, 811, 274, 309, 821, 203, 640, 279, 992, 893, 138, 857, 291, 936,
          632, 829, 140, 313, 298)

f_cost <- function(x) {
  y <- unlist(x)
  z <- cost[y]
  return(colwise(z))
}

model <- MILPModel()
model %<>% add_variable(x[j], j =1:20)
model %<>% add_constraint(sum_expr(x[j], j = vect_list[i]) <= 3, i = 1:3)
model %<>% add_constraint(sum_expr(  colwise(f_cost(j)) * x[j], j = vect_list[i]) <= 3, i = 1:3)
```

**Comment by sbmack** [comment]
hugo, thanks for the quick turn.  But nope, it's still busted on my end with the error:

```
Error in `[[<-.data.frame`(`*tmp*`, "coef", value = c(811, 640, 140, 313,  : 
  replacement has 60 rows, data has 20
In addition: Warning message:
In coef * val :
  longer object length is not a multiple of shorter object length
```
I'm flummoxed...

**Comment by hugolarzabal** [comment]
You should download the latest version from github.

The last version is  0.8.0.9000 and not 0.8.0

And there are changes about sum_expr between those two versions.

**Comment by sbmack** [comment]
Installing from github works!  Thanks.  Note that in the example problem using the colwise statement in the external function alone works making the model code a little cleaner.
