### ISSUE TITLE
Column Generation with ompr

### ISSUE THREAD

**Issue by dirkdegel** [dirkschumacher/ompr#242]
I'm just curious if it is possible to implement a column generation algorithm with ompr (similar as in Julia/Jump, see here: [http://www.juliaopt.org/notebooks/Shuvomoy%20-%20Column%20generation.html](http://www.juliaopt.org/notebooks/Shuvomoy%20-%20Column%20generation.html)). For my understanding there are no functions available in ompr to modify the objective function or add columns to the contraints.

**Comment by sbmack** [comment]
When I read the JuMP code it calls the solver 2x, `solve(cutstockSub)`  For a delayed column generation  and then a re-solve after evaluating the solution of the first solve.

So in other words, delayed column generation is not a native JuMP function but can be implemented using a loop for updating and re-solve.  Which suggests the same could be done in R by replicating the JuMP model logic.

**Comment by dirkschumacher** [comment]
I think to make Column generation really efficient a different model needs to be used that modifies the solution in place (i.e. directly communications with the solver). I really like the new math. prog. API that the julia folks come up with. It is on my idea list, but as you all might have noticed, I am super short on time at the moment.

**Comment by dirkschumacher** [comment]
See https://github.com/r-opt/rmpk

@dirkdegel do you want to try it with `rmpk`? Post an issue there, if you are interested.
