### ISSUE TITLE
Evaluating twice yields different results

### ISSUE THREAD

**Issue by jdb78** [dirkschumacher/ompr#243]
I currently employ a MILP model with the symphony solver. I first solve the linear problem to determine lower and upper bounds for my MIP problem.
Then, I convert the linear model into a MIP problem by simply setting the variable type to 'integer' and updating the lower and upper bounds. In the next step, the model is solved using symphony. It fails stating there is an infeasibility. So far, so good.

However, when I execute the line
`milp_result <- ompr::solve_model(milp_model, ompr.roi::with_ROI('symphony))`
a second time in the script, an optimal solution is found.

Any ideas how to explain this?

**Comment by sbmack** [comment]
Some error analysis advice:

Write out the model in standard form before each solve to visually inspect that they are equivalent.  i.e.

```
wd <- getwd()
file_out <- paste(wd, "milp_model.txt", sep = "/")
write.op(as_ROI_model(milp_model), file_out, "lp_lpsolve")
```
You could also switch the solver to glpk to see if the phenomenon is associated with the solver.
You should also manually inspect the solution against the constraints to ensure that the solution is indeed feasible and one or more constraints are binding.

**Comment by dirkschumacher** [comment]
Thanks both of you. @jdb78 Can you try to construct a minimal model, that can be reproduced here? Then I can use this as a test case to further investigate and fix the potential bug.
