### ISSUE TITLE
get_solution mixing up two variables

### ISSUE THREAD

**Issue by hugolarzabal** [dirkschumacher/ompr#244]
I have noticed in a few cases where get_solution return strange values.

After investigating a little bit, I realised that it happens when two variables have somewhat similar names.

For example, I have found that in one model, `get_solution(solution, s[t,as])` returns the value of s but also the values of another variable named bus[c,cs].
It also happened in another case with variables named "t_start" and "airport_start".

My understanding is that a regex match in get_solution is looking for "s[" and also return "bus[".

**Comment by hugolarzabal** [comment]
I think that I found how to fix it.

In the function extract_solution, there is patter defined as
```
    instance_pattern <- paste0(var_name,
                               "\\[",
                               paste0(idx_pattern, collapse = ","),
                               "\\]")
```
We can force the match to be on the complete variable name and not only part of it by adding "^" at the begining of the pattern.
```
    instance_pattern <- paste0("^",
                                var_name,
                               "\\[",
                               paste0(idx_pattern, collapse = ","),
                               "\\]")
```

If it doesn't break anything else, I can make a PR with that fix.

**Comment by dirkschumacher** [comment]
Oh thanks for spotting this. Or we just use exact matching instead of a regex? `fixed=TRUE`?

**Comment by hugolarzabal** [comment]
From grep definition, I find that about fixed = TRUE:

> pattern  character string containing a regular expression (or character string for fixed = TRUE) 

My understanding is that it will look for the exact string instead of a regular expression (for example, it will try to match "\\[" instead of "[").

"^" is the simplest way to find the exact match. "^" is the regex symbol to represent the begining of the text ("$" is the end of the text).
For example, using "^a$" will do the exact match with "a".

In that case, we do not need the "$" since a variable name will always end with "]".
