### ISSUE TITLE
MIP model instead of MILP model in the MILP WHLP article

### ISSUE THREAD

**Issue by dirkdegel** [dirkschumacher/ompr#247]
Dear Dirk,

I just noticed, that in the [MILP WHLP](https://dirkschumacher.github.io/ompr/articles/milp-problem-warehouse-location.html) article the **MIP** model is described and the not the **MILP**. In the [source code](https://github.com/dirkschumacher/ompr/blob/master/vignettes/milp-problem-warehouse-location.Rmd) is the right model.

**Comment by dirkschumacher** [comment]
The website has the content of the current CRAN version. In the `dev` version of the docs this should be fixed: https://dirkschumacher.github.io/ompr/dev/articles/milp-problem-warehouse-location.html
