### ISSUE TITLE
Assigning students to courses [Docs]

### ISSUE THREAD

**Issue by alexhallam** [dirkschumacher/ompr#251]
I got a little confused with the article [here](https://dirkschumacher.github.io/ompr/articles/problem-course-assignment.html). 

I was assuming that 

```r
preferences(1)
## [1] 1 2 3
```

was ordinal where `1` what was the most preferred and `3` was the least preferred, but when I got to the end of the article the results showed 

```r
## # A tibble: 6 x 4
##     i      j    weight preferences
##   <int> <int>  <int>      <chr>      
## 1     5     1      3         2,3,1      
## 2    10     1      3         4,3,1      
## 3    15     1      3        2,4,1      
## 4    16     1      3        3,4,1      
## 5    23     1      3        2,4,1      
## 6    26     1      3        3,2,1
``` 

So student `5` choosing class `1` had weight `3` (the max weight), so even-though the preference order is `2, 3, 1` the preference -- when ranked greatest to least -- is really `1, 3, 2`. Is this correct?

**Comment by hugolarzabal** [comment]
It is explained at the start of the document.
The preferences are not the order but a system of weights or points given by the students to the courses they want to attend. 

`All students have stated individual preferences on a scale from 1 to 3, where 3 is the most favorable course.`

**Comment by alexhallam** [comment]
haha sorry, I am still not getting it. I don't think I was clear in my question. Let me try asking a different way.

Assume student `a` has preference `2,3,1`. Does `a` prefer class `2` or `1` the most?

**Comment by hugolarzabal** [comment]
It is true that it is not very clear in the example.

But since the example showthat student 5 is assigned course 1 with a weight of 3, I am pretty sure that it is his top preference.

The example also says:

> 38 students got their top preference. 2 students were assigned to their second choice and 0 students got their least preferable course
