### ISSUE TITLE
How to model cost functions?

### ISSUE THREAD

**Issue by karmaal2010** [dirkschumacher/ompr#252]
Hi, I just discovered OMPR, kudos on a great R package! I am wondering how to model cost functions (not constraints). An example would be the Economic Order Quantity, where re-ordering inventory in larger quantities is more efficient because of lower shipping and handling rates per unit, until the carrying cost of unused inventory becomes too high. Or many examples of containerization, where there are economies of scale in transporting or storing larger volumes, until the engineering costs of the massive containers becomes too high. In OMPR I see the concept of an objective function, but not the concept of a cost function, and I was wondering if there is a way to model this using the OMPR constraint concept.

**Comment by sbmack** [comment]
The general concept is volume or some other kind of discounting.  That usually requires defining a piecewise linearization of an objective function with a different decision variable for each volume/cost increment.  Without special functions built into the solver, you generally have to use binary auxiliary variables to ensure that no more than 1 volume/cost increment variable is selected for each product.  There are other complicating factors such as whether discounts apply to an entire order or just the last increment.

Any textbook on mathematical programming applications will describe the details of this class of problems.  The formulations can be modeled in ompr.  But it usually takes some skill to figure out exactly what you want.  And the recommended MILPModel function can behave in unexpected ways depending on what syntax you use.  Luckily, testing in the RStudio environment is pretty easy.

Good Luck.

**Comment by karmaal2010** [comment]
Thanks for the quick and concise response!
