### ISSUE TITLE
write.op function missing / ompr install failed

### ISSUE THREAD

**Issue by sbmack** [dirkschumacher/ompr#254]
Attempting to run this code which ran fine before:

`write.op(as_ROI_model(model), file_out, "lp_lpsolve")`

Returned this error:

```
Error in write.op(as_ROI_model(model), file_out, "lp_lpsolve") : 
  could not find function "write.op"
```
I then attempted to reinstall ompr from devtools:

`devtools::install_github("dirkschumacher/ompr")`

The install failed with these error messages:

```
Error in file.copy(lp, dirname(pkgdir), recursive = TRUE, copy.date = TRUE) : 
  (converted from warning) problem copying C:\Users\sbmac\Documents\R\win-library\3.5\00LOCK-ompr\ompr\libs\x64\ompr.dll to C:\Users\sbmac\Documents\R\win-library\3.5\ompr\libs\x64\ompr.dll: Permission denied
Execution halted
In R CMD INSTALL
Error in i.p(...) : 
  (converted from warning) installation of package ‘C:/Users/sbmac/AppData/Local/Temp/RtmpCAtI3U/file3254693d17c3/ompr_0.8.0.9000.tar.gz’ had non-zero exit status
```
Any guidance on the above?

**Comment by hugolarzabal** [comment]
did that write.op function ever exist in ompr?

It does look like `ROI_write` function from ROI.

The second part is probably a problem with package reinstallation after an R update.
