### ISSUE TITLE
Using decision variables value for data frame indexes

### ISSUE THREAD

**Issue by Blom1** [dirkschumacher/ompr#258]
Hello,

First of all, kudos for the ompr package, I really like it!

There is only one thing I can't find out. I would like to use the decision variable value in a dataframe index. 

For example, my decision variable is x_{i} which is an integer variable which implies the amount of facings product i gets in a shelf. The sales is dependent of the facings, so for the cost function I would love to use the x_{i} value to look up the corresponding amount of sales, for example in df_sales[i, x_{i}].

Is this possible in any way? For now I can only reach the x values when the problem is solved.

Thanks in advance!

**Comment by hugolarzabal** [comment]
Hello,

I think that you can solve your problem easily by using binary variables with multiple indices.

You can do the following:

> Binary decision variable (0 or 1):
> x[i, j] = # product i use facing j
>
>Constraint: Only one type of facing per product
> sum(x[i, j]) = 1
> 
> Dataframe:
> s[i,j] = # sales per product i for a number of facings j
> 
> Maximizing sales will be:
> max sum(x[i, j] * s[ i , j ])

**Comment by Blom1** [comment]
Thanks Hugo,

Indeed, I've done this in my model. However, this leads to i^(j-1) extra decision variables, which makes the model much slower.

This thread can be closed, as I assume there is no possibility to do it like I wished.

**Comment by hugolarzabal** [comment]
You are right, it is not possible to do it like you wished.
 It is not a limitation of ompr specifically but of Mixed integer linear programing as a whole.
The whole model must be designed with linear equations and inequations and s[ i , x[i] ] is clearly not linear.
