### ISSUE TITLE
nested index in 

### ISSUE THREAD

**Issue by ccshao** [dirkschumacher/ompr#260]
Is that ok to write the constraint in the nested way? A silly example likes the following, baiscally I want to set j iterates from 1 to n, and i iterates from 1 to j

```

X <- sample(100, 10)
Y <- sample(100, 10)
n <- 10

MIPModel() %>%
  add_constraint(X[i] <= Y[j], j = 1:n, i = 1:j) 

```

**Comment by hugolarzabal** [comment]
No, it doesn't work.

The right way to do it would be using a filter:

> add_constraint(X[i] <= Y[j], j = 1:n, i = 1:n, i <=j)

**Comment by ccshao** [comment]
Thanks for the solution!
