### ISSUE TITLE
Error: Unexpected operator '(' found.        

### ISSUE THREAD

**Issue by singfie** [dirkschumacher/ompr#261]
Hi, please excuse my beginner questions, but I am new to this package and encountered some errors I cannot localize or understand. I am trying to build a two-stage stochastic programming model with a recursive update. I am tryin to loop through a couple of different scenarios but cannot figure out what the problem of the core MILP implementation is. I get the error "Error: Unexpected operator '(' found. " when trying to run the model, but cannot identify any unnecessary operator in this code. Is this maybe related to the data I fed it with? Thanks a lot for the help.
`########MIP SETUP########

library(gtools)
library(ompr)
library(magrittr)
library(ompr.roi)
library(ROI.plugin.glpk)

#function to find all combinations of a certain number of contractors
solution_set<-function(nContractors){
  combinations(n=I,r=nContractors,v=seq_len(I),repeats.allowed=F)
}

# function to aggregate shortages
demandjtkS<- function(j,t,k,S) {
  if (t == 0){
    d <- 0
  }else{
    d <- demand_gen_function(516)[j,t,k]
  }
  return(d)
}

# function to aggregate failed deliveries
exp_miss <- function(S){
  return(sum(Q_IK[,S,]))
}

# first stage obective part 1
setup_costs <- function(set){
  fx <- c(rep(0, length(set)))
  for (i in (1:length(set))){
    fx[i] <- C_I[set[i]]
  }
  return(sum(fx))
}

# MAIN IMPLEMENTATION
for (no in seq(1:5)){
  
  ys <- as.matrix(solution_set(no))
  ys <- cbind(ys, matrix(0,nrow(ys),(Xi+1))) # add space for fixed cost (1 col) and overall cost for recording after loop (Xi col)
  
  for (sol in seq(1:nrow(ys))){
    # assign contract set up costs (first part of objective function)
    contractors = ys[sol,1:no]
    ys[sol,no+1] <- setup_costs(c(ys[sol,1:no]))
    # this can be used as the first part of the optimal value
    for (S in seq(1:Xi)){
      t = 1
      # MIP model building for second stage
      model <- MIPModel() %>%
        # DECISION VARIABLES
        # number of units of item k delivered to location j from contractor i under scenario Xi at time t
        add_variable(x[i, j, k, t], i = contractors, j = 1:J, k = 1:K, t = 1:TT, type = "integer", lb = 0) %>%
        
        # OBJECTIVE
        # minimize unsatisfied demand
        set_objective(sum_expr(((demandjtkS(j,k,t,S) - sum_expr(x[i, j, k, t], i = contractors) +
                                   demandjtkS(j,k,t-1,S))/demandjtkS(j,k,t,S)), j = 1:J, k=1:K, t = 1:TT), "min") %>%
        
        # CONSTRAINTS
        
        # barrier for accepting non-performance
        add_constraint(sum_expr(x[i,j,k,t], i = contractors, j = 1:J, k = 1:K) * exp_miss(S) <= TAU_Q[S], t = 1:TT)
      
      model
      result <- solve_model(model, with_ROI(solver = "glpk", verbose = TRUE))

      ys[sol,S+no+1] <- result
    }
  }
  assign(paste("records_contr_no", no, sep=""), ys)
}`

**Comment by singfie** [comment]
Also, I do not know why GitHub does not display this nicer. Thanks for the help.

**Comment by hugolarzabal** [comment]
I tried to execute your code but it is missing many things (I, J, K, TT values, TAU_Q  and demand_gen_function definitions...)

It is also quite complecated with those loops.

Could you make a simpler and reproducible example with the minimum number of variables and parameters to get the same error ?

**Comment by singfie** [comment]
@hugolarzabal I can just providing the entire script, as I cannot localize what the error is coming from to reproduce it: 

Thanks for the help again.

#clean workspace
rm(list = ls())
gc()

library(ggplot2)
library(gtools)
library(ompr)
library(magrittr)
library(ompr.roi)
library(ROI.plugin.glpk)

########SETS AND PARAMETERS#########
Xi <- 10 #set of scenarios

#######SETS#########

I <- 10     # number of contractors
J <- 7 # number of possible demand locations
K <- 2 # set of item types
TT <- 15 #set of time intervals (weeks)

n_contractors_select <- 3

#######PARAMETERS#########

#Supply#
C_I <- c(10000, 9000, 9000, 6000, 6000, 5000, 5000, 3000, 3000, 2000) #contract setup cost for contractor I

B_K <- array(matrix(data=c(rep(50,TT), rep(10, TT)), nrow = K, ncol = TT, byrow = TRUE) * 10, dim=c(K,TT,length.out=Xi)) #shortage cost of item k at time t for scenario Xi
# rows are items, cols is time, array is scenario

U_IK <-matrix(data=c(seq(10,2,length.out = I), seq(5,1,length.out = I)), nrow = K, ncol = I, byrow = TRUE) #variable cost for contractor I to send item K
# rows are item types cols are contractors

Q_IK <- array(matrix(c(.05, .05, .05, .1, .1, .1, .15, .15, .2, .2), nrow = I, ncol = Xi, byrow = T), dim = c(I, Xi, length.out = K)) 
# expected fraction of lost of misplaced items, updated each scenario
# rows are contractors, cols are scenarios, arrays are items

TAU_Q <- c(runif(Xi, min = 0, max = 0.3)) # lost or misplaced tolerance

M_IK <- array(matrix(round(c(runif(I*K*TT)*40)), nrow=I, ncol=TT), dim=c(I,TT,length.out=K)) #daily capacity of contractor i for deliver item k
# arrays are item, cols are time, rows are contractors


#Demand Parameters#
E_K <- rep(10, times = K) #expected shortages per capita of item k
V_K <- rep(1, times = K) #variance shortages per capita of item k
Pop_J <- c(100, 70, 80, 60, 20, 40, 10) #population at location J
Vul_J <- c(.1,.1,.05,.05,.2,.2,.2) #probability of disaster at location J

#Time horizon#
t <- c(seq(1,TT,1)) # time horizon

######FUNCTIONS TO GENERATE PARAMETERS UNDER EACH SCENARIO#####

demand_gen_function<-function(seed){
  
  set.seed(seed)
  
  t0 <- sample(1:TT, size = 1) #start of scenario
  t_end <- sample(t0:TT, size = 1) #end of scenario
  
  #randomly generate if event occured at each location with given location vulnerabilities (probabilities)
  event_loc <- rbinom(n = J, size = 1, prob = Vul_J)
  total_pop_impacted <- event_loc * Pop_J
  
  #for each location, each item and each time period generate demand
  D_JK_Scenario<- array(matrix(rep(0, times = TT*J*K),
                         nrow = J,
                         ncol = TT), dim=c(J,TT,length.out=K))
  # each array is one item, cols are locations, rows time steps
  for (k in seq(K)){
    each_item_time1 <- rnorm(n = TT, mean = E_K[k], sd = V_K[k])
    scenario_length <- c(rep(0, times = t0-1), rep(1, times = t_end - t0 + 1), rep(0, times = TT-t_end))
    each_item_time <- each_item_time1 * scenario_length
    for (j in seq(J)){
      #k_start = k + ((k-1)*TT)
      #k_end = k*TT
      total_demand_location_JK <- total_pop_impacted[j]*each_item_time
      counter = 1
      for (z in (1:TT)){
        D_JK_Scenario[j, z, k] <- total_demand_location_JK[counter]
        counter = counter +1
      }
    }
  }
  return(D_JK_Scenario)
}

supply_gen_function<-function(seed){
  
}

########MIP SETUP########

#function to find all combinations of a certain number of contractors
solution_set<-function(nContractors){
  combinations(n=I,r=nContractors,v=seq_len(I),repeats.allowed=F)
}

# function to aggregate shortages
demandjtkS<- function(j,t,k,S) {
  if (t == 0){
    d <- 0
  }else{
    d <- demand_gen_function(516)[j,t,k]
  }
  return(d)
}

# function to aggregate failed deliveries
exp_miss <- function(S){
  return(sum(Q_IK[,S,]))
}

# first stage obective part 1
setup_costs <- function(set){
  fx <- c(rep(0, length(set)))
  for (i in (1:length(set))){
    fx[i] <- C_I[set[i]]
  }
  return(sum(fx))
}

# MAIN IMPLEMENTATION
for (no in seq(1:5)){
  
  ys <- as.matrix(solution_set(no))
  ys <- cbind(ys, matrix(0,nrow(ys),(Xi+1))) # add space for fixed cost (1 col) and overall cost for recording after loop (Xi col)
  
  for (sol in seq(1:nrow(ys))){
    # assign contract set up costs (first part of objective function)
    contractors = ys[sol,1:no]
    ys[sol,no+1] <- setup_costs(c(ys[sol,1:no]))
    # this can be used as the first part of the optimal value
    for (S in seq(1:Xi)){
      t = 1
      # MIP model building for second stage
      model <- MIPModel() %>%
        # DECISION VARIABLES
        # number of units of item k delivered to location j from contractor i under scenario Xi at time t
        add_variable(x[i, j, k, t], i = contractors, j = 1:J, k = 1:K, t = 1:TT, type = "integer", lb = 0) %>%
        
        # OBJECTIVE
        # minimize unsatisfied demand
        set_objective(sum_expr(((demandjtkS(j,k,t,S) - sum_expr(x[i, j, k, t], i = contractors) +
                                   demandjtkS(j,k,t-1,S))/demandjtkS(j,k,t,S)), j = 1:J, k=1:K, t = 1:TT), "min") %>%
        
        # CONSTRAINTS
        
        # barrier for accepting non-performance
        add_constraint(sum_expr(x[i,j,k,t], i = contractors, j = 1:J, k = 1:K) * exp_miss(S) <= TAU_Q[S], t = 1:TT)
        
      model
      result <- solve_model(model, with_ROI(solver = "glpk", verbose = TRUE))
      # # MIP model building for second stage
      # model <- MIPModel() %>%
      #   # DECISION VARIABLES
      #   # number of units of item k delivered to location j from contractor i under scenario zeta at time t
      #   add_variable(x[i, j, k, t], i = 1:I, j = 1:J, k = 1:K, t = 1:TT, type = "integer", lb = 0) %>%
      #   # binary variable with value of 1 if contractor i is selceted or a 0 if not selected
      #   add_variable(y[i], i = 1:I, type = "binary") %>%
      # 
      #   # OBJECTIVE
      #   # minimize unsatisfied demand # WORK HERE
      #   set_objective((demandjtkS(j,k,t,S) - sum_expr(x[i, j, k], i = 1:I, j = 1:J, k = 1:K) +
      #                 demandjtkS(j,k,t-1,S))/demandjtkS(j,k,t,S), "min") %>%
      # 
      #   # CONSTRAINTS
      # 
      #   # barrier for accepting non-performance
      #   add_constraint(sum_expr(x[i,j,k,t], i = 1:I, j = 1:J, k = 1:K) * exp_miss(S) <= TAU_Q[S])
      # model
      # 
      # result <- solve_model(model, with_ROI(solver = "glpk", verbose = TRUE))
      ys[sol,S+no+1] <- result
    }
  }
  assign(paste("records_contr_no", no, sep=""), ys)
}

**Comment by hugolarzabal** [comment]
It would be better to avoid cutting your code in small parts with titles in between. When I copy paste all your post in R, I have to eliminate all those titles manually.

I think that your error is here: `demandjtkS(j,k,t-1,S)`
This function doesn't handle well t = 1
 ```
demandjtkS(1,1,0,1)
numeric(0)
```
I guess that the error come from the fact that sum_expr is expecting a value and encounter the ( of numeric(0) instead.

one way to solve that problem is to iterate t from 2 to TT in set_objective
```
    set_objective(sum_expr(((demandjtkS(j,k,t,S) - sum_expr(x[i, j, k, t], i = contractors) +
                               demandjtkS(j,k,t-1,S))/demandjtkS(j,k,t,S)), j = 1:J, k=1:K, t = 2:TT), "min")
```

**Comment by singfie** [comment]
Thank you, that was helpful. There were another few issues, so I had to rebuild a few parts. Thanks again!
