### ISSUE TITLE
Stopping time criteria

### ISSUE THREAD

**Issue by Blom1** [dirkschumacher/ompr#262]
Hello all,

I can't find it in the documentation, but is it possible to add a stopping time to the MIPModel? To stop the model after for example an hour and get the last solution.

Many other linear optimization problems does have this function and it would be nice to have!

With kind regards,

Bjorn

**Comment by hugolarzabal** [comment]
Yes, you can actually pass different arguments to be used by the solver in the `with_ROI` function.

As an example, you can call cbc solver that way:
`solve_model(model, with_ROI("cbc", sec=600, ratio = 0.001, allow = 15))`

For cbc:
- sec is the maximum solving time in seconds
- ratio is the proportional gap
- allow is the absolute gap

Those arguments depend on the solver and the R library associated to it.
