### ISSUE TITLE
Formulating maxmin / equal allocation problem

### ISSUE THREAD

**Issue by Zuumx** [dirkschumacher/ompr#264]
Hello and thank you for the great package.

I'm trying to formulate the following MIPModel:

I have 8 products p, 2 groups of customers g and 4 weeks w. I want to allocate one product for each group for each week. Products 1:4 are preferred by group 1 and products 5:8 are preferred by group 2. Preferences are stored in binary matrix preferred[p, g].

Each product has a predicted sales amount in a vector total_sales.

```
allocator <- MIPModel() %>%  

# binary variables if product p is chosen for group g in week w
add_variable(y[p, g, w], p = 1:8, g = 1:2, w = 1:4, type = "binary") %>%   

# each product is chosen only once
add_constraint(sum_expr(y[p, g, w], g = 1:2, w = 1:4) <= 1, p = 1:8) %>%   

# each group has one product for every week
add_constraint(sum_expr(y[p, g, w], p = 1:8) == 1, g = 1:2, w = 1:4 %>%

# group 1 prefers products 1:4, group 2 5:8
add_constraint(sum_expr(y[p, g, w], w = 1:4) <= preferred[p, g], p = 1:8, g = 1:2)
```
Model seems to be working and is able to allocate the products for groups and weeks. However, I would like to have four balanced weeks in regard to total_sales. I've been thinking about either maximizing the lowest sales amount for a single week (maxmin) or minimizing the differences between all of the 4 weeks but have been unable to formulate the objective function. 

Total sales for a week: 
```
y[p, g, w] * total_sales[p], p = 1:8, g = 1:2
````

Any help would be appreciated!

**Comment by Zuumx** [comment]
Ok so I found out that minimizing the sum of absolute differences between weeks can be formulated like this:

```
add_variable(u[w1, w2], w1 = 1:4, w2 = 1:4, w1 < w2) %>%
add_constraint(u[w1, w2] >= sum_expr(y[p, g, w1] * total_sales[p] 
- y[p, g, w2] * total_sales[p], p = 1:8, g = 1:2), w1 = 1:4, w2 = 1:4, w1 < w2) %>% 
add_constraint(-u[w1, w2] <= sum_expr(y[p, g, w1] * testtotal_sales[p] 
- y[p, g, w2] * testtotal_sales[p], p = 1:8, g = 1:2), w1 = 1:4, w2 = 1:4, w1 < w2) %>% 
set_objective(sum_expr(u[w1, w2], w1 = 1:4, w2 = 1:4, w1 < w2), "min")
```
where u is a helper variable and w1 and w2 are used to compare weeks.

Also maximizing the lowest week seems to work like this:

```
add_variable(u) %>%
  set_objective(u, "max") %>% 
  add_constraint(u <= sum_expr(y[p, g, w] * testtotal_sales[p], p = 1:8, g = 1:2), w = 1:4)
```

Maxmin would probably work better for my problem. However, when using either of these approaches to my real problem with p = 1:980, g = 1:4, w = 1:6 the solver seems to get stuck. I'm using "glpk". Is there anything I could do to improve my code to get the solution?

**Comment by dirkschumacher** [comment]
Yeah the model gets bigger and potentially harder to solve. The first thing you can do is to try the glpk option `presolve=TRUE` which enables some presolve options that can reduce your model before solving.

The second thing is to try another solver: CBC is an option or if you are an academic, you can try CPLEX or Gurobi.

I assume the issue can be closed now.
