### ISSUE TITLE
Matrix Constraints

### ISSUE THREAD

**Issue by Christof23** [dirkschumacher/ompr#268]
In the documentation it is shown how to express the following matrix in a constraint:

x[1, 1]
x[1, 1] + x[1, 2]
x[1, 1] + x[1, 2] + x[1, 3]

by x[1, colwise(1, 1:2, 1:3)].

I'd like to be able similarly to express, say 

x[1, 1] + x[1, 2]
x[2, 1] 

but am running into problems with duplicate indexes with  i = colwise(1:2,1), j = colwise(1,1:2). Any thoughts welcome!

**Comment by hugolarzabal** [comment]
I guess something like that should work:
`sum_expr(x[i, j], j = colwise(1:2, 1)) <= k,  i = 1:2)`

You usually only need to apply colwise to one variable, the other being iterated normally.

**Comment by dirkschumacher** [comment]
I will close this, as it seems solved/not relevant anymore. Feel free to post your questions in the discussions.
