### ISSUE TITLE
Constraint not well formed

### ISSUE THREAD

**Issue by endelk** [dirkschumacher/ompr#269]
Hi,

I'm struggling to set this model properly. Sorry if I'm missing the basics.

model <- MIPModel() %>%
  add_variable(x[i, j], i = 1:n, j = 1:m, type = "binary") %>%
  set_objective(sum_expr(A[i,j] * x[i,j], i = 1:n, j = 1:m), "max") %>%
  add_constraint(sum_expr(B[i,j]* x[i,j] <= D, i = 1:n, j = 1:m))

Error: constraint not well formed. Must be a linear (in)equality.

I tried also MILP Model but then:

model <- MILPModel() %>%
  add_variable(x[i, j], i = 1:n, j = 1:m, type = "binary") %>%
  set_objective(sum_expr(A[i,j] * x[i,j], i = 1:n, j = 1:m), "max") %>%
  add_constraint(sum_expr(B[i,j]* x[i,j] <= budget, i = 1:n, j = 1:m))

Error in as.data.frame.default(x[[i]], optional = TRUE) : 
  cannot coerce class ‘structure("LinearVariableCollection", package = "ompr")’ to a data.frame

I tried also to creat vectors for the constants, like this:

vect_A <- A[1:n,1:m] %>% unlist()
vect_B <- B[1:n,1:m] %>% unlist()

model <- MILPModel() %>%
  add_variable(x[i, j], i = 1:n, j = 1:m, type = "binary") %>%
  set_objective(sum_expr(vect_A * x[i,j], i = 1:n, j = 1:m), "max") %>%
  add_constraint(sum_expr(vect_B* x[i,j] <= budget, i = 1:n, j = 1:m))

And then I got back:
Error: constraint not well formed. Must be a linear (in)equality.

Thanks for any help!

Endel

**Comment by hugolarzabal** [comment]
Hello,
You are not closing the parentesis in the right place:
`add_constraint(sum_expr(B[i,j]* x[i,j] <= D, i = 1:n, j = 1:m))`

The `<= ` cannot be inside the sum_expr, it doesn't make sense.

I guess you mean 
`add_constraint(sum_expr(B[i,j]* x[i,j],  i = 1:n, j = 1:m) <= D)`
or
`add_constraint(sum_expr(B[i,j]* x[i,j],  i = 1:n) <= D, j = 1:m)`

**Comment by endelk** [comment]
Hi hugolarzabal

Yeah, I realized this beforehand, however it still does not work. Thanks anyways.

Please find the current:

model <- MIPModel() %>%
  add_variable(x[i, j], i = 1:n, j = 1:m, type = "integer", lb = 0, ub = 1) %>%
  set_objective(sum_expr(A[i,j] * x[i,j], i = 1:n, j = 1:m), "max") %>%
  add_constraint(sum_expr(B[i,j] * x[i,j], i = 1:n, j = 1:m), "<=", budget)

I am still getting. Error: constraint not well formed. Must be a linear (in)equality.

**Comment by hugolarzabal** [comment]
`add_constraint(sum_expr(B[i,j]* x[i,j], i = 1:n, j = 1:m) <= budget)`

**Comment by endelk** [comment]
Thanks you!
