### ISSUE TITLE
Can't get map_data in The Minimum Graph Coloring Problem

### ISSUE THREAD

**Issue by wberset** [dirkschumacher/ompr#273]
Hi Dirk,

First, thanks very much for creating and maintaining  this app. It is very nice and useful.

The problem I am having is when I try to get the map_data after:
library(rgeos)
library(rgdal)
library(maptools)
library(dplyr)
 and 
map_data <- rgdal::readOGR("https://raw.githubusercontent.com/datasets/geo-boundaries-us-110m/84e946f6b1de01e2642bcdb17d5b697acb6b48c4/json/ne_110m_admin_1_states_provinces_shp_scale_rank.geojson", "OGRGeoJSON")

I get the following error in R:

"Error in ogrInfo(dsn = dsn, layer = layer, encoding = encoding, use_iconv = use_iconv,  : 
  Cannot open layer"

Do I need to get another package?

Thanks for your help.

Wes

**Comment by dirkschumacher** [comment]
Thanks. Will look into it.

**Comment by hugolarzabal** [comment]
I don't know much about the readOGR function but its documentation says that the second argument (layer) is optional. If it is not specified, it will guess the right value.

If you remove this second argument "OGRGeoJSON", the function guessa value for layer and works fine.

The problem may be related with some update of the library or the page from where it reads the data.

**Comment by wberset** [comment]
Dirk,
Thanks. I remove this second argument "OGRGeoJSON" and was able to get the data.

Wes
