### ISSUE TITLE
Error in modOut[[d1]][[d2]][[d3]][["ModelName"]] : subscript out of bounds

### ISSUE THREAD

**Issue by zoeyzuo20** [dirkschumacher/ompr#274]
I am working on a SDM model with one environmental factor and Present-Only data based on the example of BIOMOD2 Simple_species_modelling.pdf

```{r}
myRespName <- 'Aedes_aegypti'
a<-Aedes_aegypti_CoordinateswithXY[,myRespName]
myResp <- as.numeric(unlist(a))
myRespXY <- Aedes_aegypti_CoordinateswithXY[,c("POINT_X","POINT_Y")]

myExpl = stack( ("C:/Users/jiahui.zuo/Google Drive/ESI - EENM input datasets - Colombia/environmental/CHELSA/CHELSA_Annual_values/CHELSA_annual_mean_temp_Colombia.tif")) 

```

```{r}
myBiomodData <- BIOMOD_FormatingData(resp.var = myResp, 
                                     expl.var = myExpl, 
                                     resp.xy = myRespXY, 
                                     resp.name = myRespName)

```
```{r}
myBiomodData
```
```{r}

#something is wrong is this graph

plot(myBiomodData)

```

```{r}
myBiomodOption <- BIOMOD_ModelingOptions()

#states<-as.data.frame(ModelName[,c(4)])

myBiomodModelOut <- BIOMOD_Modeling( 

  myBiomodData, 
  models = c('SRE','CTA','RF','MARS','FDA'), 
  models.options = myBiomodOption, 
  NbRunEval=3, 
  DataSplit=80, 
  Prevalence=0.5, 
  VarImport=3,
  models.eval.meth = c('TSS','ROC'),
  SaveObj = TRUE,
  rescal.all.models = TRUE,
  do.full.models = FALSE,
  modeling.id = paste(myRespName,"FirstModeling",sep=""))


myBiomodModelOut 
```

**Error in modOut[[d1]][[d2]][[d3]][["ModelName"]] : subscript out of bounds******

Can someone tell me what should I do to fix this? I checked the previous record just saying that because this is a present - only data. :(
Someone post a solution :  
myBiomodOption <- BIOMOD_ModelingOptions(
MAXENT = list( path_to_maxent.jar = getwd())
)
But it's not working for my case, this code will only make mine back to system files GuloGulo

**Comment by dirkschumacher** [comment]
Are you sure this is the right repository? What is BIOMOD?

**Comment by zoeyzuo20** [comment]
> Are you sure this is the right repository? What is BIOMOD?

https://cran.r-project.org/web/packages/biomod2/index.html
BIOMOD2

**Comment by dirkschumacher** [comment]
What does it have to do with `ompr`?

**Comment by zoeyzuo20** [comment]
> What does it have to do with `ompr`?

Sorry about that
I just found out I posted it in the wrong session
