### ISSUE TITLE
 There are variables in your environment that interfere with your defined model ..

### ISSUE THREAD

**Issue by wberset** [dirkschumacher/ompr#275]
Hi Dirk,

I am trying to reproduce and run the "Minimum Graph Coloring Problem". I can get the map_data ...., but when I run the model (MIPModel()) I get 50, or more warnings. The warning messages are all:

"There are variables in your environment that interfere with your defined model variables: x,y. This can lead to unexpected behaviour."

Although the model "gets created".

When I go to run the model:
result <- solve_model(model, with_ROI("glpk", presolve = TRUE, verbose = TRUE))

I get the message:

"Error in acc[[key]] : no such index at level 1" and

result
Status: optimal
Objective value: 118

I am getting exactly the same thing when I try to reproduce the:
1) The Traveling Salesmen Problem and
2) The Multiple Traveling Salesmen Problem

Thanks for your help with this.

Wes

**Comment by dirkschumacher** [comment]
🤔

**Comment by prof-anderson** [comment]
I've had similar issues with conflicts between variable names inside the ompr model and with variables in the R environment. This can happen easily with short variable names like x or y.  As a workaround, I've been adding a prefix of V for variables in ompr to distinguish them.

**Comment by wberset** [comment]
Tim,
Thanks a bunch. I did this and it worked!! This not a bad idea anyway.

Hopefully I can be of help some time.

Wes
