### ISSUE TITLE
Way to control constraints and convergence criteria

### ISSUE THREAD

**Issue by minmat84** [dirkschumacher/ompr#277]
First of all, thanks for the great work! the ompr package has been very useful for me.

The background is as follows: I am working on a linear optimization problem, in which the model should assign quantities that satisfy a bunch of constraints, especially that they are (if not 0) above a minimum quantity, say x_min.
I modeled the x_min constraint by defining binary variables and using the big M trick. Depending on the parameter constellations there are situations that I need to set a very big M so that the problem converges (at least within a decent time). For very large M however the problem converges „too“ fast, that ist the x_min constraint is obviously violated, although it would be feasible.

Here is a small and stylized version of my MIP model, while the orginal problem is a bit more complex:

`

> 
>  library(magrittr)
>   library(dplyr)
>   library(ompr)
>   library(ROI)
>   library(Rglpk)
>   library(ROI.plugin.glpk)
>   library(ompr.roi)
> 
> fun <- function(big_M){
> set.seed(123)
> n_h <- 10
> n_l <- 10
> capacities_1 <- matrix(sample(0:1000, n_l*n_h/2, replace=TRUE),ncol =n_h/2,nrow=n_l)
> capacities_2 <- matrix(sample(0:100, n_l*n_h/2, replace=TRUE),ncol =n_h/2,nrow=n_l)
> capacities <- cbind(capacities_1,capacities_2)
> demand <- 0.9*matrix(apply(capacities,1,sum))
> x_min <- 50
> plant_capacities <- 1.1*matrix(apply(capacities,2,sum))
> u <- matrix(sample(1:100, n_l*n_h, replace=TRUE),ncol =n_h,nrow=n_l)*sign(capacities)
> model <-
>   MIPModel() %>%>    
>   add_variable(b[l,h], l = 1:n_l, h= 1:n_h, type = "binary") %>%
>   add_variable(x[l,h], l = 1:n_l, h = 1:n_h, type = "continuous",lb =0,ub=1000) %>%
>   add_constraint(x_min*b[l,h] <= x[l,h], l=1:n_l, h=1:n_h ) %>%
>   add_constraint( x[l,h] <= big_M * b[l,h], l=1:n_l, h=1:n_h ) %>%
>   set_objective(sum_expr(u[l,h] * x[l,h], l = 1:n_l, h = 1:n_h)) %>%
>   add_constraint(sum_expr(x[l,h], l = 1:n_l) <= plant_capacities[h], h = 1:n_h ) %>%
>   add_constraint(x[l,h] <= capacities[l,h] , l = 1:n_l, h = 1:n_h ) %>%
>   add_constraint(sum_expr(x[l,h], h = 1:n_h) ==demand[l], l = 1:n_l ) %>%
>   solve_model(with_ROI("glpk",verbose=TRUE,tm_limit = 1000 * 120))
> 
> result_table <- get_solution(model, x[l,h])
> b_table <-get_solution(model,b[l,h])
> x_table <- get_solution(model, x[l,h])
>
> violation <- x_table %>% filter(between(value,1,49))
> violation
> }
> 
> 
> 
> > fun(100)
> <SOLVER MSG> ----
> GLPK Simplex Optimizer, v4.47
> 320 rows, 200 columns, 700 non-zeros
>       0: obj = 0.000000000e+000 infeas = 2.555e+004 (10)
>     200: obj = 3.614580000e+005 infeas = 1.836e+004 (10)
> PROBLEM HAS NO FEASIBLE SOLUTION
> GLPK Integer Optimizer, v4.47
> 320 rows, 200 columns, 700 non-zeros
> 100 integer variables, all of which are binary
> glp_intopt: optimal basis to initial LP relaxation not provided
> <!SOLVER MSG> ----
> [1] variable l h value
> <0 Zeilen> (oder row.names mit Länge 0)
> 
> 
> > fun(100000)
> <SOLVER MSG> ----
> GLPK Simplex Optimizer, v4.47
> 320 rows, 200 columns, 700 non-zeros
>       0: obj = 0.000000000e+000 infeas = 2.555e+004 (10)
> * 155: obj = 1.350009700e+006 infeas = 0.000e+000 (0)
> * 212: obj = 1.422776500e+006 infeas = 0.000e+000 (0)
> OPTIMAL SOLUTION FOUND
> GLPK Integer Optimizer, v4.47
> 320 rows, 200 columns, 700 non-zeros
> 100 integer variables, all of which are binary
> Integer optimization begins...
> + 212: mip = not found yet <= +inf (1; 0)
> + 314: >>>>> 1.387478500e+006 <= 1.388678500e+006 < 0.1% (29; 0)
> + 315: >>>>> 1.388678500e+006 <= 1.388678500e+006 0.0% (10; 19)
> + 315: mip = 1.388678500e+006 <= tree is empty 0.0% (0; 57)
> INTEGER OPTIMAL SOLUTION FOUND
> <!SOLVER MSG> ----
> [1] variable l h value
> <0 Zeilen> (oder row.names mit Länge 0)
> 
> 
> > fun(100000000000000)
> <SOLVER MSG> ----
> GLPK Simplex Optimizer, v4.47
> 320 rows, 200 columns, 700 non-zeros
>       0: obj = 0.000000000e+000 infeas = 2.555e+004 (10)
> * 110: obj = 1.350009700e+006 infeas = 0.000e+000 (0)
> * 200: obj = 1.422776500e+006 infeas = 0.000e+000 (0)
> OPTIMAL SOLUTION FOUND
> GLPK Integer Optimizer, v4.47
> 320 rows, 200 columns, 700 non-zeros
> 100 integer variables, all of which are binary
> Integer optimization begins...
> + 200: mip = not found yet <= +inf (1; 0)
> + 237: >>>>> 1.388752900e+006 <= 1.388752900e+006 0.0% (1; 0)
> + 237: mip = 1.388752900e+006 <= tree is empty 0.0% (0; 1)
> INTEGER OPTIMAL SOLUTION FOUND
> <!SOLVER MSG> ----
>   variable l h value
> 1 x 4 5 28.0
> 2 x 5 7 41.6 

`
So, for a small M (fun(100)) the solver finds no feasible solution, for a medium M (fun(1000)) it's all fine and for the very big M fun(100000000000000) it accepts x below x_min as solution (28 and 41.6), although a quantity of at least 50 each would be feasible.

It seems to be related to some convergance criterium that makes the solver accept a solution as being close enough to constrained optimality. But I am struggling to understand which precision is acceptabe to the solver. Also I wonder if there is a way that I can control directly the optimality criterium. Moreover, is there a way to check each constraint in the model output? Would be helpful to see which constraints are binding, and which not.

Thank and best
Matthias

**Comment by hugolarzabal** [comment]
Hello,

Your big M is way too big.

Solvers have a precision limit on numbers that allow then to consider as equals 2 values that are almost equal.
Usually those precisions are between 10^-6 and 10^-9

Knowing that, the problem you have is simple:

- Let's say that the precision of glpk is 10^-6.
- In `add_constraint( x[l,h] <= big_M * b[l,h], l=1:n_l, h=1:n_h )`
- b[l,h] can take the value 10^-7 which will be considered equal to 0 by glpk
- So the constaint becomes `x[l,h] <= 10000000` which doesn't restrain x at all.

When your big M is 100 I would guess that the solution become infeasible because your big M constraints becomes `x[l,h] <= 100` and it is impossible to supply all the demands with all x being less than 100.

As a general rule, big M should be as small as possible while being superior to the highest possible value of x.
You can find more informations about the problems that can be created by big M here:
[](http://www.thequestforoptimality.com/bigm-dual/ )

**Comment by minmat84** [comment]
Thanks a lot for your answer and your suggestion regarding the magnitude of the big M. I think the link to more informations on that got lost in your comment. 

I understand that the last example's M is way too big in this extreme example. The issue is that in my orginal (more complex) problem I have the same problem with way lower (and less obviously absurd) magnitudes of M. That is why I would like to understand what is accepted as close enough to 0 by ompr/glpk. 

Maybe this purely a glpk related question and not the right place to ask here, but : is there a way to gain control over the precision of the solver? I could not find information on that in the ompr or glpk documentation. I know from other optimaziation tools (e.g. matlab) that one can overrule the default precision with a custom value.

**Comment by hugolarzabal** [comment]
I edited my previous post to correct the link.

The precision is entirely a parameter of the solver.
You can pass parameters to the solver by adding it as argument in the with_ROI function:
`solve_model(model, with_ROI("glpk", param1=5, param2 = 0.01))`
while changing  param1, param2 with the names of the parameters in the solver manual.

I found a link with glpk parameters:
[http://www.maximalsoftware.com/solvopt/optglpk.html](http://www.maximalsoftware.com/solvopt/optglpk.html)

I think the parameter you are looking for is "Integral feasible tolerance" which is named "TolInt" for the solver.
You can try:
`solve_model(model, with_ROI("glpk", TolInt=10^(-8))`

Thought, it is still probably a bad idea to have really big big M (the link that now works explain why).
If you have really high values in the model, you should consider changing the unit to express them in thousands or millions.
