### ISSUE TITLE
user defined functions in expressions?

### ISSUE THREAD

**Issue by dan9401** [dirkschumacher/ompr#278]
I'm wondering is it possible to use functions in the expressions, this is a minimum example, my real problem is a little more complicated than this:

```
n = 3
V = 1:n
U = function(i) {
    if (V[i] < P[i]) {
        u = P[i] - V[i]
    } else {
        u = V[i] - P[i]
    }
    u
}

result <- MIPModel() %>%
  add_variable(Pi[i], i = 1:n, type = "continuous", lb = 0) %>%
  set_objective(sum_expr(U(i), i = 1:n), "max")
```

Is it possible to do something like this? My real function U is also a little more complicated.

**Comment by dirkschumacher** [comment]
In General this type of Control Flow is not possible. However you can model certain types of if/else conditions with binary variables. 

Maybe search for “if else binary variables integer programming”. 

I am not at a computer so I can’t give you a concrete example for your case, but it is possible.
