### ISSUE TITLE
Error in allf[[1]] : subscript out of bounds

### ISSUE THREAD

**Issue by lorenrv** [dirkschumacher/ompr#280]
This is my code:
ggsurvplot(fit, wilt, pval=TRUE, facet.by="sym")

it gives me error only when trying to use facet. I also tried ggsurvplot_facet and it gave me the same error. I'm assuming it might be something in my data frame? Help

**Comment by dirkschumacher** [comment]
I think this is the wrong repository. Good luck though. Maybe someone at stackoverflow can help?
