### ISSUE TITLE
add_constraint: function to take up the entire variable

### ISSUE THREAD

**Issue by giacfalk** [dirkschumacher/ompr#282]
Hi, I am trying to set up the following problem:

v < 1:10
result <- MILPModel() %>%
  add_variable(x[i], i = 1:v, type = "binary") %>%
  set_objective(sum_expr(x[i], i = 1:v), sense = "min")  %>%
  add_constraint(traveltime(x) <= 60) %>%
  solve_model(with_ROI(solver = "glpk")) 

Here, _traveltime_ is a function which takes an entire vector as the input, rather than a single value (such as stats::sd). Thus, I would like the constraint to be **global** for the variable x, rather than discrete for each of its values. 

How can I rewrite this?

**Comment by hugolarzabal** [comment]
Hi,
In linear optimization, every constraint have to be linear.
if your function traveltime linear, you should express it in the constraint with a sum_expr.

If it is not linear, then there are some tricks to transform it in a linear form with several constraints but I cannot help you without knowing what your function does.
