### ISSUE TITLE
Issues with constraints

### ISSUE THREAD

**Issue by bsci-mit-mm** [dirkschumacher/ompr#284]
Optimization/R/OMPR newbie here...

**Background**
I'm trying to allocate product between two storage locations based on storage cost, such that the total qty of products equals given constant demand (governed by optimization equation below).

minimize: 
![image](https://user-images.githubusercontent.com/55604635/66157174-3294c380-e5f1-11e9-8709-e517f3cc8da8.png)
subject to:
![image](https://user-images.githubusercontent.com/55604635/66157755-74723980-e5f2-11e9-937f-c237060591ce.png)

**Question 1**
I noticed that when I try to run the below code with MILP, one of the last two constraints in the model is never met. ie. max_c = 120, but the optimization would 'solve' and give an answer where the corresponding sum = 140. 
However, when I switch to MIP, the model works fine.... is this a bug or am I just using the functions incorrectly?

**Question 2**
Then when I try to change the objective function to the following by adding cost for transportation

![image](https://user-images.githubusercontent.com/55604635/66157637-3412bb80-e5f2-11e9-8d79-94c22a4aad86.png)

and the objective function part of the model to:

`
set_objective(r_c * sum_expr(product$space[i]*x[i,1], i = 1:n) + r_w * sum_expr(product$space[i]*x[i,2], i = 1:n) + f_l * sum_expr(x[i,2], i = 1:n), "min") %>%`

One of my variables always comes back negative, even though I have explicitly set all variables to be positive. Any ideas on what I'm doing wrong here?

```
    # all variables need to be positive
  add_constraint(x[i,1] >= 0, i=1:n) %>%
  add_constraint(x[i,2] >= 0, i=1:n) %>%
```

**

Code
```
# n represents no. of distinct UPNs
n <- 10
# m represents no. of warehouses
m <- 2

# storage rate of central and warehouse
r_c = 100
r_w = 30

# max storage space for central and warehouse
max_c = 150
max_w = 120

model <- MIPModel() %>%
  # qty of product i allocated to location l
  add_variable(x[i, l], i=1:n, l=1:m, type="continuous") %>%
  
  # minimize total cost
  set_objective(r_c * sum_expr(product$space[i]*x[i,1], i = 1:n) + r_w * sum_expr(product$space[i]*x[i,2], i = 1:n), "min") %>%
  
  # need at least one product of i in location l = 1
  add_constraint(x[i,1] >= 1, i=1:n) %>%
  add_constraint(x[i,1] + x[i,2] >= product$demand[i]/20, i=1:n) %>%
  
    # all variables need to be positive
  add_constraint(x[i,1] >= 0, i=1:n) %>%
  add_constraint(x[i,2] >= 0, i=1:n) %>%
  
  # max central and warehouse storage area constraint
  add_constraint(sum_expr(product$space[i]*x[i,1], i = 1:n) <= max_c) %>%
  add_constraint(sum_expr(product$space[i]*x[i,2], i = 1:n) <= max_w)
```

**Comment by bsci-mit-mm** [comment]
Ok, so I changed from using GLPK to Symphony and it seems to have solved the issue for Q2... *scratches head*

**Comment by dirkschumacher** [comment]
Thanks!
Question 1: might be a bug.
Question 2: Very strange. Would you mind testing your model with [rmpk](https://github.com/dirkschumacher/rmpk)? It will probably be the next major version of ompr and it would be a good way to check if there is a bug in the modelling code or somewhere in ROI.

**Comment by dirkschumacher** [comment]
I rewrote the `MIPModel`, so this problem might have gone away. I cannot reproduce the code above as the `product` variable is missing. If the problem still persists, feel free to reopen. Thanks!

``` r
library(ompr)
library(ompr.roi)
library(ROI.plugin.glpk)
# n represents no. of distinct UPNs
n <- 10
# m represents no. of warehouses
m <- 2

# storage rate of central and warehouse
r_c = 100
r_w = 30

# max storage space for central and warehouse
max_c = 150
max_w = 120

model <- MIPModel() |>
  # qty of product i allocated to location l
  add_variable(x[i, l], i=1:n, l=1:m, type="continuous") |>
  
  # minimize total cost
  set_objective(r_c * sum_expr(1*x[i,1], i = 1:n) + r_w * sum_expr(1*x[i,2], i = 1:n), "min") |>
  
  # need at least one product of i in location l = 1
  add_constraint(x[i,1] >= 1, i=1:n) |>
  add_constraint(x[i,1] + x[i,2] >= 1/20, i=1:n) |>
  
  # all variables need to be positive
  add_constraint(x[i,1] >= 0, i=1:n) |>
  add_constraint(x[i,2] >= 0, i=1:n) |>
  
  # max central and warehouse storage area constraint
  add_constraint(sum_expr(1*x[i,1], i = 1:n) <= max_c) |>
  add_constraint(sum_expr(1*x[i,2], i = 1:n) <= max_w)
sol <- solve_model(model, with_ROI("glpk"))
get_solution(sol, x[i, l])
#>    variable  i l value
#> 1         x  1 1     1
#> 2         x  1 2     0
#> 3         x  2 1     1
#> 4         x  2 2     0
#> 5         x  3 1     1
#> 6         x  3 2     0
#> 7         x  4 1     1
#> 8         x  4 2     0
#> 9         x  5 1     1
#> 10        x  5 2     0
#> 11        x  6 1     1
#> 12        x  6 2     0
#> 13        x  7 1     1
#> 14        x  7 2     0
#> 15        x  8 1     1
#> 16        x  8 2     0
#> 17        x  9 1     1
#> 18        x  9 2     0
#> 19        x 10 1     1
#> 20        x 10 2     0
```

<sup>Created on 2022-01-10 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
