### ISSUE TITLE
Problem with variables / specification

### ISSUE THREAD

**Issue by chris13337** [dirkschumacher/ompr#285]
Hello,
I know this is maybe not the right place to ask but since I don't find any other help with ompr package I hope to get some help here. I am trying to convert a Julia-code (3 years old) into R code with the help of your package. 

I have this code:
 ```
model <- MIPModel()%>%
# Variable for skaters in lineup.
add_variable(skaters_lineup[i],i=1:num_skaters,type = "binary")%>%
# Variable for goalie in lineup.
add_variable(goalies_lineup[i],i=1:num_goalies,type = "binary")%>%
# One goalie constraint
add_constraint(sum_expr(goalies_lineup[i], i=1:num_goalies) == 1) %>%
# Eight Skaters constraint
add_constraint(sum_expr(skaters_lineup[i], i=1:num_skaters) == 8)%>%
# Financial Constraint
add_constraint(sum_expr(skaters$Salary[i]*skaters_lineup[i], i=1:num_skaters) + sum_expr(goalies$Salary[i]*goalies_lineup[i], i=1:num_goalies) <= 50000)%>%

set_objective(sum_expr(skaters$Proj[i]*skaters_lineup[i], i=1:num_skaters) + sum_expr(goalies$Proj[i]*goalies_lineup[i], i=1:num_goalies),"max") %>%
  
solve_model(with_ROI(solver = "glpk"))
get_solution(model, skaters_lineup)
get_solution(model, goalies_lineup)
```

I get the error code: Error: Either variable is not part of the model or you have to specify the indexes.

I tried to find the problem but I wasnt able to, maybe i have a typo but I checked this too. I would really appreciate your help,
Kind regards,
Christian Schumacher

**Comment by chris13337** [comment]
after changing something i get to this: 
solve_model(with_ROI(solver = "glpk"))%>%
get_solution(skaters_lineups[i])%>%
get_solution(goalies_lineups[i])

Error in UseMethod("get_solution_") : 
  no applicable method for 'get_solution_' applied to an object of class "data.frame"

**Comment by chris13337** [comment]
nvm figured it out

**Comment by BusraTunc50** [comment]
Hello @chris13337, 
I have the same error message for my code: 

Error in UseMethod("get_solution_") : 
  no applicable method for 'get_solution_' applied to an object of class "data.frame"

Could you please explain, how did you solve the problem?
Here is my code: 

`#indices:

#i: station where pickup occurs - 1:3
#j: station where delviery occurs - 1:3
#t: sequence of the actions - 1:3

#decision variables:

#y1_i_t: number of bikes pickedup from station i, sequence t
#y2_i_t: number of bikes delivered to station i, sequence t 
#x_i_j_t: binary variable, if the pickup is occured from station i and delivered to station j at sequence t 
#h: cost of total repositioning 
#H: cost of maximum repositioning 

#parameters:

#s0_i : initial inventory of station i
s0 <- c(8,2,15)
#s1_i: min inventory target level of station i
s1 <- c(3,4,5)
#s2_i: max inventory target level of station i 
s2 <- c(7,11,12)
#Q: capacity of the vehicle 
Q <- 99999
#c_i: capacity of the station i 
C <- c(9,13,16)
#q0: initial inventory of the vehicle
q0 <- 4
#d0_i_j: fixed cost of repositioning from station i to j 
d0 <- rbind(c(1:3),c(4:6),c(7:9))
#d1: handling cost of pickup
d1 <- 1
#d2: handling cost of delivery
d2 <- 1


MILPModel() %>%
  
  add_variable(x[i, j,t], i = 1:3, j=1:3, t = 1:10, type = "binary") %>%
  add_variable(y1[i, t], i = 1:3, t = 1:10, type = "integer") %>%
  add_variable(y2[i, t], i = 1:3, t = 1:10, type = "integer") %>%
  
  set_objective(sum_expr(as.numeric(d0[i,j])*x[i, j,t] , i=1:3, j=1:3, t=1:10) + sum_expr(d1*y1[i,t] +d2*y2[i, t], i=1:3, t=1:10), "min") %>%
  
  add_constraint(s0[i] + sum_expr(y1[i, t] - y2[i, t], t=1:10) >= s1[i], i = 1:3) %>%
  add_constraint(s0[i] + sum_expr(y1[i, t] - y2[i, t], t=1:10) <= s2[i], i = 1:3) %>%
  add_constraint(sum_expr(x[i, j,1], i = 1:3, j=1:3) <= 1) %>%
  add_constraint(sum_expr(x[i, j,t], j=1:3) <=sum_expr(x[j, i,t-1], j=1:3), i =1:3,t=2:10 ) %>%
  add_constraint(sum_expr(x[i, i,t], i=1:3,t=1:10)==0 ) %>%
  add_constraint(y1[i, t] <= Q * sum_expr(x[i, j,t], j=1:3), i=1:3,t=1:10) %>%
  add_constraint(y2[i, t] <= Q * sum_expr(x[j, i,t], j=1:3), i=1:3,t=1:10) %>%
  add_constraint(sum_expr(y1[i, t] ,t=1:10) <= s0[i], i=1:3) %>%
  add_constraint(sum_expr(y2[i, t] ,t=1:10) <= C[i] -s0[i] , i=1:3) %>%
  add_constraint(q0 + sum_expr(y1[i,t]-y2[i, t] ,i = 1:3, t = 1:t) >= 0 , t=1:10) %>%
  add_constraint(q0 + sum_expr(y1[i,t]-y2[i, t] ,i=1:3, t = 1:t) <= Q , t=1:10) %>%

  solve_model(with_ROI(solver = "glpk")) %>% 
  get_solution(x[i, j,t]) %>% 
  get_solution(y1[i, t]) %>%
  get_solution(y2[i, t]) %>%
  
  filter(value > 0) `

**Comment by ag2509** [comment]
hi, 
I seem to be having the same problem with my code and was wondering what you did to fix your issue?
thanks,
Em
