### ISSUE TITLE
Translating Julia into R with ompr.

### ISSUE THREAD

**Issue by chris13337** [dirkschumacher/ompr#286]
Hi I am trying to translate a 3-year-old Julia code to R because I am more familiar with R. I figured that maybe someone reading the Issues here or you yourself could help me.
 
I have this Julia code:
```julia
    @variable(m, used_team[i=1:num_teams], Bin)

    @constraint(m, constr[i=1:num_teams], used_team[i] <= sum{skaters_teams[t, i]*skaters_lineup[t], t=1:num_skaters})

    @constraint(m, sum{used_team[i], i=1:num_teams} >= 3)
```

and tried to write it in R like this:
```R
add_variable(used_team[i],i=1:num_teams, type = "binary")%>%
  add_constraint(used_team[i=1:num_teams] <= sum_expr(skaters_teams[t,1:num_teams]*skaters_lineups[t], t=1:num_skaters))%>%
  add_constraint(sum_expr(used_team[i], i=1:num_teams) >= 3)%>%
```

but i get this message: 

Error in check_for_unknown_vars_impl(model, the_ast) : 
  The expression contains a variable that is not part of the model.

How can I resolve this? 
thank you in advance!
KInd regards,

Christian

**Comment by dirkschumacher** [comment]
Would it be possible to create a reprex? Aka. the small, reproducible code example that produces that error? Then I can take a look. https://reprex.tidyverse.org/articles/reprex-dos-and-donts.html

**Comment by dirkschumacher** [comment]
I close this for now, but feel free to repost in the discussions.
