### ISSUE TITLE
Error: Unexpected operator '(' found

### ISSUE THREAD

**Issue by Eduardodudu** [dirkschumacher/ompr#287]
Hello, dirkschumacher!

I'm having an error with this model:

```{r}
model <- MIPModel() %>%

add_variable(x[i], i = 1:n, type = "integer", lb = 0) %>%

set_objective(sum_expr((if(sum_expr(x[i] * Matrix[i,j] < Demanda[i,2], j = 1:m)) {1} else {0}), i = 1:n), "min") %>%

add_constraint(sum_expr(x[i] * Matrix[i,j], i = 1:n) <= Contratos[j,2], j = 1:m)

```

The constraints and objective value seems to be correct when I check them with

```
model$constraints[1]
model$objective
```

Yet, I get the error "Error: Unexpected operator '(' found" when I try to solve it:

`result <- solve_model(model, with_ROI("glpk", verbose = TRUE))`

I think I'm using the wrong solver or maybe this package won't solve non-linear equations.

Could you clarify this to me? I've been digging on the web but couldn't find any solution on this matter.

**Comment by dirkschumacher** [comment]
You cannot use an if exression inside the objective function. If you want to do conditions you have to work with binary variables. E.g. create a variable y that has the value 1 if `sum_expr(x[i] * Matrix[i,j] < Demanda[i,2]` otherwise 0. Then put that variable in the objective function.

**Comment by devu123** [comment]
I did what dirkschumacher said, in the form of big M constraints - creating a variable y[i] and constraining sum_expr(x[1:n]) <= M*y[i] and sum_expr(x[1:n]) >= y[i]
be wary that this formulation greatly increases the computational complexity needed to solve this, depending on how many of these constraints you implement.

**Comment by dirkschumacher** [comment]
Thanks @devu123. Yeah it can make your model more complex. Having a single binary variable in the objective function looks a bit odd at first. Maybe there is another way to approach the problem without a 0/1 objective function. Another tip is to find an $M$ that is as small as possible.

**Comment by Eduardodudu** [comment]
Hello, dirkschumacher and devu123.

Thank you very much for your assistance! It was very helpfull.

I managed to solve it by including binary variable in the objective function and including it as a restriction for demand.

It solved the model in 107 mins. But it worked!

Thanks!

**Comment by sbmack** [comment]
> I managed to solve it by including binary variable in the objective function and including it as a restriction for demand.
> 
> It solved the model in 107 mins. But it worked!
> 
107 minutes is a long time.  How big is your model?

**Comment by Eduardodudu** [comment]
Hello @sbmack ! Sorry for the late answer. I haven't seen it.

I managed to solve this model by decomposing the graph and setting as a dataframe, then I run ompr as a function for each "cluster"


##  Creating Graph:
```
NM <- graph_from_data_frame(Contrato_Material)
components <- decompose(NM)

Contrato_Material <- data.frame(Cluster = 1:length(components)) %>%
  mutate(Resultado = map(components, ~as.data.frame(get.edgelist(..1)))) %>%
  unnest(Resultado)
```

##  Model as function

```
MODEL <- function(n,m,Demand,Contract,Matrix){

Contract <- as.data.frame(Contract)
Demand <- as.data.frame(Demand)

  model <- MIPModel() %>%
    
    # Variable of Demand
    add_variable(x[i,j], i = 1:n, j=1:m, type = "integer", lb = 0) %>%
    
    # Add binary variable
    add_variable(y[i], i = 1:n, type = "binary") %>%
    
    # Maximize demands fulfilled 
    set_objective(sum_expr(y[i], i = 1:n), "max") %>%
    
    #Restricted to Contracts capacity
    add_constraint(sum_expr(x[i,j] * Matrix[i,j], i = 1:n) <= Contract[j,2], j = 1:m) %>%
    
    #Restricted to demand binary
    add_constraint(sum_expr(x[i,j] * Matrix[i,j], j = 1:m) >= y[i]*Demand[i,2], i=1:n)
  
  #Solve
  result <- solve_model(model, with_ROI("glpk", verbose = TRUE))

  Contracts_tmp <- get_solution(result, x[i,j]) %>%
                   group_by(j) %>%
                   summarise(SUM = sum(value))

  Demand_tmp <- get_solution(result, x[i,j]) %>%
                group_by(i) %>%
                summarise(SUM = sum(value))
  
  Material <- cbind(Demand, Demand_tmp, get_solution(result, y[i]))
  
  Contrato <- cbind(Contract, Contracts_tmp) %>%
              mutate(Ruptura_Contrato = SUM > ValGlPend)
  
  Matriz <- get_solution(result, x[i,j]) %>%
            select(-variable) %>%
            spread(j, value)


  return(tibble(Result = result$objective_value, Contract = list(Contrato),
              Material = list(Material), Matriz = list(Matriz)))


}

```
## Result

```
Result <- DF %>%
  filter(n>1 | m>1) %>%
  mutate(Resultado = pmap(list(n,m,Demand, Contract, Matrix),
                          ~MODEL(..1,..2,..3,..4,..5)))
```
