### ISSUE TITLE
write.op() function fails.

### ISSUE THREAD

**Issue by sbmack** [dirkschumacher/ompr#288]
I've used the write.op function to view my formulation in standard form.  E.g.,

```
> library(ompr)
> library(ompr.roi)
> write.op(as_ROI_model(model), file_out, "lp_lpsolve")
```

Worked fine before but now it fails with the error msg:

```
Error in write.op(as_ROI_model(model), file_out, "lp_lpsolve") : 
  could not find function "write.op"
```
Has that function been removed?

**Comment by dirkschumacher** [comment]
The ROI folks might have renamed that function? Take a look at `ROI::ROI_write`

**Comment by sbmack** [comment]
> 
> 
> The ROI folks might have renamed that function? Take a look at `ROI::ROI_write`

Sorry for the delay in acknowledging your reply.  `ROI_write` works.  Thanks.
