### ISSUE TITLE
Unclear (to me) error message

### ISSUE THREAD

**Issue by CMBeale** [dirkschumacher/ompr#291]
I'm an ompr beginner, new also to MIP in general, so this may be trivial. I'm trying to run a relatively simple model, but get an error that talks about variable names and lengths that doesn't make any sense to me. I've based my code on a slightly extended knapsack problem, just to test that things make sense. 

Self-contained code that replicates the error is below

```
N <- c(10, 10, 200, 200, 200)
m <- c(100, 200, 250, 300, 1000)
s <- c(10, 100, 1000, 10, 200)

n <- NROW(N) 
B <- 10000

result <- MIPModel() %>% 
  ## variable to maximise is a vector of positive integers, one per site:
  add_variable(x[i], i = 1:n, type = "integer", lb = 0) %>% 
  ## objective is to maximise the sum over all sites of this function:
  set_objective(sum_expr(N[i] * exp(-.150 + (x[i]+s[i]) * 0.001), i = 1:n), "max") %>% 
  ## total sum of all xs must be under B
  add_constraint(sum_expr(x[i] * 1, i = 1:n) <= B) %>% 
  ## no one site can have a value above m for that site
  add_constraint(N[i] * exp(-.150 + (x[i]+s[i]) * 0.001) <= m[i], i = 1:n) %>% 
  ## solve it
  solve_model(with_ROI("glpk", verbose = TRUE))
get_solution(result, x[i]) 
```

I wonder (a) what is wrong with my code and (b) if a more informative error message could be provided in these cases to help someone like me?
Thanks!
Colin

**Comment by prof-anderson** [comment]
This usually happens when you have the same variable name used in ompr and outside of ompr in your general R environment.

The quick fix that I recommend to most people is prefixing your ompr variables with a "V" which serves two purposes.  

1.  You are likely to have R data objects named x or s but not Vx or Vs which helps to make them unique.
2.  It highlights in your ompr what are variables and what are data objects.

Tim

**Comment by CMBeale** [comment]
Thanks for the suggestion, but unless I'm much confused this isn't the case here - the code I submitted is self-contained and will run in a clean environment, but with the added 'V' suggestion it looks like this:

```
library(ompr)
library(maggritr)

N <- c(10, 10, 200, 200, 200)
m <- c(100, 200, 250, 300, 1000)
s <- c(10, 100, 1000, 10, 200)

n <- NROW(N) 
B <- 10000

result <- MIPModel() %>% 
  ## variable to maximise is a vector of positive integers, one per site:
  add_variable(Vx[i], i = 1:n, type = "integer", lb = 0) %>% 
  ## objective is to maximise the sum over all sites of this function:
  set_objective(sum_expr(N[i] * exp(-.150 + (Vx[i]+s[i]) * 0.001), i = 1:n), "max") %>% 
  ## total sum of all xs must be under B
  add_constraint(sum_expr(Vx[i] * 1, i = 1:n) <= B) %>% 
  ## no one site can have a value above m for that site
  add_constraint(N[i] * exp(-.150 + (Vx[i]+s[i]) * 0.001) <= m[i], i = 1:n) %>% 
  # solve it
  solve_model(with_ROI("glpk", verbose = TRUE))
get_solution(result, Vx[i]) 

```

**Comment by CMBeale** [comment]
So I've discovered that I don't get the error when I remove the exp from the expression, but I can't quite work out how sum_expr is evaluating and parsing things. If I use

`sum_expr(N[i] *(-.150 + (Vx[i]+s[i]) * 0.001)`
 
I get a sensible answer (but not to the problem I want)

If I use:
`sum_expr(DN[i] * 2.718282 ^ (-.150 + (Vx[i]+Ds[i]) * 0.001), i = 1:n)`

I get an answer that is incorrect (all Vx is set to 0, which is wrong) , and rather strangely, if I use:

`sum_expr(DN[i] * (2.718282 ^ (-.150 + (Vx[i]+Ds[i]) * 0.001)), i = 1:n)`

I get the same error message about names. Can anyone help here?

**Comment by sbmack** [comment]
The exponential function makes your model non-linear which is probably why the model works when you take it out.  glpk is a linear / mixed integer solver.

**Comment by CMBeale** [comment]
Ah, so would a different solver work, or is ompr completely the wrong place to be looking? Thanks!

**Comment by sbmack** [comment]
> 
> 
> Ah, so would a different solver work, or is ompr completely the wrong place to be looking? Thanks!

ompr is wrapper for ROI.  ROI does allow the formulation of non-linear models.  You can check out the solver list here:

https://cran.r-project.org/web/packages/ROI/index.html

I don't know if ompr can generate input files for non-linear models.  If not, you can use the ROI model interface instead.  The link above contains a link to a pdf of the user manual that describes how to generate the model parts.

**Comment by dirkschumacher** [comment]
Yeah you cannot use `ompr` for non-linear programs (only for linear programs in fact). As @sbmack says, try using ROI directly with a non-linear solver.
