### ISSUE TITLE
Difficulties in creating model

### ISSUE THREAD

**Issue by romanbuck** [dirkschumacher/ompr#294]
Dear Dirk, 

I am trying to convert a python model into R, using your package. I keep receiving the following error message:
```
Error in check_for_unknown_vars_impl(model, the_ast) : 
  The expression contains a variable that is not part of the model.
```
It might have something to do with the syntax I use.
If you have a minute, I would appreciate if you could have a look at the stackexchange thread and maybe leave a comment... :-)

https://or.stackexchange.com/questions/3455/reducing-number-of-suppliers-for-product-portfolio

Regards
Roman

**Comment by sbmack** [comment]
Roman, better to post your model code here so readers have a single site reference for making comments.

**Comment by romanbuck** [comment]
Hi there, 

my R model code is:

```
require(ompr)
require(ompr.roi)
require(dplyr)
require(ROI)
require(ROI.plugin.glpk)


test <-rbind(c(),
           c("Prd1", 1, NA, NA, NA, NA, NA, NA, 1, NA, NA, NA),
           c("Prd2",1, NA, NA, NA, NA, 1, NA, NA, NA, 1, NA),
           c("Prd3",NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA),
           c("Prd4",1, 1, 1, 1, NA, NA, NA, NA, NA, NA, NA),
           c("Prd5",NA, NA, NA, NA, NA, NA, 1, NA, NA, NA, NA),
           c("Prd6",1, NA, NA, NA, NA, 1, NA, NA, NA, 1, NA),
           c("Prd7",1, NA, NA, NA, 1, NA, NA, NA, 1, NA, NA),
           c("Prd8",NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA),
           c("Prd9",NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA))
dims <- dim(test)
test <- as.numeric(test)
dim(test) <- dims  
test.df <- data.frame(test)
colnames(test.df) <- c("Product","Sup1", "Sup2", "Sup3", "Sup4", "Sup5", "Sup6", "Sup7", "Sup8", "Sup9", "Sup10", "Sup11")
test.df[,1] <- c("Prd1","Prd2","Prd3","Prd4","Prd5","Prd6","Prd7","Prd8","Prd9")

n <- nrow(test.df) 
m <- ncol(test.df)
M <- 100
set_n <- range(0,n)
set_m <- range(0,m)

model <- MIPModel() %>%
  add_variable(b[i,j], i = set_n, j = set_m, type = "binary") %>%
  add_variable(x[j], j = set_m, type = "binary") %>%
  set_objective(sum_expr(b[i,j] * 2, i = set_n, j = set_m) - sum_expr(x[j], j = set_m)) %>%
  add_constraint((sum_expr(b[i,j], j = set_m)) <= 1) %>%
  add_constraint(M * x[j] >= sum_expr(b[i,j], i = set_n) - 1 + 0.001) %>%
  add_constraint(M * ( 1-  x[j]) >= ( 1 - sum_expr(b[i,j], i = set_n) - 0.001)) %>%
  solve_model(with_ROI(solver = "symphony", verbosity = 1)) %>%
  get_solution(x[i, j]) %>%
  filter(value > 0) %>%
  arrange(i)
```

However I think it is important to understand what I am trying to achieve with it.

Below is the correct description of my problem

[https://imgur.com/a/t1S4HeD](url)

(unfortunately I don't know how to embed an image here.)

**Comment by dirkschumacher** [comment]
This line produces a problem. The `i` is missing.
```R
add_constraint((sum_expr(b[i,j], j = set_m)) <= 1) %>%
```

A good strategy for debugging is to construct the model one constraint at a time to isolate the problem.

**Comment by anthonyshook** [comment]
I also get the impression that these two lines are not doing what you want them to be doing...
```
set_n <- range(0,n)
set_m <- range(0,m)
```
From looking at the python code, I'm thinking you want set_n to be equal to `1:n` -- but what you'll get here is `c(0, n)`.

**Comment by romanbuck** [comment]
Dear @anthonyshook and @dirkschumacher,
many thanks for your hints. I have now got the model running without errors. I still have to work out if the results are somehow meaningful, especially if applied on a bigger dataset. Please find the code below:


`require(ompr)
require(ompr.roi)
require(dplyr)
require(ROI)
require(ROI.plugin.glpk)

# Start building with those tools: https://dirkschumacher.github.io/ompr/articles/modelling.html
# This model: https://or.stackexchange.com/questions/3455/reducing-number-of-suppliers-for-product-portfolio

test <-rbind(c(),
           c("Prd1", 1, NA, NA, NA, NA, NA, NA, 1, NA, NA, NA),
           c("Prd2",1, NA, NA, NA, NA, 1, NA, NA, NA, 1, NA),
           c("Prd3",NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA),
           c("Prd4",1, 1, 1, 1, NA, NA, NA, NA, NA, NA, NA),
           c("Prd5",NA, NA, NA, NA, NA, NA, 1, NA, NA, NA, NA),
           c("Prd6",1, NA, NA, NA, NA, 1, NA, NA, NA, 1, NA),
           c("Prd7",1, NA, NA, NA, 1, NA, NA, NA, 1, NA, NA),
           c("Prd8",NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA),
           c("Prd9",NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA))
dims <- dim(test)
test <- as.numeric(test)
dim(test) <- dims  
test.df <- data.frame(test)
colnames(test.df) <- c("Product","Sup1", "Sup2", "Sup3", "Sup4", "Sup5", "Sup6", "Sup7", "Sup8", "Sup9", "Sup10", "Sup11")
test.df[,1] <- c("Prd1","Prd2","Prd3","Prd4","Prd5","Prd6","Prd7","Prd8","Prd9")

n <- nrow(test.df) 
m <- ncol(test.df)
M <- 100
set_n <- 0:n
set_m <- 0:m

model <- MIPModel() %>%
  add_variable(b[i,j], i = set_n, j = set_m, type = "binary") %>%
  add_variable(x[j], j = set_m, type = "binary") %>%
  set_objective(sum_expr(b[i,j] * 2, i = set_n, j = set_m) - sum_expr(x[j], j = set_m)) %>%
  add_constraint((sum_expr(b[i,j], j = set_m, i = set_n)) <= 1) %>% # added i = set_n
  add_constraint((M * sum_expr(x[j], j = set_m)) >= (sum_expr(b[i,j], i = set_n, j = set_m) - 1 + 0.001)) %>%
  add_constraint((M * ( 1-  sum_expr(x[j], j = set_m))) >= ( 1 - sum_expr(b[i,j], i = set_n, j = set_m) - 0.001)) %>%
  solve_model(with_ROI(solver = "symphony", verbosity = 1)) %>%
  get_solution(x[i, j]) %>%
  filter(value > 0) %>%
  arrange(i)`

The tricky part was actually adding the constraints. I had some bugs in there where I had not used 'sum_expr()', and also where the range was not set for all indices. Also as highlighted by @anthonyshook the 'range()' function was not doing what I was thinking it would :-)

Thanks
Roman

**Comment by sbmack** [comment]
A  useful diagnostic method is to write out the formulation in standard form and inspect it visually to ensure it is generating what you want.  Us just a subset of the data so it's easier to read.  ROI_write will generate a text file of a formulation.  It is not full featured.  I.e., it does not write out the actual variable names or multiple indexes but it can usually be interpreted.

**Comment by dirkschumacher** [comment]
> I haven't quite figured out how to create my initial matrix back from the results of the model (thereby showing the optimized solution). Any hints are appreciated.

The function `extract_constraints(model)` gives you the constraint matrix.
