### ISSUE TITLE
Different result using MIPModel() and MILPModel()

### ISSUE THREAD

**Issue by crcastro08** [dirkschumacher/ompr#295]
Hi, when I use the MIPModel I got different result from MILPModel. Comparing the result with other solvers, it seem like MIPModel give a correct result.
Someone else has found similar results?
Regards

**Comment by sbmack** [comment]
You probably first want to check that the same model formulation is being generated with both cases.  There are ompr functions that write out formulation info:
```
objective_function(model)
extract_constraints(model)
variable_bounds(model)
```
Also the ROI_write function writes out the model in standard form to a text file for visual inspection:

`ROI_write(as_ROI_model(model), file_out, "lp_lpsolve")`

**Comment by dirkschumacher** [comment]
It would be great if you post the smallest possible example where the two models yield different. Then it will be easier to identify what the problem is

**Comment by crcastro08** [comment]
Hi, thanks for your time..
I Attache the code with the model and the data I use to find the solution,
the code for both options is the same, I just change MIPModel for MILPModel.

Apparently it makes a different formulation but I don't understand why

Thank you for you help

[input.txt](https://github.com/dirkschumacher/ompr/files/4233279/input.txt)
[RCode.txt](https://github.com/dirkschumacher/ompr/files/4233282/RCode.txt)

**Comment by sbmack** [comment]
> **the code for both options is the same, I just change MIPModel for MILPModel.**
> 
The vector semantics for MILPModel are different from MIPModel.  See the Vectorized semantics revisited section at this link:

[https://dirkschumacher.github.io/ompr/articles/milp-modelling.html](url)

**Comment by crcastro08** [comment]
Thank you very much for the help,
