### ISSUE TITLE
Cross terms in objective

### ISSUE THREAD

**Issue by localoptimum** [dirkschumacher/ompr#297]
Hi Dirk,

I've been asked in a recent paper why I went straight to a metaheuristic model rather than trying MIP, and chose ompr to attempt a solution in R.  I'm a new user!

I'm adapting your warehouse allocation example to my problem of assigning items to positions.  I also need to quantify interference between neighbouring allocations, which would be like warehouses having a negative impact on each other depending on their separation, so there would be a tendency to space warehouses as far apart as possible.

If I use MIPModel(), in my set_objective() function I get an error message saying that the objective is probably non-linear.  If I use MILPModel(), I get an error saying "non-numeric argument to binary operator".

The code of my attempt is attached as a txt file, line 91 is the guilty party which I've labelled with 5 comments :)

Many thanks in advance for any help you can provide

Phil

[milpr.txt](https://github.com/dirkschumacher/ompr/files/4344616/milpr.txt)

**Comment by sbmack** [comment]
Your formulation cannot include non-linear terms with MIPModel or MILPModel.  You can include the penalty function using an auxiliary variable.  For simplicity, reduce the location variables to a single index: location, Xi  Then say X1 and X2 should have a proximity location penalty PI2.

So create the binary penalty pairing variable Z12 for X1 and X2.  I.e., if X1 = 1 AND X2 = 1, Z12 = 1.  The penalty term added to the objective function is P12 * Z12.

Now add a series of constraints for all of the locations that have a penalty pairing:

Z12 >= X1 + X2 - 1

If X1 = X2 = 1, then Z12 = 1 and the penalty is added.  For X1 + X2 < 2, Z12 = 0 to minimize the penalty.

So your model should include the relevant penalty pair variables and your data should include a vector of penalty values for each pair.

With me?

**Comment by localoptimum** [comment]
Hi sbmack,
Thanks for the quick reply.  I see what you are getting at, I'll try have a look this afternoon.

**Comment by localoptimum** [comment]
It was my suspicion too that the non-linearity was genuine.

**Comment by dirkdegel** [comment]
This might be helpful:
https://www.msi-jp.com/xpress/learning/square/10-mipformref.pdf

I think point 2.8 is what @sbmack mentioned.
