### ISSUE TITLE
How to solve a model written in ompr using neos server

### ISSUE THREAD

**Issue by dmresearch15** [dirkschumacher/ompr#298]
Hi Dirk,

Thanks in advance.

I'm able to solve the following example code given in your web site locally.

How can I solve it using neos server?

The code:

library(dplyr)
library(ROI)
library(ROI.plugin.glpk)
#library(ROI.plugin.cplex)
library(ompr)
library(ompr.roi)

# solver = glpk

result <- MIPModel() %>%
  add_variable(x, type = "integer") %>%
  add_variable(y, type = "continuous", lb = 0) %>%
  set_bounds(x, lb = 0) %>%
  set_objective(x + y, "max") %>%
  add_constraint(x + y <= 11.25) %>%
  solve_model(with_ROI(solver = "glpk")) 
get_solution(result, x)
get_solution(result, y)

Regards,

Deb

**Comment by dirkdegel** [comment]
Hi Beb,

I never tried it but maybe it works when you generate a *.lp or *.mps file. Normally a solver should be able to read this file types. I modified your code a bit.

```
library(dplyr)
library(ROI)
library(ROI.plugin.glpk)
#library(ROI.plugin.cplex)
library(ompr)
library(ompr.roi)
#solver = glpk

model <- MIPModel() %>%
add_variable(x, type = "integer") %>%
add_variable(y, type = "continuous", lb = 0) %>%
set_bounds(x, lb = 0) %>%
set_objective(x + y, "max") %>%
add_constraint(x + y <= 11.25) 

result <- solve_model(model, with_ROI(solver = "glpk"))
get_solution(result, x)
get_solution(result, y)

library(ROI.plugin.lpsolve)
roi_model <- as_ROI_model(model)
write.lp(roi_model, file = "./my_problem.lp", type = "lp")  # type=c("lp", "mps", "freemps")
``` 

Hope that helps.
Cheers Dirk

**Comment by dirkdegel** [comment]
Or maybe like this

```
ROI_write(roi_model, file = "my_problem_1.lp", type = "lp_cplex")
```

**Comment by dmresearch15** [comment]
Thanks Dirk. It helps.

**Comment by dirkschumacher** [comment]
I think there might be a NEOS ROI plugin. That would also work I believe.
