### ISSUE TITLE
how to write subset of a index in constraint

### ISSUE THREAD

**Issue by shuaiwang88** [dirkschumacher/ompr#302]
Hi Dirk,
I am working on a shift scheduling problem:

Shift is a set from 1:18
The shift_length(s) has two types: full time 8 hrs, and part time 5 hrs 
``` r 
shift_length
 [1] 8 8 8 8 8 8 8 8 8 5 5 5 5 5 5 5 5 5 5

full_time_ind <- which(shift_length > 6)
[1] 1 2 3 4 5 6 7 8 9
part_time_ind <- which(shift_length < 6
[1] 10 11 12 13 14 15 16 17 18 19
``` 
I want to add a constraint:
the total number of workers on full time shifts is at least 1.3 times of the part time workers. 
I tried this:
``` r
add_variable(y[s], s = 1:18, type = "integer", lb = 0) 
add_constraint(expr_sum(y[s], s = 1:18, s %in% full_time_ind) >=
                 expr_sum(y[s], s = 1:18, s %in% part_time_ind) * 
                   1.3)
``` 

which has error : The expression contains a variable that is not part of the model.
How to represent this subset of s? 

Thanks!
Shuai

**Comment by dirkdegel** [comment]
Hi Shuai,

I could figure out some minor issues:
- the length of your shift_length parameter is 19 not 18
- I think something with the "add_constraint" is wrong as well, but I'm not sure

Maybe this helps a bit (it worked on my machine):

```
library(tidyverse)

library(ompr)
library(ompr.roi)
library(ROI)
library(ROI.plugin.lpsolve)

shift_length <- c(8, 8, 8, 8, 8, 8, 8, 8, 8, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5) 
length(shift_length)

full_time_ind <- which(shift_length > 6)
part_time_ind <- which(shift_length < 6)


model <- MIPModel()
add_variable(model, y[s], s = 1:19, type = "integer", lb = 0) %>%
add_constraint(sum_expr(y[s], s = full_time_ind) >= 1.3 * sum_expr(y[s], s = part_time_ind))
```
Cheers Dirk

**Comment by shuaiwang88** [comment]
Hi dirk,
I found out I was using expr_sum instead of sum_expr. 

Thank you so much and stay healthy!

Shuai.
