### ISSUE TITLE
extract results where constraints failed

### ISSUE THREAD

**Issue by karthikkommalapati** [dirkschumacher/ompr#306]
Dear Drik,

I wouldn't say this is an issue, but I do not know how else to approach in this case.

I would like to extract results if a certain combination is not feasible and which constraint failed within that combination. Basically the opposite of the results, list out all the failed combination along with failed constraints. Is there a way to extract that information?

Kind Regards,
Karthik

**Comment by dirkschumacher** [comment]
`ompr` does not support that. What you probably want is an IIS. That is for example supported by Gurobi: https://or.stackexchange.com/a/2588
