### ISSUE TITLE
Constraints lhs Exploration

### ISSUE THREAD

**Issue by DSoot** [dirkschumacher/ompr#309]
Is there any way that I can explore the lhs table from constraints? What model$constraints[[1]]$lhs returns is an object of class "LinearVariableCollection". I need to make some checks by filtering it.

**Comment by dirkschumacher** [comment]
This is an S4 class, so you can access the variables using `@...`.

**Comment by dirkschumacher** [comment]
I close this but feel free to reopen if you still have a question

**Comment by DSoot** [comment]
Thank you!
