### ISSUE TITLE
performance issues?

### ISSUE THREAD

**Issue by shuaiwang88** [dirkschumacher/ompr#310]
Hi Dirk,

 I wrote an article comparing the speed of several packages for math modeling:
[constrution speed](https://medium.com/@vanstark88/construction-speed-in-popular-open-source-math-modeling-tools-712fd841fc50)

Here's the code for ompr:

a <- Sys.time()
n <- 500000

MIPModel() %>%
  add_variable(x[i], i = 1:n, type = "continuous") %>%
  set_objective(sum_expr(x[i] , i = 1:n), "min") %>%
  add_constraint(x[i] >=1 ) %>%
  solve_model(with_ROI(solver = "cbc")) 
b <- Sys.time()
b-a

The speed is significantly slower than other packages. 
Do you think this is apple to apple comparison?

Thanks,
Shuai

**Comment by dirkschumacher** [comment]
Yeah, It is quite slow indeed and I am working on improving it (#308 (just started to apply the linear part I tested in rmpk) and [rmpk](https://github.com/r-opt/rmpk)), but my free time and energy after work is limited :)

`MILPModel` was my first attempt to try a different way of modelling and storing the constraints/variables which is faster for a subset of models. `add_constraint(x[i] >=1 ) ` should probably be `add_constraint(x[i] >=1, i = 1:n)`. 

I will use your article as a benchmark for the upcoming developments :)

There are also other projects that might be worthwhile to explore:
* https://cvxr.rbind.io/ + its python version
* https://github.com/coin-or/pulp
* https://github.com/coin-or/python-mip

**Comment by sbmack** [comment]
> Yeah, It is quite slow indeed and I am working on improving it

I reduced n to 10 to test the model and got an expected error when I ran the code.
```
Error in check_for_unknown_vars_impl(model, the_ast) : 
  The expression contains a variable that is not part of the model.
```
The code failed at the constraint:

` add_constraint(x[i] >=1 )`

Which is obvious since i is not indexed and the x[i] are not summed.  Which makes the constraint unintelligible to the formulation engine.  The issue is the probably the ill formed constraint.

P.S. I am surprised the model ran for Dirk and the OP.

**Comment by sbmack** [comment]
Dirk,

FYI, since you closed this, I submitted a follow on comment that identifies a formulation error.

Regards,

Steve Mack
Arlington VA
USA

**Comment by dirkschumacher** [comment]
Thanks @sbmack. Yeah, I did not run but that is what I meant by
> add_constraint(x[i] >=1 ) should probably be add_constraint(x[i] >=1, i = 1:n).

@shuaiwang88 Also take a look at [Gravity](https://github.com/coin-or/Gravity) (pretty cool btw). They did some work comparing modelling languages. I think that would be worthwhile to read if you want to do a proper benchmark.

**Comment by sbmack** [comment]
> add_constraint(x[i] >=1 ) should probably be add_constraint(x[i] >=1, i = 1:n).

Dirk, thanks.  For the OP, that mod to the constraint definition would work and yield n single variable constraints, x[i] >= 1, which is essentially a lower bound on x[i].  I.e., you could set a lower bound of 1 for x[i] instead.  So I think you should think through your intent for the constraint(s).
