### ISSUE TITLE
Methods not working as intended in ompr

### ISSUE THREAD

**Issue by AnkurSMehta** [dirkschumacher/ompr#317]
**Methods not working as intended in ompr:**
The moment we invoke solve_model, 
variable_keys, extract_constraints, objective_function doesn't work,
The error it gives:
Error in UseMethod("variable_keys") : 
  no applicable method for 'variable_keys' applied to an object of class "solution"

If we set up the model without running solve_model, the above methods do work:
If we use solve_model separately, the get_solution method doesn't work
The error it gives:
Error in UseMethod("get_solution_") : 
  no applicable method for 'get_solution_' applied to an object of class "optimization_model"

Here's the code:
`model9 <- MIPModel() %>% add_variable(x[i], i=1:4,type='continuous') %>% 
  add_variable(y[i,j],i=1:4,j=1:6,type='continuous') %>% 
  add_constraint(x[i]+y[i,j] <= 5*i+j+1,i=1:4,j=1:6) %>% 
  set_objective(sum_expr(x[i]+y[i,j],i=1:4,j=6),'max') %>% solve_model(with_ROI("glpk"))

variable_keys(model9)
extract_constraints(model9)
objective_function(model9)

solve_model(model9, with_ROI("glpk"))`

**Comment by dirkschumacher** [comment]
The reason is that `model9` is of type `solution` as the last call in the chain was `solve_model(...)`.
