### ISSUE TITLE
add_constraint with Lead/Lag variables

### ISSUE THREAD

**Issue by jairocer** [dirkschumacher/ompr#326]
Hello,

I am new in R and familiarizing with the ompr package. I am trying to add a constraint to a model, and it includes lagging.

This is the constraint: **x[t] - x[t-1] + y[t] = C[t] , ∀t**. For example, if t=1:4, then the equations should be like
t=1:       x[1] -    0  +  y[1] = C[1]
t=2:       x[2] - x[1] + y[2] = C[2]
t=3:       x[3] - x[2] + y[3] = C[3]
t=4:       x[4] - x[3] + y[4] = C[4]
Any ideas in how to write the lagging in the **add_constraint(..., t =1:4)**

Thank you 
-JC

**Comment by dirkschumacher** [comment]
Would something like this work?

```R
library(magrittr)
library(ompr)
MIPModel() %>% 
  add_variable(x[i], i = 1:10) %>% 
  add_variable(y[i], i = 1:10) %>% 
  add_variable(Co[i], i = 1:10) %>% 
  add_constraint(x[1] + y[1] == Co[1]) %>% 
  add_constraint(x[t] - x[t-1] + y[t] == Co[t], t = 2:4)
```

**Comment by jairocer** [comment]
Thanks for the reply. I solved the issue by beginning the indexation of x from 0 (add_variable(x[t], t = 0:TT) ), and setting its initial condition to 0, i.e., x[0] == 0 .  


library(magrittr)
library(ompr)
Co <- c(1, 2, 3, 3, 2, 1, 7, 8, 9, 9)
TT = 10
MIPModel() %>% 
  add_variable(x[t], t = 0:TT) %>% 
  add_variable(y[t], t = 1:TT) %>% 
  
  add_constraint(x[t] - x[t-1] + y[t] == Co[t], t = 1:TT) %>% 
  add_constraint(x[0] == 0) %>%
