### ISSUE TITLE
Check Matrix and R-devel compatibility

### ISSUE THREAD

**Issue by dirkschumacher** [dirkschumacher/ompr#335]
There might be some breaking changes in the upcoming R-devel / Matrix package release.

**Comment by sbmack** [comment]
Sounds great!  Looking forward...

**Comment by dirkschumacher** [comment]
Everything seems to be fine (ran the package tests).

Environment:
```
FROM rocker/r-devel:latest

RUN apt-get install git-all libglpk-dev  r-cran-devtools  -y
RUN install2.r ROI.plugin.glpk
RUN install2.r ompr.roi
RUN Rscript -e 'install.packages("Matrix", repos = "http://R-Forge.R-project.org")'
RUN git clone https://github.com/dirkschumacher/ompr.roi.git
RUN git clone https://github.com/dirkschumacher/ompr.git
```

**Comment by sbmack** [comment]
> 
> 
> Everything seems to be fine (ran the package tests).
> 
> Environment:
> 
> ```
> FROM rocker/r-devel:latest
> 
> RUN apt-get install git-all libglpk-dev  r-cran-devtools  -y
> RUN install2.r ROI.plugin.glpk
> RUN install2.r ompr.roi
> RUN Rscript -e 'install.packages("Matrix", repos = "http://R-Forge.R-project.org")'
> RUN git clone https://github.com/dirkschumacher/ompr.roi.git
> RUN git clone https://github.com/dirkschumacher/ompr.git
> ```

Thanks Dirk.  But that is not R code.  Is it the installer?  Can you advise on installing from R or RStudio?  Thanks, SteveM

**Comment by dirkschumacher** [comment]
This is the content of a Dockerfile that I used to run the test in R-devel together with the new Matrix package from R-Forge.

**Comment by sbmack** [comment]
Dirk,

Great.  So this code will update the packages?

options(repos = c(
  ropt = 'https://r-opt.r-universe.dev',
  CRAN = 'https://cloud.r-project.org'))

# Install some packages
install.packages("rmpk")
install.packages("ROIoptimzer")

# load the packages
library(rmpk)
library(ROIoptimzer)
library(ROI.plugin.glpk)

Thanks,

SteveM

**Comment by sbmack** [comment]
Dirk,

I ran your block of code below.  Received this warning:

> install.packages("ROIoptimzer")
Installing package into 'C:/Users/sbmac/Documents/R/win-library/4.0'
(as 'lib' is unspecified)
Warning in install.packages :
  package 'ROIoptimzer' is not available for this version of R

I am running R 4.0.5  My installed version of ROIoptimizer is 0.0.0.9000

Steve

From: Stephen Mack
Sent: Thursday, April 22, 2021 6:49 PM
To: dirkschumacher/ompr ***@***.***>
Subject: RE: [dirkschumacher/ompr] Check Matrix and R-devel compatibility (#335)

Dirk,

Great.  So this code will update the packages?

options(repos = c(
  ropt = 'https://r-opt.r-universe.dev',
  CRAN = 'https://cloud.r-project.org'))

# Install some packages
install.packages("rmpk")
install.packages("ROIoptimzer")

# load the packages
library(rmpk)
library(ROIoptimzer)
library(ROI.plugin.glpk)

Thanks,

SteveM

**Comment by dirkschumacher** [comment]
ROIoptimzer is a different packages. What are you trying to do? :)

**Comment by sbmack** [comment]
Dirk,

Sorry for the misunderstanding.  With your "breaking changes" notice I was thinking that you had implemented new functionality in ROIoptimizer.

So your notice just validates that the updated Matrix package is still compatible with ompr, ompr.roi?

Thanks,

Steve
