### ISSUE TITLE
Relicense to MIT

### ISSUE THREAD

**Issue by dirkschumacher** [dirkschumacher/ompr#353]
In order to make the package licensing easier to understand and as permissive as possible, I would like to license the package code [MIT](https://choosealicense.com/licenses/mit/) from now on. Before I can do that I would like to ask the previous [contributors](https://github.com/dirkschumacher/ompr/graphs/contributors) for their OK or concerns.

- [x] @hugolarzabal 
- [x] @rtwalker

@rtwalker Github lists you as a contributor on the front page, but I cannot find the commits you made. 🤔

**Comment by hugolarzabal** [comment]
Hello Dirk,
Yes, I am ok with this obviously.

**Comment by rtwalker** [comment]
Relicense to MIT is ok by me! I believe my only contribution is in #177.

**Comment by dirkschumacher** [comment]
Thanks both!
