### ISSUE TITLE
Adding constraints is very slow

### ISSUE THREAD

**Issue by dirkschumacher** [dirkschumacher/ompr#6]

**Comment by dirkschumacher** [comment]
maybe PR #35  fixes it

**Comment by rickyars** [comment]
What are the other bottlenecks? I would like to help if I can. Right now the models I'm building are taking longer to create (specifically the add_constraint call) than to solve. This seems a bit weird.

**Comment by dirkschumacher** [comment]
Yes, it gets quite slow for larger models and indeed add_constraint is the slowest function so far I think. My goal was to first focus on a nice API and improve speed afterwards. 

PR #123 implements a new stack, that is about 4 times faster than the old implementation and speeds up some operations used in almost every function. However it fails on travis for certain r versions and I cannot reproduce the problem.

In general, it might be time to think about how to internally represent and build the model the most efficient way.

**Comment by rickyars** [comment]
I can't remember the last time I pulled the repo, but this has gotten so much faster. Thank you.
