### ISSUE TITLE
Standard evaluation version of functions

### ISSUE THREAD

**Issue by richierocks** [dirkschumacher/ompr#67]
Standard evaluation is often better for when you want to include code in your own packages.  Do you plan to include standard evaluation versions of the functions?  

I'm thinking of the *dplyr* style, for example `filter` vs. `filter_`. So you could include `add_variable_`, `set_obejctive_`, etc.

I think that most of the logic is handled by the *lazyeval* package, so it shouldn't be too tricky to implement.

**Comment by dirkschumacher** [comment]
Sounds like a good idea. How would that api look exactly? Pass in a lazyeval object or a character string?

**Comment by richierocks** [comment]
I think you want something like this:

```{r}
setGeneric("set_objective", function(model, expression, direction = "max") {
  set_objective_(model, expression = lazyeval::lazy(expression), direction = direction)
}

setGeneric("set_objective_", function(model, expression, direction = "max") {
  # As the current set_objective fn, but without calls to substitute
}
```

`expression` can be passed to `set_objective_` as a formula, string, or `quote`d expression.

BTW, if `direction` can only be "min" or "max", then you can check it by changing the signature to

```{r}
function(model, expression, direction = c("max", "min"))
```

then calling `direction <- match.arg(direction)` in the function body.

**Comment by dirkschumacher** [comment]
Cool thanks. Will look into this. Indeed, maybe I should use lazyeval instead of base R's eval/substitute constructs.

**Comment by dirkschumacher** [comment]
@richierocks Added a first version. If you have any comments on the code or other ideas let me know

**Comment by dirkschumacher** [comment]
:shipit: I close the issue for now.

**Comment by dirkschumacher** [comment]
Still needs a solution for variable and constraint quantifiers
