### ISSUE TITLE
Export model to MPS format

### ISSUE THREAD

**Issue by dirkschumacher** [dirkschumacher/ompr#93]
https://en.wikipedia.org/wiki/MPS_(format)

http://lpsolve.sourceforge.net/5.5/mps-format.htm

**Comment by ggsdc** [comment]
Hello,

I've been thinking of developing a function wo write the model into a MPS file, it could be based on the current function that the library `linprog` ([reference](https://github.com/cran/linprog/blob/master/R/writeMps.R))  has or the one in PuLP for python ([reference](https://github.com/coin-or/pulp/blob/master/src/pulp/pulp.py), see definition `writeMPS`).

I wanted to know if you have been working on this enhancement, in case you have something already done, or if you want me to send you the end result of the function to try include it in the future for `ompr`.

**Comment by znmeb** [comment]
MPS is a tad on the old side - isn't AMPL / GMPL / GNU MathProg a more widely used target?

**Comment by dirkschumacher** [comment]
MPS is definitely an old format but it can still be used as input for standard solvers. I haven't done anything on that topic. 

Some solvers available with ROI have the option to also output mps/lp files.

**Comment by prubin73** [comment]
Would it make sense to expose the ROI::write.op method? I think that would, for example, allow me to export either an LP format file or possibly a SAV file when using the CPLEX plug-in. This would require you to create an instance of the "OP" class when the model is defined (or, lazily, when the write method is called), as opposed to waiting until the solve method is invoked.

**Comment by dirkschumacher** [comment]
`ompr.roi` could expose a function called `as.op` which converts an `ompr` model to an `OP` object.

**Comment by dirkschumacher** [comment]
Let's discuss this in a seperate issue: https://github.com/dirkschumacher/ompr.roi/issues/9

**Comment by dirkschumacher** [comment]
Can be done using `ROI`.
